// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package input

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
	"github.com/depthbomb/win32defs/gdi"
	"github.com/depthbomb/win32defs/internal/nativebuffer"
	"github.com/depthbomb/win32defs/winmsg"
)

// GESTURECONFIG projects Windows.Win32.UI.Input.Touch.GESTURECONFIG.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-gestureconfig.
type GESTURECONFIG struct {
	DwID    GESTURECONFIG_ID
	DwWant  uint32
	DwBlock uint32
}

// GESTURECONFIG_ID projects Windows.Win32.UI.Input.Touch.GESTURECONFIG_ID.
type GESTURECONFIG_ID uint32

// GESTUREINFO is a view of native Windows.Win32.UI.Input.Touch.GESTUREINFO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-gestureinfo.
type GESTUREINFO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	GESTUREINFOSize               = 48 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	GESTUREINFOAlignment          = 8
	GESTUREINFOCbSizeOffset       = 0
	GESTUREINFODwFlagsOffset      = 4
	GESTUREINFODwIDOffset         = 8
	GESTUREINFOHwndTargetOffset   = 12 + (unsafe.Sizeof(uintptr(0))-4)/4*4
	GESTUREINFOPtsLocationOffset  = 16 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	GESTUREINFODwInstanceIDOffset = 20 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	GESTUREINFODwSequenceIDOffset = 24 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	GESTUREINFOUllArgumentsOffset = 32 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	GESTUREINFOCbExtraArgsOffset  = 40 + (unsafe.Sizeof(uintptr(0))-4)/4*8
)

// NewGESTUREINFO allocates zeroed, aligned native storage.
func NewGESTUREINFO() GESTUREINFO {
	return GESTUREINFO{data: nativebuffer.New(int(GESTUREINFOSize), uintptr(GESTUREINFOAlignment))}
}

// ViewGESTUREINFO shares data without copying. It panics if data is shorter than GESTUREINFOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewGESTUREINFO(data []byte) GESTUREINFO {
	return GESTUREINFO{data: nativebuffer.View(data, int(GESTUREINFOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b GESTUREINFO) Bytes() []byte {
	return b.data[:GESTUREINFOSize:GESTUREINFOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b GESTUREINFO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(GESTUREINFOAlignment))
}

// GetCbSize returns a copy of the native field value.
func (b GESTUREINFO) GetCbSize() uint32 {
	offset := uintptr(GESTUREINFOCbSizeOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCbSize copies value into the native field.
func (b GESTUREINFO) SetCbSize(value uint32) {
	offset := uintptr(GESTUREINFOCbSizeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwFlags returns a copy of the native field value.
func (b GESTUREINFO) GetDwFlags() uint32 {
	offset := uintptr(GESTUREINFODwFlagsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwFlags copies value into the native field.
func (b GESTUREINFO) SetDwFlags(value uint32) {
	offset := uintptr(GESTUREINFODwFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwID returns a copy of the native field value.
func (b GESTUREINFO) GetDwID() uint32 {
	offset := uintptr(GESTUREINFODwIDOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwID copies value into the native field.
func (b GESTUREINFO) SetDwID(value uint32) {
	offset := uintptr(GESTUREINFODwIDOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetHwndTarget returns a copy of the native field value.
func (b GESTUREINFO) GetHwndTarget() foundation.HWND {
	offset := uintptr(GESTUREINFOHwndTargetOffset)

	return nativebuffer.Read[foundation.HWND](b.Bytes()[offset : offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)])
}

// SetHwndTarget copies value into the native field.
func (b GESTUREINFO) SetHwndTarget(value foundation.HWND) {
	offset := uintptr(GESTUREINFOHwndTargetOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)], value)
}

// GetPtsLocation returns a copy of the native field value.
func (b GESTUREINFO) GetPtsLocation() foundation.POINTS {
	offset := uintptr(GESTUREINFOPtsLocationOffset)

	return nativebuffer.Read[foundation.POINTS](b.Bytes()[offset : offset+(4)])
}

// SetPtsLocation copies value into the native field.
func (b GESTUREINFO) SetPtsLocation(value foundation.POINTS) {
	offset := uintptr(GESTUREINFOPtsLocationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwInstanceID returns a copy of the native field value.
func (b GESTUREINFO) GetDwInstanceID() uint32 {
	offset := uintptr(GESTUREINFODwInstanceIDOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwInstanceID copies value into the native field.
func (b GESTUREINFO) SetDwInstanceID(value uint32) {
	offset := uintptr(GESTUREINFODwInstanceIDOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwSequenceID returns a copy of the native field value.
func (b GESTUREINFO) GetDwSequenceID() uint32 {
	offset := uintptr(GESTUREINFODwSequenceIDOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwSequenceID copies value into the native field.
func (b GESTUREINFO) SetDwSequenceID(value uint32) {
	offset := uintptr(GESTUREINFODwSequenceIDOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetUllArguments returns a copy of the native field value.
func (b GESTUREINFO) GetUllArguments() uint64 {
	offset := uintptr(GESTUREINFOUllArgumentsOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetUllArguments copies value into the native field.
func (b GESTUREINFO) SetUllArguments(value uint64) {
	offset := uintptr(GESTUREINFOUllArgumentsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCbExtraArgs returns a copy of the native field value.
func (b GESTUREINFO) GetCbExtraArgs() uint32 {
	offset := uintptr(GESTUREINFOCbExtraArgsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCbExtraArgs copies value into the native field.
func (b GESTUREINFO) SetCbExtraArgs(value uint32) {
	offset := uintptr(GESTUREINFOCbExtraArgsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GESTURENOTIFYSTRUCT projects Windows.Win32.UI.Input.Touch.GESTURENOTIFYSTRUCT.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-gesturenotifystruct.
type GESTURENOTIFYSTRUCT struct {
	CbSize       uint32
	DwFlags      uint32
	HwndTarget   foundation.HWND
	PtsLocation  foundation.POINTS
	DwInstanceID uint32
}

// HGESTUREINFO projects Windows.Win32.UI.Input.Touch.HGESTUREINFO.
type HGESTUREINFO uintptr

// HRAWINPUT projects Windows.Win32.UI.Input.HRAWINPUT.
type HRAWINPUT uintptr

// HSYNTHETICPOINTERDEVICE projects Windows.Win32.UI.Input.Pointer.HSYNTHETICPOINTERDEVICE.
type HSYNTHETICPOINTERDEVICE uintptr

// HTOUCHINPUT projects Windows.Win32.UI.Input.Touch.HTOUCHINPUT.
type HTOUCHINPUT uintptr

// INPUT_INJECTION_VALUE projects Windows.Win32.UI.Input.Pointer.INPUT_INJECTION_VALUE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-input_injection_value.
type INPUT_INJECTION_VALUE struct {
	Page  uint16
	Usage uint16
	Value int32
	Index uint16
}

// INPUT_MESSAGE_DEVICE_TYPE projects Windows.Win32.UI.Input.INPUT_MESSAGE_DEVICE_TYPE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-input_message_device_type.
type INPUT_MESSAGE_DEVICE_TYPE int32

// INPUT_MESSAGE_ORIGIN_ID projects Windows.Win32.UI.Input.INPUT_MESSAGE_ORIGIN_ID.
// See https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-input_message_origin_id.
type INPUT_MESSAGE_ORIGIN_ID int32

// INPUT_MESSAGE_SOURCE projects Windows.Win32.UI.Input.INPUT_MESSAGE_SOURCE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-input_message_source.
type INPUT_MESSAGE_SOURCE struct {
	DeviceType INPUT_MESSAGE_DEVICE_TYPE
	OriginId   INPUT_MESSAGE_ORIGIN_ID
}

// MOUSE_STATE projects Windows.Win32.UI.Input.MOUSE_STATE.
type MOUSE_STATE uint16

// POINTER_BUTTON_CHANGE_TYPE projects Windows.Win32.UI.Input.Pointer.POINTER_BUTTON_CHANGE_TYPE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-pointer_button_change_type.
type POINTER_BUTTON_CHANGE_TYPE int32

// POINTER_DEVICE_CURSOR_INFO projects Windows.Win32.UI.Input.Pointer.POINTER_DEVICE_CURSOR_INFO.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_device_cursor_info.
type POINTER_DEVICE_CURSOR_INFO struct {
	CursorId uint32
	Cursor   POINTER_DEVICE_CURSOR_TYPE
}

// POINTER_DEVICE_CURSOR_TYPE projects Windows.Win32.UI.Input.Pointer.POINTER_DEVICE_CURSOR_TYPE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-pointer_device_cursor_type.
type POINTER_DEVICE_CURSOR_TYPE int32

// POINTER_DEVICE_INFO projects Windows.Win32.UI.Input.Pointer.POINTER_DEVICE_INFO.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_device_info.
type POINTER_DEVICE_INFO struct {
	DisplayOrientation uint32
	Device             foundation.HANDLE
	PointerDeviceType  POINTER_DEVICE_TYPE
	Monitor            gdi.HMONITOR
	StartingCursorId   uint32
	MaxActiveContacts  uint16
	ProductString      [520]uint16
}

// POINTER_DEVICE_PROPERTY projects Windows.Win32.UI.Input.Pointer.POINTER_DEVICE_PROPERTY.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_device_property.
type POINTER_DEVICE_PROPERTY struct {
	LogicalMin   int32
	LogicalMax   int32
	PhysicalMin  int32
	PhysicalMax  int32
	Unit         uint32
	UnitExponent uint32
	UsagePageId  uint16
	UsageId      uint16
}

// POINTER_DEVICE_TYPE projects Windows.Win32.UI.Input.Pointer.POINTER_DEVICE_TYPE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-pointer_device_type.
type POINTER_DEVICE_TYPE int32

// POINTER_FLAGS projects Windows.Win32.UI.Input.Pointer.POINTER_FLAGS.
type POINTER_FLAGS uint32

// POINTER_INFO is a view of native Windows.Win32.UI.Input.Pointer.POINTER_INFO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_info.
type POINTER_INFO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	POINTER_INFOSize                        = 88 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOAlignment                   = 8
	POINTER_INFOPointerTypeOffset           = 0
	POINTER_INFOPointerIdOffset             = 4
	POINTER_INFOFrameIdOffset               = 8
	POINTER_INFOPointerFlagsOffset          = 12
	POINTER_INFOSourceDeviceOffset          = 16
	POINTER_INFOHwndTargetOffset            = 20 + (unsafe.Sizeof(uintptr(0))-4)/4*4
	POINTER_INFOPtPixelLocationOffset       = 24 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOPtHimetricLocationOffset    = 32 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOPtPixelLocationRawOffset    = 40 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOPtHimetricLocationRawOffset = 48 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFODwTimeOffset                = 56 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOHistoryCountOffset          = 60 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOInputDataOffset             = 64 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFODwKeyStatesOffset           = 68 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOPerformanceCountOffset      = 72 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_INFOButtonChangeTypeOffset      = 80 + (unsafe.Sizeof(uintptr(0))-4)/4*8
)

// NewPOINTER_INFO allocates zeroed, aligned native storage.
func NewPOINTER_INFO() POINTER_INFO {
	return POINTER_INFO{data: nativebuffer.New(int(POINTER_INFOSize), uintptr(POINTER_INFOAlignment))}
}

// ViewPOINTER_INFO shares data without copying. It panics if data is shorter than POINTER_INFOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewPOINTER_INFO(data []byte) POINTER_INFO {
	return POINTER_INFO{data: nativebuffer.View(data, int(POINTER_INFOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b POINTER_INFO) Bytes() []byte {
	return b.data[:POINTER_INFOSize:POINTER_INFOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b POINTER_INFO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(POINTER_INFOAlignment))
}

// GetPointerType returns a copy of the native field value.
func (b POINTER_INFO) GetPointerType() winmsg.POINTER_INPUT_TYPE {
	offset := uintptr(POINTER_INFOPointerTypeOffset)

	return nativebuffer.Read[winmsg.POINTER_INPUT_TYPE](b.Bytes()[offset : offset+(4)])
}

// SetPointerType copies value into the native field.
func (b POINTER_INFO) SetPointerType(value winmsg.POINTER_INPUT_TYPE) {
	offset := uintptr(POINTER_INFOPointerTypeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPointerId returns a copy of the native field value.
func (b POINTER_INFO) GetPointerId() uint32 {
	offset := uintptr(POINTER_INFOPointerIdOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetPointerId copies value into the native field.
func (b POINTER_INFO) SetPointerId(value uint32) {
	offset := uintptr(POINTER_INFOPointerIdOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetFrameId returns a copy of the native field value.
func (b POINTER_INFO) GetFrameId() uint32 {
	offset := uintptr(POINTER_INFOFrameIdOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetFrameId copies value into the native field.
func (b POINTER_INFO) SetFrameId(value uint32) {
	offset := uintptr(POINTER_INFOFrameIdOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPointerFlags returns a copy of the native field value.
func (b POINTER_INFO) GetPointerFlags() POINTER_FLAGS {
	offset := uintptr(POINTER_INFOPointerFlagsOffset)

	return nativebuffer.Read[POINTER_FLAGS](b.Bytes()[offset : offset+(4)])
}

// SetPointerFlags copies value into the native field.
func (b POINTER_INFO) SetPointerFlags(value POINTER_FLAGS) {
	offset := uintptr(POINTER_INFOPointerFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetSourceDevice returns a copy of the native field value.
func (b POINTER_INFO) GetSourceDevice() foundation.HANDLE {
	offset := uintptr(POINTER_INFOSourceDeviceOffset)

	return nativebuffer.Read[foundation.HANDLE](b.Bytes()[offset : offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)])
}

// SetSourceDevice copies value into the native field.
func (b POINTER_INFO) SetSourceDevice(value foundation.HANDLE) {
	offset := uintptr(POINTER_INFOSourceDeviceOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)], value)
}

// GetHwndTarget returns a copy of the native field value.
func (b POINTER_INFO) GetHwndTarget() foundation.HWND {
	offset := uintptr(POINTER_INFOHwndTargetOffset)

	return nativebuffer.Read[foundation.HWND](b.Bytes()[offset : offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)])
}

// SetHwndTarget copies value into the native field.
func (b POINTER_INFO) SetHwndTarget(value foundation.HWND) {
	offset := uintptr(POINTER_INFOHwndTargetOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)], value)
}

// GetPtPixelLocation returns a copy of the native field value.
func (b POINTER_INFO) GetPtPixelLocation() foundation.POINT {
	offset := uintptr(POINTER_INFOPtPixelLocationOffset)

	return nativebuffer.Read[foundation.POINT](b.Bytes()[offset : offset+(8)])
}

// SetPtPixelLocation copies value into the native field.
func (b POINTER_INFO) SetPtPixelLocation(value foundation.POINT) {
	offset := uintptr(POINTER_INFOPtPixelLocationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetPtHimetricLocation returns a copy of the native field value.
func (b POINTER_INFO) GetPtHimetricLocation() foundation.POINT {
	offset := uintptr(POINTER_INFOPtHimetricLocationOffset)

	return nativebuffer.Read[foundation.POINT](b.Bytes()[offset : offset+(8)])
}

// SetPtHimetricLocation copies value into the native field.
func (b POINTER_INFO) SetPtHimetricLocation(value foundation.POINT) {
	offset := uintptr(POINTER_INFOPtHimetricLocationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetPtPixelLocationRaw returns a copy of the native field value.
func (b POINTER_INFO) GetPtPixelLocationRaw() foundation.POINT {
	offset := uintptr(POINTER_INFOPtPixelLocationRawOffset)

	return nativebuffer.Read[foundation.POINT](b.Bytes()[offset : offset+(8)])
}

// SetPtPixelLocationRaw copies value into the native field.
func (b POINTER_INFO) SetPtPixelLocationRaw(value foundation.POINT) {
	offset := uintptr(POINTER_INFOPtPixelLocationRawOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetPtHimetricLocationRaw returns a copy of the native field value.
func (b POINTER_INFO) GetPtHimetricLocationRaw() foundation.POINT {
	offset := uintptr(POINTER_INFOPtHimetricLocationRawOffset)

	return nativebuffer.Read[foundation.POINT](b.Bytes()[offset : offset+(8)])
}

// SetPtHimetricLocationRaw copies value into the native field.
func (b POINTER_INFO) SetPtHimetricLocationRaw(value foundation.POINT) {
	offset := uintptr(POINTER_INFOPtHimetricLocationRawOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetDwTime returns a copy of the native field value.
func (b POINTER_INFO) GetDwTime() uint32 {
	offset := uintptr(POINTER_INFODwTimeOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwTime copies value into the native field.
func (b POINTER_INFO) SetDwTime(value uint32) {
	offset := uintptr(POINTER_INFODwTimeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetHistoryCount returns a copy of the native field value.
func (b POINTER_INFO) GetHistoryCount() uint32 {
	offset := uintptr(POINTER_INFOHistoryCountOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetHistoryCount copies value into the native field.
func (b POINTER_INFO) SetHistoryCount(value uint32) {
	offset := uintptr(POINTER_INFOHistoryCountOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetInputData returns a copy of the native field value.
func (b POINTER_INFO) GetInputData() int32 {
	offset := uintptr(POINTER_INFOInputDataOffset)

	return nativebuffer.Read[int32](b.Bytes()[offset : offset+(4)])
}

// SetInputData copies value into the native field.
func (b POINTER_INFO) SetInputData(value int32) {
	offset := uintptr(POINTER_INFOInputDataOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwKeyStates returns a copy of the native field value.
func (b POINTER_INFO) GetDwKeyStates() uint32 {
	offset := uintptr(POINTER_INFODwKeyStatesOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwKeyStates copies value into the native field.
func (b POINTER_INFO) SetDwKeyStates(value uint32) {
	offset := uintptr(POINTER_INFODwKeyStatesOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPerformanceCount returns a copy of the native field value.
func (b POINTER_INFO) GetPerformanceCount() uint64 {
	offset := uintptr(POINTER_INFOPerformanceCountOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetPerformanceCount copies value into the native field.
func (b POINTER_INFO) SetPerformanceCount(value uint64) {
	offset := uintptr(POINTER_INFOPerformanceCountOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetButtonChangeType returns a copy of the native field value.
func (b POINTER_INFO) GetButtonChangeType() POINTER_BUTTON_CHANGE_TYPE {
	offset := uintptr(POINTER_INFOButtonChangeTypeOffset)

	return nativebuffer.Read[POINTER_BUTTON_CHANGE_TYPE](b.Bytes()[offset : offset+(4)])
}

// SetButtonChangeType copies value into the native field.
func (b POINTER_INFO) SetButtonChangeType(value POINTER_BUTTON_CHANGE_TYPE) {
	offset := uintptr(POINTER_INFOButtonChangeTypeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// POINTER_PEN_INFO is a view of native Windows.Win32.UI.Input.Pointer.POINTER_PEN_INFO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_pen_info.
type POINTER_PEN_INFO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	POINTER_PEN_INFOSize              = 112 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFOAlignment         = 8
	POINTER_PEN_INFOPointerInfoOffset = 0
	POINTER_PEN_INFOPenFlagsOffset    = 88 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFOPenMaskOffset     = 92 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFOPressureOffset    = 96 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFORotationOffset    = 100 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFOTiltXOffset       = 104 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_PEN_INFOTiltYOffset       = 108 + (unsafe.Sizeof(uintptr(0))-4)/4*8
)

// NewPOINTER_PEN_INFO allocates zeroed, aligned native storage.
func NewPOINTER_PEN_INFO() POINTER_PEN_INFO {
	return POINTER_PEN_INFO{data: nativebuffer.New(int(POINTER_PEN_INFOSize), uintptr(POINTER_PEN_INFOAlignment))}
}

// ViewPOINTER_PEN_INFO shares data without copying. It panics if data is shorter than POINTER_PEN_INFOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewPOINTER_PEN_INFO(data []byte) POINTER_PEN_INFO {
	return POINTER_PEN_INFO{data: nativebuffer.View(data, int(POINTER_PEN_INFOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b POINTER_PEN_INFO) Bytes() []byte {
	return b.data[:POINTER_PEN_INFOSize:POINTER_PEN_INFOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b POINTER_PEN_INFO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(POINTER_PEN_INFOAlignment))
}

// GetPointerInfo returns a view sharing this buffer's storage.
func (b POINTER_PEN_INFO) GetPointerInfo() POINTER_INFO {
	offset := uintptr(POINTER_PEN_INFOPointerInfoOffset)

	return ViewPOINTER_INFO(b.Bytes()[offset : offset+(88+(unsafe.Sizeof(uintptr(0))-4)/4*8)])
}

// SetPointerInfo copies value into the native field.
func (b POINTER_PEN_INFO) SetPointerInfo(value POINTER_INFO) {
	offset := uintptr(POINTER_PEN_INFOPointerInfoOffset)
	copy(b.Bytes()[offset:offset+(88+(unsafe.Sizeof(uintptr(0))-4)/4*8)], value.Bytes())
}

// GetPenFlags returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetPenFlags() uint32 {
	offset := uintptr(POINTER_PEN_INFOPenFlagsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetPenFlags copies value into the native field.
func (b POINTER_PEN_INFO) SetPenFlags(value uint32) {
	offset := uintptr(POINTER_PEN_INFOPenFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPenMask returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetPenMask() uint32 {
	offset := uintptr(POINTER_PEN_INFOPenMaskOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetPenMask copies value into the native field.
func (b POINTER_PEN_INFO) SetPenMask(value uint32) {
	offset := uintptr(POINTER_PEN_INFOPenMaskOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPressure returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetPressure() uint32 {
	offset := uintptr(POINTER_PEN_INFOPressureOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetPressure copies value into the native field.
func (b POINTER_PEN_INFO) SetPressure(value uint32) {
	offset := uintptr(POINTER_PEN_INFOPressureOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetRotation returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetRotation() uint32 {
	offset := uintptr(POINTER_PEN_INFORotationOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetRotation copies value into the native field.
func (b POINTER_PEN_INFO) SetRotation(value uint32) {
	offset := uintptr(POINTER_PEN_INFORotationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetTiltX returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetTiltX() int32 {
	offset := uintptr(POINTER_PEN_INFOTiltXOffset)

	return nativebuffer.Read[int32](b.Bytes()[offset : offset+(4)])
}

// SetTiltX copies value into the native field.
func (b POINTER_PEN_INFO) SetTiltX(value int32) {
	offset := uintptr(POINTER_PEN_INFOTiltXOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetTiltY returns a copy of the native field value.
func (b POINTER_PEN_INFO) GetTiltY() int32 {
	offset := uintptr(POINTER_PEN_INFOTiltYOffset)

	return nativebuffer.Read[int32](b.Bytes()[offset : offset+(4)])
}

// SetTiltY copies value into the native field.
func (b POINTER_PEN_INFO) SetTiltY(value int32) {
	offset := uintptr(POINTER_PEN_INFOTiltYOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// POINTER_TOUCH_INFO is a view of native Windows.Win32.UI.Input.Pointer.POINTER_TOUCH_INFO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-pointer_touch_info.
type POINTER_TOUCH_INFO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	POINTER_TOUCH_INFOSize               = 136 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFOAlignment          = 8
	POINTER_TOUCH_INFOPointerInfoOffset  = 0
	POINTER_TOUCH_INFOTouchFlagsOffset   = 88 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFOTouchMaskOffset    = 92 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFORcContactOffset    = 96 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFORcContactRawOffset = 112 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFOOrientationOffset  = 128 + (unsafe.Sizeof(uintptr(0))-4)/4*8
	POINTER_TOUCH_INFOPressureOffset     = 132 + (unsafe.Sizeof(uintptr(0))-4)/4*8
)

// NewPOINTER_TOUCH_INFO allocates zeroed, aligned native storage.
func NewPOINTER_TOUCH_INFO() POINTER_TOUCH_INFO {
	return POINTER_TOUCH_INFO{data: nativebuffer.New(int(POINTER_TOUCH_INFOSize), uintptr(POINTER_TOUCH_INFOAlignment))}
}

// ViewPOINTER_TOUCH_INFO shares data without copying. It panics if data is shorter than POINTER_TOUCH_INFOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewPOINTER_TOUCH_INFO(data []byte) POINTER_TOUCH_INFO {
	return POINTER_TOUCH_INFO{data: nativebuffer.View(data, int(POINTER_TOUCH_INFOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b POINTER_TOUCH_INFO) Bytes() []byte {
	return b.data[:POINTER_TOUCH_INFOSize:POINTER_TOUCH_INFOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b POINTER_TOUCH_INFO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(POINTER_TOUCH_INFOAlignment))
}

// GetPointerInfo returns a view sharing this buffer's storage.
func (b POINTER_TOUCH_INFO) GetPointerInfo() POINTER_INFO {
	offset := uintptr(POINTER_TOUCH_INFOPointerInfoOffset)

	return ViewPOINTER_INFO(b.Bytes()[offset : offset+(88+(unsafe.Sizeof(uintptr(0))-4)/4*8)])
}

// SetPointerInfo copies value into the native field.
func (b POINTER_TOUCH_INFO) SetPointerInfo(value POINTER_INFO) {
	offset := uintptr(POINTER_TOUCH_INFOPointerInfoOffset)
	copy(b.Bytes()[offset:offset+(88+(unsafe.Sizeof(uintptr(0))-4)/4*8)], value.Bytes())
}

// GetTouchFlags returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetTouchFlags() uint32 {
	offset := uintptr(POINTER_TOUCH_INFOTouchFlagsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetTouchFlags copies value into the native field.
func (b POINTER_TOUCH_INFO) SetTouchFlags(value uint32) {
	offset := uintptr(POINTER_TOUCH_INFOTouchFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetTouchMask returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetTouchMask() uint32 {
	offset := uintptr(POINTER_TOUCH_INFOTouchMaskOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetTouchMask copies value into the native field.
func (b POINTER_TOUCH_INFO) SetTouchMask(value uint32) {
	offset := uintptr(POINTER_TOUCH_INFOTouchMaskOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetRcContact returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetRcContact() foundation.RECT {
	offset := uintptr(POINTER_TOUCH_INFORcContactOffset)

	return nativebuffer.Read[foundation.RECT](b.Bytes()[offset : offset+(16)])
}

// SetRcContact copies value into the native field.
func (b POINTER_TOUCH_INFO) SetRcContact(value foundation.RECT) {
	offset := uintptr(POINTER_TOUCH_INFORcContactOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(16)], value)
}

// GetRcContactRaw returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetRcContactRaw() foundation.RECT {
	offset := uintptr(POINTER_TOUCH_INFORcContactRawOffset)

	return nativebuffer.Read[foundation.RECT](b.Bytes()[offset : offset+(16)])
}

// SetRcContactRaw copies value into the native field.
func (b POINTER_TOUCH_INFO) SetRcContactRaw(value foundation.RECT) {
	offset := uintptr(POINTER_TOUCH_INFORcContactRawOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(16)], value)
}

// GetOrientation returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetOrientation() uint32 {
	offset := uintptr(POINTER_TOUCH_INFOOrientationOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetOrientation copies value into the native field.
func (b POINTER_TOUCH_INFO) SetOrientation(value uint32) {
	offset := uintptr(POINTER_TOUCH_INFOOrientationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetPressure returns a copy of the native field value.
func (b POINTER_TOUCH_INFO) GetPressure() uint32 {
	offset := uintptr(POINTER_TOUCH_INFOPressureOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetPressure copies value into the native field.
func (b POINTER_TOUCH_INFO) SetPressure(value uint32) {
	offset := uintptr(POINTER_TOUCH_INFOPressureOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// RAWHID projects Windows.Win32.UI.Input.RAWHID.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rawhid.
type RAWHID struct {
	DwSizeHid uint32
	DwCount   uint32
	// Flexible array: this is the metadata-declared initial extent.
	// Additional elements require a larger native allocation.
	BRawData [1]uint8
}

// RAWINPUTDEVICE projects Windows.Win32.UI.Input.RAWINPUTDEVICE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rawinputdevice.
type RAWINPUTDEVICE struct {
	UsUsagePage uint16
	UsUsage     uint16
	DwFlags     RAWINPUTDEVICE_FLAGS
	HwndTarget  foundation.HWND
}

// RAWINPUTDEVICELIST projects Windows.Win32.UI.Input.RAWINPUTDEVICELIST.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rawinputdevicelist.
type RAWINPUTDEVICELIST struct {
	HDevice foundation.HANDLE
	DwType  RID_DEVICE_INFO_TYPE
}

// RAWINPUTDEVICE_FLAGS projects Windows.Win32.UI.Input.RAWINPUTDEVICE_FLAGS.
type RAWINPUTDEVICE_FLAGS uint32

// RAWINPUTHEADER projects Windows.Win32.UI.Input.RAWINPUTHEADER.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rawinputheader.
type RAWINPUTHEADER struct {
	DwType  uint32
	DwSize  uint32
	HDevice foundation.HANDLE
	WParam  foundation.WPARAM
}

// RAWKEYBOARD projects Windows.Win32.UI.Input.RAWKEYBOARD.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rawkeyboard.
type RAWKEYBOARD struct {
	MakeCode         uint16
	Flags            uint16
	Reserved         uint16
	VKey             uint16
	Message          uint32
	ExtraInformation uint32
}

// RID_DEVICE_INFO_HID projects Windows.Win32.UI.Input.RID_DEVICE_INFO_HID.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rid_device_info_hid.
type RID_DEVICE_INFO_HID struct {
	DwVendorId      uint32
	DwProductId     uint32
	DwVersionNumber uint32
	UsUsagePage     uint16
	UsUsage         uint16
}

// RID_DEVICE_INFO_KEYBOARD projects Windows.Win32.UI.Input.RID_DEVICE_INFO_KEYBOARD.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rid_device_info_keyboard.
type RID_DEVICE_INFO_KEYBOARD struct {
	DwType                 uint32
	DwSubType              uint32
	DwKeyboardMode         uint32
	DwNumberOfFunctionKeys uint32
	DwNumberOfIndicators   uint32
	DwNumberOfKeysTotal    uint32
}

// RID_DEVICE_INFO_MOUSE projects Windows.Win32.UI.Input.RID_DEVICE_INFO_MOUSE.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-rid_device_info_mouse.
type RID_DEVICE_INFO_MOUSE struct {
	DwId                uint32
	DwNumberOfButtons   uint32
	DwSampleRate        uint32
	FHasHorizontalWheel foundation.BOOL
}

// RID_DEVICE_INFO_TYPE projects Windows.Win32.UI.Input.RID_DEVICE_INFO_TYPE.
type RID_DEVICE_INFO_TYPE uint32

// TOUCHEVENTF_FLAGS projects Windows.Win32.UI.Input.Touch.TOUCHEVENTF_FLAGS.
type TOUCHEVENTF_FLAGS uint32

// TOUCHINPUT projects Windows.Win32.UI.Input.Touch.TOUCHINPUT.
// See https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-touchinput.
type TOUCHINPUT struct {
	X           int32
	Y           int32
	HSource     foundation.HANDLE
	DwID        uint32
	DwFlags     TOUCHEVENTF_FLAGS
	DwMask      TOUCHINPUTMASKF_MASK
	DwTime      uint32
	DwExtraInfo uintptr
	CxContact   uint32
	CyContact   uint32
}

// TOUCHINPUTMASKF_MASK projects Windows.Win32.UI.Input.Touch.TOUCHINPUTMASKF_MASK.
type TOUCHINPUTMASKF_MASK uint32

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [12]byte                                        = [unsafe.Sizeof(*new(GESTURECONFIG))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(GESTURECONFIG))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(GESTURECONFIG{}.DwID)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(GESTURECONFIG{}.DwWant)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(GESTURECONFIG{}.DwBlock)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(GESTURECONFIG_ID))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(GESTURECONFIG_ID))]byte{}
	_ [20 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Sizeof(*new(GESTURENOTIFYSTRUCT))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(GESTURENOTIFYSTRUCT))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(GESTURENOTIFYSTRUCT{}.CbSize)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(GESTURENOTIFYSTRUCT{}.DwFlags)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(GESTURENOTIFYSTRUCT{}.HwndTarget)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(GESTURENOTIFYSTRUCT{}.PtsLocation)]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(GESTURENOTIFYSTRUCT{}.DwInstanceID)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Sizeof(*new(HGESTUREINFO))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(HGESTUREINFO))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Sizeof(*new(HRAWINPUT))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(HRAWINPUT))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Sizeof(*new(HSYNTHETICPOINTERDEVICE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(HSYNTHETICPOINTERDEVICE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Sizeof(*new(HTOUCHINPUT))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(HTOUCHINPUT))]byte{}
	_ [12]byte                                        = [unsafe.Sizeof(*new(INPUT_INJECTION_VALUE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(INPUT_INJECTION_VALUE))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(INPUT_INJECTION_VALUE{}.Page)]byte{}
	_ [2]byte                                         = [unsafe.Offsetof(INPUT_INJECTION_VALUE{}.Usage)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(INPUT_INJECTION_VALUE{}.Value)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(INPUT_INJECTION_VALUE{}.Index)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(INPUT_MESSAGE_DEVICE_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(INPUT_MESSAGE_DEVICE_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(INPUT_MESSAGE_ORIGIN_ID))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(INPUT_MESSAGE_ORIGIN_ID))]byte{}
	_ [8]byte                                         = [unsafe.Sizeof(*new(INPUT_MESSAGE_SOURCE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(INPUT_MESSAGE_SOURCE))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(INPUT_MESSAGE_SOURCE{}.DeviceType)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(INPUT_MESSAGE_SOURCE{}.OriginId)]byte{}
	_ [2]byte                                         = [unsafe.Sizeof(*new(MOUSE_STATE))]byte{}
	_ [2]byte                                         = [unsafe.Alignof(*new(MOUSE_STATE))]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(POINTER_BUTTON_CHANGE_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_BUTTON_CHANGE_TYPE))]byte{}
	_ [8]byte                                         = [unsafe.Sizeof(*new(POINTER_DEVICE_CURSOR_INFO))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_DEVICE_CURSOR_INFO))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_CURSOR_INFO{}.CursorId)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_CURSOR_INFO{}.Cursor)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(POINTER_DEVICE_CURSOR_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_DEVICE_CURSOR_TYPE))]byte{}
	_ [1064 + (unsafe.Sizeof(uintptr(0))-4)/4*16]byte = [unsafe.Sizeof(*new(POINTER_DEVICE_INFO))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(POINTER_DEVICE_INFO))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.DisplayOrientation)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.Device)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte     = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.PointerDeviceType)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*12]byte   = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.Monitor)]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*16]byte   = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.StartingCursorId)]byte{}
	_ [20 + (unsafe.Sizeof(uintptr(0))-4)/4*16]byte   = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.MaxActiveContacts)]byte{}
	_ [22 + (unsafe.Sizeof(uintptr(0))-4)/4*16]byte   = [unsafe.Offsetof(POINTER_DEVICE_INFO{}.ProductString)]byte{}
	_ [28]byte                                        = [unsafe.Sizeof(*new(POINTER_DEVICE_PROPERTY))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_DEVICE_PROPERTY))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.LogicalMin)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.LogicalMax)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.PhysicalMin)]byte{}
	_ [12]byte                                        = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.PhysicalMax)]byte{}
	_ [16]byte                                        = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.Unit)]byte{}
	_ [20]byte                                        = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.UnitExponent)]byte{}
	_ [24]byte                                        = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.UsagePageId)]byte{}
	_ [26]byte                                        = [unsafe.Offsetof(POINTER_DEVICE_PROPERTY{}.UsageId)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(POINTER_DEVICE_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_DEVICE_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(POINTER_FLAGS))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(POINTER_FLAGS))]byte{}
	_ [12]byte                                        = [unsafe.Sizeof(*new(RAWHID))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RAWHID))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RAWHID{}.DwSizeHid)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RAWHID{}.DwCount)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RAWHID{}.BRawData)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Sizeof(*new(RAWINPUTDEVICE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(RAWINPUTDEVICE))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RAWINPUTDEVICE{}.UsUsagePage)]byte{}
	_ [2]byte                                         = [unsafe.Offsetof(RAWINPUTDEVICE{}.UsUsage)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RAWINPUTDEVICE{}.DwFlags)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RAWINPUTDEVICE{}.HwndTarget)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte     = [unsafe.Sizeof(*new(RAWINPUTDEVICELIST))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(RAWINPUTDEVICELIST))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RAWINPUTDEVICELIST{}.HDevice)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Offsetof(RAWINPUTDEVICELIST{}.DwType)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(RAWINPUTDEVICE_FLAGS))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RAWINPUTDEVICE_FLAGS))]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte    = [unsafe.Sizeof(*new(RAWINPUTHEADER))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(RAWINPUTHEADER))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RAWINPUTHEADER{}.DwType)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RAWINPUTHEADER{}.DwSize)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RAWINPUTHEADER{}.HDevice)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(RAWINPUTHEADER{}.WParam)]byte{}
	_ [16]byte                                        = [unsafe.Sizeof(*new(RAWKEYBOARD))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RAWKEYBOARD))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RAWKEYBOARD{}.MakeCode)]byte{}
	_ [2]byte                                         = [unsafe.Offsetof(RAWKEYBOARD{}.Flags)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RAWKEYBOARD{}.Reserved)]byte{}
	_ [6]byte                                         = [unsafe.Offsetof(RAWKEYBOARD{}.VKey)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RAWKEYBOARD{}.Message)]byte{}
	_ [12]byte                                        = [unsafe.Offsetof(RAWKEYBOARD{}.ExtraInformation)]byte{}
	_ [16]byte                                        = [unsafe.Sizeof(*new(RID_DEVICE_INFO_HID))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RID_DEVICE_INFO_HID))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_HID{}.DwVendorId)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_HID{}.DwProductId)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_HID{}.DwVersionNumber)]byte{}
	_ [12]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_HID{}.UsUsagePage)]byte{}
	_ [14]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_HID{}.UsUsage)]byte{}
	_ [24]byte                                        = [unsafe.Sizeof(*new(RID_DEVICE_INFO_KEYBOARD))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RID_DEVICE_INFO_KEYBOARD))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwType)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwSubType)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwKeyboardMode)]byte{}
	_ [12]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwNumberOfFunctionKeys)]byte{}
	_ [16]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwNumberOfIndicators)]byte{}
	_ [20]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_KEYBOARD{}.DwNumberOfKeysTotal)]byte{}
	_ [16]byte                                        = [unsafe.Sizeof(*new(RID_DEVICE_INFO_MOUSE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RID_DEVICE_INFO_MOUSE))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_MOUSE{}.DwId)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_MOUSE{}.DwNumberOfButtons)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(RID_DEVICE_INFO_MOUSE{}.DwSampleRate)]byte{}
	_ [12]byte                                        = [unsafe.Offsetof(RID_DEVICE_INFO_MOUSE{}.FHasHorizontalWheel)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(RID_DEVICE_INFO_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(RID_DEVICE_INFO_TYPE))]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(TOUCHEVENTF_FLAGS))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(TOUCHEVENTF_FLAGS))]byte{}
	_ [40 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte    = [unsafe.Sizeof(*new(TOUCHINPUT))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte     = [unsafe.Alignof(*new(TOUCHINPUT))]byte{}
	_ [0]byte                                         = [unsafe.Offsetof(TOUCHINPUT{}.X)]byte{}
	_ [4]byte                                         = [unsafe.Offsetof(TOUCHINPUT{}.Y)]byte{}
	_ [8]byte                                         = [unsafe.Offsetof(TOUCHINPUT{}.HSource)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(TOUCHINPUT{}.DwID)]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(TOUCHINPUT{}.DwFlags)]byte{}
	_ [20 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(TOUCHINPUT{}.DwMask)]byte{}
	_ [24 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(TOUCHINPUT{}.DwTime)]byte{}
	_ [28 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte    = [unsafe.Offsetof(TOUCHINPUT{}.DwExtraInfo)]byte{}
	_ [32 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte    = [unsafe.Offsetof(TOUCHINPUT{}.CxContact)]byte{}
	_ [36 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte    = [unsafe.Offsetof(TOUCHINPUT{}.CyContact)]byte{}
	_ [4]byte                                         = [unsafe.Sizeof(*new(TOUCHINPUTMASKF_MASK))]byte{}
	_ [4]byte                                         = [unsafe.Alignof(*new(TOUCHINPUTMASKF_MASK))]byte{}
)
