// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).
// Documentation: Microsoft.Windows.SDK.Win32Docs 0.1.42-alpha (e83bf398dceb1957d698d24daa8a23f986beedb0109727a0ee99b229a525230b).

// Package pipes provides named-pipe access, modes, and operation flags.
package pipes

// Value is the common representation used by this package.
type Value uint32

const (
	NMPWAIT_NOWAIT Value = 0x00000001
	// NMPWAIT_USE_DEFAULT_WAIT: Documentation varies per use. Refer to each: WaitNamedPipe , WaitNamedPipe ,
	// WaitNamedPipeA , WaitNamedPipeW , WaitNamedPipeW .
	NMPWAIT_USE_DEFAULT_WAIT Value = 0x00000000
	// NMPWAIT_WAIT_FOREVER: The function does not return until an instance of the named pipe is available.
	NMPWAIT_WAIT_FOREVER       Value = 0xFFFFFFFF
	PIPE_ACCEPT_REMOTE_CLIENTS Value = 0x00000000
	PIPE_ACCESS_DUPLEX         Value = 0x00000003
	PIPE_ACCESS_INBOUND        Value = 0x00000001
	PIPE_ACCESS_OUTBOUND       Value = 0x00000002
	// PIPE_CLIENT_END: The handle refers to the client end of a named pipe instance. This is the default.
	PIPE_CLIENT_END Value = 0x00000000
	// PIPE_NOWAIT: The pipe handle is in nonblocking mode. If this flag is not specified, the pipe handle is in blocking
	// mode.
	PIPE_NOWAIT        Value = 0x00000001
	PIPE_READMODE_BYTE Value = 0x00000000
	// PIPE_READMODE_MESSAGE: The pipe handle is in message-read mode. If this flag is not specified, the pipe handle is in
	// byte-read mode.
	PIPE_READMODE_MESSAGE      Value = 0x00000002
	PIPE_REJECT_REMOTE_CLIENTS Value = 0x00000008
	// PIPE_SERVER_END: The handle refers to the server end of a named pipe instance. If this value is not specified, the
	// handle refers to the client end of a named pipe instance.
	PIPE_SERVER_END Value = 0x00000001
	// PIPE_TYPE_BYTE: The named pipe is a byte pipe. This is the default.
	PIPE_TYPE_BYTE Value = 0x00000000
	// PIPE_TYPE_MESSAGE: The named pipe is a message pipe. If this value is not specified, the pipe is a byte pipe.
	PIPE_TYPE_MESSAGE        Value = 0x00000004
	PIPE_UNLIMITED_INSTANCES Value = 0x000000FF
	PIPE_WAIT                Value = 0x00000000
)

// Name returns the canonical symbolic name for value.
func Name(value Value) (string, bool) {
	switch value {
	case Value(0x00000000):
		return "NMPWAIT_USE_DEFAULT_WAIT", true
	case Value(0x00000001):
		return "NMPWAIT_NOWAIT", true
	case Value(0x00000002):
		return "PIPE_ACCESS_OUTBOUND", true
	case Value(0x00000003):
		return "PIPE_ACCESS_DUPLEX", true
	case Value(0x00000004):
		return "PIPE_TYPE_MESSAGE", true
	case Value(0x00000008):
		return "PIPE_REJECT_REMOTE_CLIENTS", true
	case Value(0x000000FF):
		return "PIPE_UNLIMITED_INSTANCES", true
	case Value(0xFFFFFFFF):
		return "NMPWAIT_WAIT_FOREVER", true
	default:
		return "", false
	}
}

// Names returns every symbolic alias for value in lexical order.
func Names(value Value) []string {
	switch value {
	case Value(0x00000000):
		return []string{"NMPWAIT_USE_DEFAULT_WAIT", "PIPE_ACCEPT_REMOTE_CLIENTS", "PIPE_CLIENT_END", "PIPE_READMODE_BYTE", "PIPE_TYPE_BYTE", "PIPE_WAIT"}
	case Value(0x00000001):
		return []string{"NMPWAIT_NOWAIT", "PIPE_ACCESS_INBOUND", "PIPE_NOWAIT", "PIPE_SERVER_END"}
	case Value(0x00000002):
		return []string{"PIPE_ACCESS_OUTBOUND", "PIPE_READMODE_MESSAGE"}
	case Value(0x00000003):
		return []string{"PIPE_ACCESS_DUPLEX"}
	case Value(0x00000004):
		return []string{"PIPE_TYPE_MESSAGE"}
	case Value(0x00000008):
		return []string{"PIPE_REJECT_REMOTE_CLIENTS"}
	case Value(0x000000FF):
		return []string{"PIPE_UNLIMITED_INSTANCES"}
	case Value(0xFFFFFFFF):
		return []string{"NMPWAIT_WAIT_FOREVER"}
	default:
		return nil
	}
}

// Parse returns the numeric value associated with an exact symbolic name.
func Parse(name string) (Value, bool) {
	switch name {
	case "NMPWAIT_NOWAIT":
		return NMPWAIT_NOWAIT, true
	case "NMPWAIT_USE_DEFAULT_WAIT":
		return NMPWAIT_USE_DEFAULT_WAIT, true
	case "NMPWAIT_WAIT_FOREVER":
		return NMPWAIT_WAIT_FOREVER, true
	case "PIPE_ACCEPT_REMOTE_CLIENTS":
		return PIPE_ACCEPT_REMOTE_CLIENTS, true
	case "PIPE_ACCESS_DUPLEX":
		return PIPE_ACCESS_DUPLEX, true
	case "PIPE_ACCESS_INBOUND":
		return PIPE_ACCESS_INBOUND, true
	case "PIPE_ACCESS_OUTBOUND":
		return PIPE_ACCESS_OUTBOUND, true
	case "PIPE_CLIENT_END":
		return PIPE_CLIENT_END, true
	case "PIPE_NOWAIT":
		return PIPE_NOWAIT, true
	case "PIPE_READMODE_BYTE":
		return PIPE_READMODE_BYTE, true
	case "PIPE_READMODE_MESSAGE":
		return PIPE_READMODE_MESSAGE, true
	case "PIPE_REJECT_REMOTE_CLIENTS":
		return PIPE_REJECT_REMOTE_CLIENTS, true
	case "PIPE_SERVER_END":
		return PIPE_SERVER_END, true
	case "PIPE_TYPE_BYTE":
		return PIPE_TYPE_BYTE, true
	case "PIPE_TYPE_MESSAGE":
		return PIPE_TYPE_MESSAGE, true
	case "PIPE_UNLIMITED_INSTANCES":
		return PIPE_UNLIMITED_INSTANCES, true
	case "PIPE_WAIT":
		return PIPE_WAIT, true
	default:
		return Value(0), false
	}
}
