// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.25-preview (65783efbef7950839ae287fa933610eb939fcddaef80024dea8465f37a9449ad).
// Documentation: Microsoft.Windows.SDK.Win32Docs 0.1.42-alpha (e83bf398dceb1957d698d24daa8a23f986beedb0109727a0ee99b229a525230b).

// Package sysinfo provides system architecture, product, version, and processor information values.
package sysinfo

// Value is the common representation used by this package.
type Value uint32

const (
	ACPI Value = 0x41435049
	// CacheData: The cache is for data.
	CacheData Value = 0x00000002
	// CacheInstruction: The cache is for processor instructions.
	CacheInstruction Value = 0x00000001
	// CacheTrace: The cache is for traces.
	CacheTrace Value = 0x00000003
	// CacheUnified: The cache is unified.
	CacheUnified Value = 0x00000000
	CacheUnknown Value = 0x00000004
	// ComputerNameDnsDomain: The name of the DNS domain assigned to the local computer or the cluster associated with the
	// local computer.
	ComputerNameDnsDomain Value = 0x00000002
	// ComputerNameDnsFullyQualified: The fully qualified DNS name that uniquely identifies the local computer or the
	// cluster associated with the local computer. This name is a combination of the DNS host name and the DNS domain name,
	// using the form HostName . DomainName . For example, if the DNS host name is "corporate-mail-server" and the DNS
	// domain name is "microsoft.com", the fully qualified DNS name is "corporate-mail-server.microsoft.com".
	ComputerNameDnsFullyQualified Value = 0x00000003
	// ComputerNameDnsHostname: The DNS name of the local computer or the cluster associated with the local computer.
	ComputerNameDnsHostname Value = 0x00000001
	// ComputerNameMax: Not used.
	ComputerNameMax Value = 0x00000008
	// ComputerNameNetBIOS: The NetBIOS name of the local computer or the cluster associated with the local computer. This
	// name is limited to MAX_COMPUTERNAME_LENGTH + 1 characters and may be a truncated version of the DNS host name. For
	// example, if the DNS host name is "corporate-mail-server", the NetBIOS name would be "corporate-mail-".
	ComputerNameNetBIOS Value = 0x00000000
	// ComputerNamePhysicalDnsDomain: The name of the DNS domain assigned to the local computer. On a cluster, this is the
	// DNS domain of the local node on the cluster.
	ComputerNamePhysicalDnsDomain Value = 0x00000006
	// ComputerNamePhysicalDnsFullyQualified: The fully qualified DNS name that uniquely identifies the computer. On a
	// cluster, this is the fully qualified DNS name of the local node on the cluster. The fully qualified DNS name is a
	// combination of the DNS host name and the DNS domain name, using the form HostName . DomainName .
	ComputerNamePhysicalDnsFullyQualified Value = 0x00000007
	// ComputerNamePhysicalDnsHostname: The DNS host name of the local computer. On a cluster, this is the DNS host name of
	// the local node on the cluster.
	ComputerNamePhysicalDnsHostname Value = 0x00000005
	// ComputerNamePhysicalNetBIOS: The NetBIOS name of the local computer. On a cluster, this is the NetBIOS name of the
	// local node on the cluster.
	ComputerNamePhysicalNetBIOS                  Value = 0x00000004
	CpuSetInformation                            Value = 0x00000000
	DEPPolicyAlwaysOff                           Value = 0x00000000
	DEPPolicyAlwaysOn                            Value = 0x00000001
	DEPPolicyOptIn                               Value = 0x00000002
	DEPPolicyOptOut                              Value = 0x00000003
	DEPTotalPolicyCount                          Value = 0x00000004
	DEVICEFAMILYDEVICEFORM_ALLINONE              Value = 0x00000007
	DEVICEFAMILYDEVICEFORM_BANKING               Value = 0x0000000E
	DEVICEFAMILYDEVICEFORM_BUILDING_AUTOMATION   Value = 0x0000000F
	DEVICEFAMILYDEVICEFORM_CONVERTIBLE           Value = 0x00000005
	DEVICEFAMILYDEVICEFORM_DESKTOP               Value = 0x00000003
	DEVICEFAMILYDEVICEFORM_DETACHABLE            Value = 0x00000006
	DEVICEFAMILYDEVICEFORM_DIGITAL_SIGNAGE       Value = 0x00000010
	DEVICEFAMILYDEVICEFORM_GAMING                Value = 0x00000011
	DEVICEFAMILYDEVICEFORM_GAMING_CONSOLE        Value = 0x0000002F
	DEVICEFAMILYDEVICEFORM_GAMING_HANDHELD       Value = 0x0000002E
	DEVICEFAMILYDEVICEFORM_HMD                   Value = 0x0000000B
	DEVICEFAMILYDEVICEFORM_HOME_AUTOMATION       Value = 0x00000012
	DEVICEFAMILYDEVICEFORM_INDUSTRIAL_AUTOMATION Value = 0x00000013
	DEVICEFAMILYDEVICEFORM_INDUSTRY_HANDHELD     Value = 0x0000000C
	DEVICEFAMILYDEVICEFORM_INDUSTRY_OTHER        Value = 0x0000001D
	DEVICEFAMILYDEVICEFORM_INDUSTRY_TABLET       Value = 0x0000000D
	DEVICEFAMILYDEVICEFORM_KIOSK                 Value = 0x00000014
	DEVICEFAMILYDEVICEFORM_LARGESCREEN           Value = 0x0000000A
	DEVICEFAMILYDEVICEFORM_MAKER_BOARD           Value = 0x00000015
	DEVICEFAMILYDEVICEFORM_MAX                   Value = 0x0000002F
	DEVICEFAMILYDEVICEFORM_MEDICAL               Value = 0x00000016
	DEVICEFAMILYDEVICEFORM_NETWORKING            Value = 0x00000017
	DEVICEFAMILYDEVICEFORM_NOTEBOOK              Value = 0x00000004
	DEVICEFAMILYDEVICEFORM_PHONE                 Value = 0x00000001
	DEVICEFAMILYDEVICEFORM_POINT_OF_SERVICE      Value = 0x00000018
	DEVICEFAMILYDEVICEFORM_PRINTING              Value = 0x00000019
	DEVICEFAMILYDEVICEFORM_PUCK                  Value = 0x00000009
	DEVICEFAMILYDEVICEFORM_STICKPC               Value = 0x00000008
	DEVICEFAMILYDEVICEFORM_TABLET                Value = 0x00000002
	DEVICEFAMILYDEVICEFORM_THIN_CLIENT           Value = 0x0000001A
	DEVICEFAMILYDEVICEFORM_TOY                   Value = 0x0000001B
	DEVICEFAMILYDEVICEFORM_UNKNOWN               Value = 0x00000000
	DEVICEFAMILYDEVICEFORM_VENDING               Value = 0x0000001C
	DEVICEFAMILYDEVICEFORM_XBOX_ONE              Value = 0x0000001E
	DEVICEFAMILYDEVICEFORM_XBOX_ONE_S            Value = 0x0000001F
	DEVICEFAMILYDEVICEFORM_XBOX_ONE_X            Value = 0x00000020
	DEVICEFAMILYDEVICEFORM_XBOX_ONE_X_DEVKIT     Value = 0x00000021
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_01      Value = 0x00000025
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_02      Value = 0x00000026
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_03      Value = 0x00000027
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_04      Value = 0x00000028
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_05      Value = 0x00000029
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_06      Value = 0x0000002A
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_07      Value = 0x0000002B
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_08      Value = 0x0000002C
	DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_09      Value = 0x0000002D
	DEVICEFAMILYDEVICEFORM_XBOX_SERIES_S         Value = 0x00000024
	DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X         Value = 0x00000022
	DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X_DEVKIT  Value = 0x00000023
	DEVICEFAMILYINFOENUM_7067329                 Value = 0x0000000F
	DEVICEFAMILYINFOENUM_8828080                 Value = 0x0000000E
	DEVICEFAMILYINFOENUM_DESKTOP                 Value = 0x00000003
	DEVICEFAMILYINFOENUM_HOLOGRAPHIC             Value = 0x0000000A
	DEVICEFAMILYINFOENUM_IOT                     Value = 0x00000007
	DEVICEFAMILYINFOENUM_IOT_HEADLESS            Value = 0x00000008
	DEVICEFAMILYINFOENUM_MAX                     Value = 0x00000011
	DEVICEFAMILYINFOENUM_MOBILE                  Value = 0x00000004
	DEVICEFAMILYINFOENUM_SERVER                  Value = 0x00000009
	DEVICEFAMILYINFOENUM_SERVER_NANO             Value = 0x0000000D
	DEVICEFAMILYINFOENUM_TEAM                    Value = 0x00000006
	DEVICEFAMILYINFOENUM_UAP                     Value = 0x00000000
	DEVICEFAMILYINFOENUM_WINDOWS_8X              Value = 0x00000001
	DEVICEFAMILYINFOENUM_WINDOWS_CORE            Value = 0x00000010
	DEVICEFAMILYINFOENUM_WINDOWS_CORE_HEADLESS   Value = 0x00000011
	DEVICEFAMILYINFOENUM_WINDOWS_PHONE_8X        Value = 0x00000002
	DEVICEFAMILYINFOENUM_XBOX                    Value = 0x00000005
	DEVICEFAMILYINFOENUM_XBOXERA                 Value = 0x0000000C
	DEVICEFAMILYINFOENUM_XBOXSRA                 Value = 0x0000000B
	DeveloperDriveDisabledByGroupPolicy          Value = 0x00000003
	DeveloperDriveDisabledBySystemPolicy         Value = 0x00000002
	DeveloperDriveEnabled                        Value = 0x00000001
	DeveloperDriveEnablementStateError           Value = 0x00000000
	FIRM                                         Value = 0x4649524D
	// FirmwareTypeBios: The computer booted in legacy BIOS mode.
	FirmwareTypeBios Value = 0x00000001
	// FirmwareTypeMax: Not implemented.
	FirmwareTypeMax Value = 0x00000003
	// FirmwareTypeUefi: The computer booted in UEFI mode.
	FirmwareTypeUefi Value = 0x00000002
	// FirmwareTypeUnknown: The firmware type is unknown.
	FirmwareTypeUnknown                     Value = 0x00000000
	GlobalDataIdConsoleSharedDataFlags      Value = 0x0000000E
	GlobalDataIdCyclesPerYield              Value = 0x0000000B
	GlobalDataIdImageNumberHigh             Value = 0x00000005
	GlobalDataIdImageNumberLow              Value = 0x00000004
	GlobalDataIdInterruptTime               Value = 0x00000002
	GlobalDataIdKdDebuggerEnabled           Value = 0x0000000A
	GlobalDataIdLastSystemRITEventTickCount Value = 0x0000000D
	GlobalDataIdNtMajorVersion              Value = 0x00000007
	GlobalDataIdNtMinorVersion              Value = 0x00000008
	GlobalDataIdNtSystemRootDrive           Value = 0x0000000F
	GlobalDataIdQpcBias                     Value = 0x00000012
	GlobalDataIdQpcBypassEnabled            Value = 0x00000010
	GlobalDataIdQpcData                     Value = 0x00000011
	GlobalDataIdRngSeedVersion              Value = 0x00000001
	GlobalDataIdSafeBootMode                Value = 0x0000000C
	GlobalDataIdSystemExpirationDate        Value = 0x00000009
	GlobalDataIdTimeZoneBias                Value = 0x00000003
	GlobalDataIdTimeZoneId                  Value = 0x00000006
	GlobalDataIdUnknown                     Value = 0x00000000
	IMAGE_FILE_MACHINE_ALPHA                Value = 0x00000184
	IMAGE_FILE_MACHINE_ALPHA64              Value = 0x00000284
	IMAGE_FILE_MACHINE_AM33                 Value = 0x000001D3
	// IMAGE_FILE_MACHINE_AMD64: Documentation varies per use. Refer to each: IMAGE_DEBUG_INFORMATION , IMAGE_FILE_HEADER .
	IMAGE_FILE_MACHINE_AMD64 Value = 0x00008664
	IMAGE_FILE_MACHINE_ARM   Value = 0x000001C0
	IMAGE_FILE_MACHINE_ARM64 Value = 0x0000AA64
	IMAGE_FILE_MACHINE_ARMNT Value = 0x000001C4
	IMAGE_FILE_MACHINE_AXP64 Value = 0x00000284
	IMAGE_FILE_MACHINE_CEE   Value = 0x0000C0EE
	IMAGE_FILE_MACHINE_CEF   Value = 0x00000CEF
	IMAGE_FILE_MACHINE_EBC   Value = 0x00000EBC
	// IMAGE_FILE_MACHINE_I386: Documentation varies per use. Refer to each: IMAGE_DEBUG_INFORMATION , IMAGE_FILE_HEADER .
	IMAGE_FILE_MACHINE_I386 Value = 0x0000014C
	// IMAGE_FILE_MACHINE_IA64: Intel Itanium
	IMAGE_FILE_MACHINE_IA64        Value = 0x00000200
	IMAGE_FILE_MACHINE_M32R        Value = 0x00009041
	IMAGE_FILE_MACHINE_MIPS16      Value = 0x00000266
	IMAGE_FILE_MACHINE_MIPSFPU     Value = 0x00000366
	IMAGE_FILE_MACHINE_MIPSFPU16   Value = 0x00000466
	IMAGE_FILE_MACHINE_POWERPC     Value = 0x000001F0
	IMAGE_FILE_MACHINE_POWERPCFP   Value = 0x000001F1
	IMAGE_FILE_MACHINE_R10000      Value = 0x00000168
	IMAGE_FILE_MACHINE_R3000       Value = 0x00000162
	IMAGE_FILE_MACHINE_R4000       Value = 0x00000166
	IMAGE_FILE_MACHINE_SH3         Value = 0x000001A2
	IMAGE_FILE_MACHINE_SH3DSP      Value = 0x000001A3
	IMAGE_FILE_MACHINE_SH3E        Value = 0x000001A4
	IMAGE_FILE_MACHINE_SH4         Value = 0x000001A6
	IMAGE_FILE_MACHINE_SH5         Value = 0x000001A8
	IMAGE_FILE_MACHINE_TARGET_HOST Value = 0x00000001
	IMAGE_FILE_MACHINE_THUMB       Value = 0x000001C2
	IMAGE_FILE_MACHINE_TRICORE     Value = 0x00000520
	IMAGE_FILE_MACHINE_UNKNOWN     Value = 0x00000000
	IMAGE_FILE_MACHINE_WCEMIPSV2   Value = 0x00000169
	OS_DEPLOYMENT_COMPACT          Value = 0x00000002
	OS_DEPLOYMENT_STANDARD         Value = 0x00000001
	PROCESSOR_ARCHITECTURE_ALPHA   Value = 0x00000002
	PROCESSOR_ARCHITECTURE_ALPHA64 Value = 0x00000007
	// PROCESSOR_ARCHITECTURE_AMD64: Documentation varies per use. Refer to each: MINIDUMP_SYSTEM_INFO , SYSTEM_INFO ,
	// WdsCliGetImageArchitecture , WdsCliInitializeLog .
	PROCESSOR_ARCHITECTURE_AMD64 Value = 0x00000009
	// PROCESSOR_ARCHITECTURE_ARM: ARM
	PROCESSOR_ARCHITECTURE_ARM            Value = 0x00000005
	PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64 Value = 0x0000000D
	// PROCESSOR_ARCHITECTURE_ARM64: ARM64
	PROCESSOR_ARCHITECTURE_ARM64         Value = 0x0000000C
	PROCESSOR_ARCHITECTURE_IA32_ON_ARM64 Value = 0x0000000E
	PROCESSOR_ARCHITECTURE_IA32_ON_WIN64 Value = 0x0000000A
	// PROCESSOR_ARCHITECTURE_IA64: Documentation varies per use. Refer to each: MINIDUMP_SYSTEM_INFO , SYSTEM_INFO ,
	// WdsCliGetImageArchitecture , WdsCliInitializeLog .
	PROCESSOR_ARCHITECTURE_IA64 Value = 0x00000006
	// PROCESSOR_ARCHITECTURE_INTEL: Documentation varies per use. Refer to each: MINIDUMP_SYSTEM_INFO , SYSTEM_INFO ,
	// WdsCliGetImageArchitecture , WdsCliInitializeLog .
	PROCESSOR_ARCHITECTURE_INTEL   Value = 0x00000000
	PROCESSOR_ARCHITECTURE_MIPS    Value = 0x00000001
	PROCESSOR_ARCHITECTURE_MSIL    Value = 0x00000008
	PROCESSOR_ARCHITECTURE_NEUTRAL Value = 0x0000000B
	PROCESSOR_ARCHITECTURE_PPC     Value = 0x00000003
	PROCESSOR_ARCHITECTURE_SHX     Value = 0x00000004
	// PROCESSOR_ARCHITECTURE_UNKNOWN: Documentation varies per use. Refer to each: MINIDUMP_SYSTEM_INFO , SYSTEM_INFO .
	PROCESSOR_ARCHITECTURE_UNKNOWN    Value = 0x0000FFFF
	PRODUCT_ARM64_SERVER              Value = 0x00000078
	PRODUCT_AZURESTACKHCI_SERVER_CORE Value = 0x00000196
	PRODUCT_AZURE_NANO_SERVER         Value = 0x000000A9
	PRODUCT_AZURE_SERVER_AGENTBRIDGE  Value = 0x000000D0
	PRODUCT_AZURE_SERVER_CLOUDHOST    Value = 0x000000C7
	PRODUCT_AZURE_SERVER_CLOUDMOS     Value = 0x000000C8
	PRODUCT_AZURE_SERVER_CORE         Value = 0x000000A8
	PRODUCT_AZURE_SERVER_NANOHOST     Value = 0x000000D1
	// PRODUCT_BUSINESS: Business
	PRODUCT_BUSINESS Value = 0x00000006
	// PRODUCT_BUSINESS_N: Business N
	PRODUCT_BUSINESS_N                       Value = 0x00000010
	PRODUCT_CLOUD                            Value = 0x000000B2
	PRODUCT_CLOUDE                           Value = 0x000000B7
	PRODUCT_CLOUDEDITION                     Value = 0x000000CB
	PRODUCT_CLOUDEDITIONN                    Value = 0x000000CA
	PRODUCT_CLOUDEN                          Value = 0x000000BA
	PRODUCT_CLOUDN                           Value = 0x000000B3
	PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER Value = 0x0000007C
	PRODUCT_CLOUD_STORAGE_SERVER             Value = 0x0000006E
	// PRODUCT_CLUSTER_SERVER: HPC Edition
	PRODUCT_CLUSTER_SERVER Value = 0x00000012
	// PRODUCT_CLUSTER_SERVER_V: Server Hyper Core V
	PRODUCT_CLUSTER_SERVER_V Value = 0x00000040
	PRODUCT_CONNECTED_CAR    Value = 0x00000075
	// PRODUCT_CORE: Windows 10 Home
	PRODUCT_CORE                           Value = 0x00000065
	PRODUCT_CORE_ARM                       Value = 0x00000061
	PRODUCT_CORE_CONNECTED                 Value = 0x0000006F
	PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC Value = 0x00000074
	PRODUCT_CORE_CONNECTED_N               Value = 0x00000071
	PRODUCT_CORE_CONNECTED_SINGLELANGUAGE  Value = 0x00000073
	// PRODUCT_CORE_COUNTRYSPECIFIC: Windows 10 Home China
	PRODUCT_CORE_COUNTRYSPECIFIC Value = 0x00000063
	// PRODUCT_CORE_N: Windows 10 Home N
	PRODUCT_CORE_N Value = 0x00000062
	// PRODUCT_CORE_SINGLELANGUAGE: Windows 10 Home Single Language
	PRODUCT_CORE_SINGLELANGUAGE Value = 0x00000064
	// PRODUCT_DATACENTER_A_SERVER_CORE: Server Datacenter, Semi-Annual Channel (core installation)
	PRODUCT_DATACENTER_A_SERVER_CORE Value = 0x00000091
	// PRODUCT_DATACENTER_EVALUATION_SERVER: Server Datacenter (evaluation installation)
	PRODUCT_DATACENTER_EVALUATION_SERVER      Value = 0x00000050
	PRODUCT_DATACENTER_EVALUATION_SERVER_CORE Value = 0x0000009F
	PRODUCT_DATACENTER_NANO_SERVER            Value = 0x0000008F
	// PRODUCT_DATACENTER_SERVER: Server Datacenter (full installation. For Server Core installations of Windows Server
	// 2012 and later, use the method, Determining whether Server Core is running .)
	PRODUCT_DATACENTER_SERVER               Value = 0x00000008
	PRODUCT_DATACENTER_SERVER_AZURE_EDITION Value = 0x00000197
	// PRODUCT_DATACENTER_SERVER_CORE: Server Datacenter (core installation, Windows Server 2008 R2 and earlier)
	PRODUCT_DATACENTER_SERVER_CORE               Value = 0x0000000C
	PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION Value = 0x00000198
	// PRODUCT_DATACENTER_SERVER_CORE_V: Server Datacenter without Hyper-V (core installation)
	PRODUCT_DATACENTER_SERVER_CORE_V Value = 0x00000027
	// PRODUCT_DATACENTER_SERVER_V: Server Datacenter without Hyper-V (full installation)
	PRODUCT_DATACENTER_SERVER_V                     Value = 0x00000025
	PRODUCT_DATACENTER_WS_SERVER_CORE               Value = 0x00000093
	PRODUCT_DATACENTER_WS_SERVER_CORE_AZURE_EDITION Value = 0x00000199
	// PRODUCT_EDUCATION: Windows 10 Education
	PRODUCT_EDUCATION Value = 0x00000079
	// PRODUCT_EDUCATION_N: Windows 10 Education N
	PRODUCT_EDUCATION_N              Value = 0x0000007A
	PRODUCT_EMBEDDED                 Value = 0x00000041
	PRODUCT_EMBEDDED_A               Value = 0x00000058
	PRODUCT_EMBEDDED_AUTOMOTIVE      Value = 0x00000055
	PRODUCT_EMBEDDED_E               Value = 0x0000005A
	PRODUCT_EMBEDDED_EVAL            Value = 0x0000006B
	PRODUCT_EMBEDDED_E_EVAL          Value = 0x0000006C
	PRODUCT_EMBEDDED_INDUSTRY        Value = 0x00000059
	PRODUCT_EMBEDDED_INDUSTRY_A      Value = 0x00000056
	PRODUCT_EMBEDDED_INDUSTRY_A_E    Value = 0x0000005C
	PRODUCT_EMBEDDED_INDUSTRY_E      Value = 0x0000005B
	PRODUCT_EMBEDDED_INDUSTRY_EVAL   Value = 0x00000069
	PRODUCT_EMBEDDED_INDUSTRY_E_EVAL Value = 0x0000006A
	// PRODUCT_ENTERPRISE: Windows 10 Enterprise
	PRODUCT_ENTERPRISE   Value = 0x00000004
	PRODUCT_ENTERPRISEG  Value = 0x000000AB
	PRODUCT_ENTERPRISEGN Value = 0x000000AC
	// PRODUCT_ENTERPRISE_E: Windows 10 Enterprise E
	PRODUCT_ENTERPRISE_E Value = 0x00000046
	// PRODUCT_ENTERPRISE_EVALUATION: Windows 10 Enterprise Evaluation
	PRODUCT_ENTERPRISE_EVALUATION Value = 0x00000048
	// PRODUCT_ENTERPRISE_N: Windows 10 Enterprise N
	PRODUCT_ENTERPRISE_N Value = 0x0000001B
	// PRODUCT_ENTERPRISE_N_EVALUATION: Windows 10 Enterprise N Evaluation
	PRODUCT_ENTERPRISE_N_EVALUATION Value = 0x00000054
	// PRODUCT_ENTERPRISE_S: Windows 10 Enterprise 2015 LTSB
	PRODUCT_ENTERPRISE_S Value = 0x0000007D
	// PRODUCT_ENTERPRISE_SERVER: Server Enterprise (full installation)
	PRODUCT_ENTERPRISE_SERVER Value = 0x0000000A
	// PRODUCT_ENTERPRISE_SERVER_CORE: Server Enterprise (core installation)
	PRODUCT_ENTERPRISE_SERVER_CORE Value = 0x0000000E
	// PRODUCT_ENTERPRISE_SERVER_CORE_V: Server Enterprise without Hyper-V (core installation)
	PRODUCT_ENTERPRISE_SERVER_CORE_V Value = 0x00000029
	// PRODUCT_ENTERPRISE_SERVER_IA64: Server Enterprise for Itanium-based Systems
	PRODUCT_ENTERPRISE_SERVER_IA64 Value = 0x0000000F
	// PRODUCT_ENTERPRISE_SERVER_V: Server Enterprise without Hyper-V (full installation)
	PRODUCT_ENTERPRISE_SERVER_V       Value = 0x00000026
	PRODUCT_ENTERPRISE_SUBSCRIPTION   Value = 0x0000008C
	PRODUCT_ENTERPRISE_SUBSCRIPTION_N Value = 0x0000008D
	// PRODUCT_ENTERPRISE_S_EVALUATION: Windows 10 Enterprise 2015 LTSB Evaluation
	PRODUCT_ENTERPRISE_S_EVALUATION Value = 0x00000081
	// PRODUCT_ENTERPRISE_S_N: Windows 10 Enterprise 2015 LTSB N
	PRODUCT_ENTERPRISE_S_N Value = 0x0000007E
	// PRODUCT_ENTERPRISE_S_N_EVALUATION: Windows 10 Enterprise 2015 LTSB N Evaluation
	PRODUCT_ENTERPRISE_S_N_EVALUATION Value = 0x00000082
	// PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL: Windows Essential Server Solution Additional
	PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL Value = 0x0000003C
	// PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC: Windows Essential Server Solution Additional SVC
	PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC Value = 0x0000003E
	// PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT: Windows Essential Server Solution Management
	PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT Value = 0x0000003B
	// PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC: Windows Essential Server Solution Management SVC
	PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC Value = 0x0000003D
	PRODUCT_HOLOGRAPHIC                      Value = 0x00000087
	PRODUCT_HOLOGRAPHIC_BUSINESS             Value = 0x00000088
	// PRODUCT_HOME_BASIC: Home Basic
	PRODUCT_HOME_BASIC Value = 0x00000002
	// PRODUCT_HOME_BASIC_E: Not supported
	PRODUCT_HOME_BASIC_E Value = 0x00000043
	// PRODUCT_HOME_BASIC_N: Home Basic N
	PRODUCT_HOME_BASIC_N Value = 0x00000005
	// PRODUCT_HOME_PREMIUM: Home Premium
	PRODUCT_HOME_PREMIUM Value = 0x00000003
	// PRODUCT_HOME_PREMIUM_E: Not supported
	PRODUCT_HOME_PREMIUM_E Value = 0x00000044
	// PRODUCT_HOME_PREMIUM_N: Home Premium N
	PRODUCT_HOME_PREMIUM_N Value = 0x0000001A
	// PRODUCT_HOME_PREMIUM_SERVER: Windows Home Server 2011
	PRODUCT_HOME_PREMIUM_SERVER Value = 0x00000022
	// PRODUCT_HOME_SERVER: Windows Storage Server 2008 R2 Essentials
	PRODUCT_HOME_SERVER Value = 0x00000013
	PRODUCT_HUBOS       Value = 0x000000B4
	// PRODUCT_HYPERV: Microsoft Hyper-V Server
	PRODUCT_HYPERV            Value = 0x0000002A
	PRODUCT_INDUSTRY_HANDHELD Value = 0x00000076
	PRODUCT_IOTEDGEOS         Value = 0x000000BB
	// PRODUCT_IOTENTERPRISE: Windows IoT Enterprise
	PRODUCT_IOTENTERPRISE      Value = 0x000000BC
	PRODUCT_IOTENTERPRISEK     Value = 0x000000CE
	PRODUCT_IOTENTERPRISES     Value = 0x000000BF
	PRODUCT_IOTENTERPRISESEVAL Value = 0x000000CF
	PRODUCT_IOTENTERPRISESK    Value = 0x000000CD
	PRODUCT_IOTOS              Value = 0x000000B9
	// PRODUCT_IOTUAP: Windows 10 IoT Core
	PRODUCT_IOTUAP Value = 0x0000007B
	PRODUCT_LITE   Value = 0x000000BD
	// PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT: Windows Essential Business Server Management Server
	PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT Value = 0x0000001E
	// PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING: Windows Essential Business Server Messaging Server
	PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING Value = 0x00000020
	// PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY: Windows Essential Business Server Security Server
	PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY Value = 0x0000001F
	// PRODUCT_MULTIPOINT_PREMIUM_SERVER: Windows MultiPoint Server Premium (full installation)
	PRODUCT_MULTIPOINT_PREMIUM_SERVER Value = 0x0000004D
	// PRODUCT_MULTIPOINT_STANDARD_SERVER: Windows MultiPoint Server Standard (full installation)
	PRODUCT_MULTIPOINT_STANDARD_SERVER Value = 0x0000004C
	PRODUCT_NANO_SERVER                Value = 0x0000006D
	PRODUCT_ONECOREUPDATEOS            Value = 0x000000B6
	// PRODUCT_PPI_PRO: Windows 10 Team
	PRODUCT_PPI_PRO Value = 0x00000077
	// PRODUCT_PROFESSIONAL: Windows 10 Pro
	PRODUCT_PROFESSIONAL Value = 0x00000030
	// PRODUCT_PROFESSIONAL_E: Not supported
	PRODUCT_PROFESSIONAL_E        Value = 0x00000045
	PRODUCT_PROFESSIONAL_EMBEDDED Value = 0x0000003A
	// PRODUCT_PROFESSIONAL_N: Windows 10 Pro N
	PRODUCT_PROFESSIONAL_N         Value = 0x00000031
	PRODUCT_PROFESSIONAL_S         Value = 0x0000007F
	PRODUCT_PROFESSIONAL_STUDENT   Value = 0x00000070
	PRODUCT_PROFESSIONAL_STUDENT_N Value = 0x00000072
	PRODUCT_PROFESSIONAL_S_N       Value = 0x00000080
	// PRODUCT_PROFESSIONAL_WMC: Professional with Media Center
	PRODUCT_PROFESSIONAL_WMC Value = 0x00000067
	PRODUCT_PRO_CHINA        Value = 0x0000008B
	// PRODUCT_PRO_FOR_EDUCATION: Windows 10 Pro Education
	PRODUCT_PRO_FOR_EDUCATION   Value = 0x000000A4
	PRODUCT_PRO_FOR_EDUCATION_N Value = 0x000000A5
	PRODUCT_PRO_SINGLE_LANGUAGE Value = 0x0000008A
	// PRODUCT_PRO_WORKSTATION: Windows 10 Pro for Workstations
	PRODUCT_PRO_WORKSTATION Value = 0x000000A1
	// PRODUCT_PRO_WORKSTATION_N: Windows 10 Pro for Workstations N
	PRODUCT_PRO_WORKSTATION_N Value = 0x000000A2
	// PRODUCT_SB_SOLUTION_SERVER: Windows Small Business Server 2011 Essentials
	PRODUCT_SB_SOLUTION_SERVER Value = 0x00000032
	// PRODUCT_SB_SOLUTION_SERVER_EM: Server For SB Solutions EM
	PRODUCT_SB_SOLUTION_SERVER_EM Value = 0x00000036
	// PRODUCT_SERVERRDSH: Windows 10 Enterprise for Virtual Desktops
	PRODUCT_SERVERRDSH Value = 0x000000AF
	// PRODUCT_SERVER_FOR_SB_SOLUTIONS: Server For SB Solutions
	PRODUCT_SERVER_FOR_SB_SOLUTIONS Value = 0x00000033
	// PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM: Server For SB Solutions EM
	PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM Value = 0x00000037
	// PRODUCT_SERVER_FOR_SMALLBUSINESS: Windows Server 2008 for Windows Essential Server Solutions
	PRODUCT_SERVER_FOR_SMALLBUSINESS Value = 0x00000018
	// PRODUCT_SERVER_FOR_SMALLBUSINESS_V: Windows Server 2008 without Hyper-V for Windows Essential Server Solutions
	PRODUCT_SERVER_FOR_SMALLBUSINESS_V Value = 0x00000023
	// PRODUCT_SERVER_FOUNDATION: Server Foundation
	PRODUCT_SERVER_FOUNDATION Value = 0x00000021
	// PRODUCT_SMALLBUSINESS_SERVER: Windows Small Business Server
	PRODUCT_SMALLBUSINESS_SERVER Value = 0x00000009
	// PRODUCT_SMALLBUSINESS_SERVER_PREMIUM: Small Business Server Premium
	PRODUCT_SMALLBUSINESS_SERVER_PREMIUM Value = 0x00000019
	// PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE: Small Business Server Premium (core installation)
	PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE Value = 0x0000003F
	// PRODUCT_SOLUTION_EMBEDDEDSERVER: Windows MultiPoint Server
	PRODUCT_SOLUTION_EMBEDDEDSERVER      Value = 0x00000038
	PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE Value = 0x00000039
	// PRODUCT_STANDARD_A_SERVER_CORE: Server Standard, Semi-Annual Channel (core installation)
	PRODUCT_STANDARD_A_SERVER_CORE Value = 0x00000092
	// PRODUCT_STANDARD_EVALUATION_SERVER: Server Standard (evaluation installation)
	PRODUCT_STANDARD_EVALUATION_SERVER      Value = 0x0000004F
	PRODUCT_STANDARD_EVALUATION_SERVER_CORE Value = 0x000000A0
	PRODUCT_STANDARD_NANO_SERVER            Value = 0x00000090
	// PRODUCT_STANDARD_SERVER: Server Standard (full installation. For Server Core installations of Windows Server 2012
	// and later, use the method, Determining whether Server Core is running .)
	PRODUCT_STANDARD_SERVER      Value = 0x00000007
	PRODUCT_STANDARD_SERVER_CORE Value = 0x0000000D
	// PRODUCT_STANDARD_SERVER_CORE_V: Server Standard without Hyper-V (core installation)
	PRODUCT_STANDARD_SERVER_CORE_V Value = 0x00000028
	// PRODUCT_STANDARD_SERVER_SOLUTIONS: Server Solutions Premium
	PRODUCT_STANDARD_SERVER_SOLUTIONS Value = 0x00000034
	// PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE: Server Solutions Premium (core installation)
	PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE Value = 0x00000035
	// PRODUCT_STANDARD_SERVER_V: Server Standard without Hyper-V
	PRODUCT_STANDARD_SERVER_V       Value = 0x00000024
	PRODUCT_STANDARD_WS_SERVER_CORE Value = 0x00000094
	// PRODUCT_STARTER: Starter
	PRODUCT_STARTER Value = 0x0000000B
	// PRODUCT_STARTER_E: Not supported
	PRODUCT_STARTER_E Value = 0x00000042
	// PRODUCT_STARTER_N: Starter N
	PRODUCT_STARTER_N Value = 0x0000002F
	// PRODUCT_STORAGE_ENTERPRISE_SERVER: Storage Server Enterprise
	PRODUCT_STORAGE_ENTERPRISE_SERVER Value = 0x00000017
	// PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE: Storage Server Enterprise (core installation)
	PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE Value = 0x0000002E
	// PRODUCT_STORAGE_EXPRESS_SERVER: Storage Server Express
	PRODUCT_STORAGE_EXPRESS_SERVER Value = 0x00000014
	// PRODUCT_STORAGE_EXPRESS_SERVER_CORE: Storage Server Express (core installation)
	PRODUCT_STORAGE_EXPRESS_SERVER_CORE Value = 0x0000002B
	// PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER: Storage Server Standard (evaluation installation)
	PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER Value = 0x00000060
	// PRODUCT_STORAGE_STANDARD_SERVER: Storage Server Standard
	PRODUCT_STORAGE_STANDARD_SERVER Value = 0x00000015
	// PRODUCT_STORAGE_STANDARD_SERVER_CORE: Storage Server Standard (core installation)
	PRODUCT_STORAGE_STANDARD_SERVER_CORE Value = 0x0000002C
	// PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER: Storage Server Workgroup (evaluation installation)
	PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER Value = 0x0000005F
	// PRODUCT_STORAGE_WORKGROUP_SERVER: Storage Server Workgroup
	PRODUCT_STORAGE_WORKGROUP_SERVER Value = 0x00000016
	// PRODUCT_STORAGE_WORKGROUP_SERVER_CORE: Storage Server Workgroup (core installation)
	PRODUCT_STORAGE_WORKGROUP_SERVER_CORE Value = 0x0000002D
	PRODUCT_THINPC                        Value = 0x00000057
	// PRODUCT_ULTIMATE: Ultimate
	PRODUCT_ULTIMATE Value = 0x00000001
	// PRODUCT_ULTIMATE_E: Not supported
	PRODUCT_ULTIMATE_E Value = 0x00000047
	// PRODUCT_ULTIMATE_N: Ultimate N
	PRODUCT_ULTIMATE_N Value = 0x0000001C
	// PRODUCT_UNDEFINED: An unknown product
	PRODUCT_UNDEFINED  Value = 0x00000000
	PRODUCT_UNLICENSED Value = 0xABCDABCD
	PRODUCT_UTILITY_VM Value = 0x00000095
	PRODUCT_VALIDATION Value = 0x000000CC
	// PRODUCT_WEB_SERVER: Web Server (full installation)
	PRODUCT_WEB_SERVER Value = 0x00000011
	// PRODUCT_WEB_SERVER_CORE: Web Server (core installation)
	PRODUCT_WEB_SERVER_CORE     Value = 0x0000001D
	PRODUCT_WNC                 Value = 0x000000D2
	PRODUCT_XBOX_DURANGOHOSTOS  Value = 0x000000C4
	PRODUCT_XBOX_ERAOS          Value = 0x000000C3
	PRODUCT_XBOX_GAMEOS         Value = 0x000000C2
	PRODUCT_XBOX_KEYSTONE       Value = 0x000000C6
	PRODUCT_XBOX_SCARLETTHOSTOS Value = 0x000000C5
	PRODUCT_XBOX_SYSTEMOS       Value = 0x000000C0
	RSMB                        Value = 0x52534D42
	// RelationAll: On input, retrieves information about all possible relationship types. This value is not used on
	// output. Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP Professional x64 Edition: This value
	// is not supported until Windows Server 2008 R2.
	RelationAll Value = 0x0000FFFF
	// RelationCache: The specified logical processors share a cache. Windows Server 2003: This value is not supported
	// until Windows Server 2003 with SP1 and Windows XP Professional x64 Edition.
	RelationCache Value = 0x00000002
	// RelationGroup: The specified logical processors share a single processor group . Windows Server 2008, Windows Vista,
	// Windows Server 2003 and Windows XP Professional x64 Edition: This value is not supported until Windows Server 2008
	// R2.
	RelationGroup Value = 0x00000004
	// RelationNumaNode: The specified logical processors are part of the same NUMA node.
	RelationNumaNode Value = 0x00000001
	// RelationNumaNodeEx: **Introduced in Windows Server 2022 (21H2, build 20348).** Requests that the full affinity be
	// returned. Unlike the other relation types, **RelationNumaNodeEx** is not used on input. It is simply a request for
	// **RelationNumaNode** with full group information.
	RelationNumaNodeEx Value = 0x00000006
	// RelationProcessorCore: The specified logical processors share a single processor core.
	RelationProcessorCore Value = 0x00000000
	// RelationProcessorDie: The specified logical processors share a single processor die.
	RelationProcessorDie    Value = 0x00000005
	RelationProcessorModule Value = 0x00000007
	// RelationProcessorPackage: The specified logical processors share a physical package (a single package socketed or
	// soldered onto a motherboard may contain multiple processor cores or threads, each of which is treated as a separate
	// processor by the operating system). Windows Server 2003: This value is not supported until Windows Server 2003 with
	// SP1 and Windows XP Professional x64 Edition.
	RelationProcessorPackage Value = 0x00000003
	// USER_CET_ENVIRONMENT_SGX2_ENCLAVE: The Intel Software Guard Extensions 2 (SGX2) enclave environment.
	USER_CET_ENVIRONMENT_SGX2_ENCLAVE Value = 0x00000002
	// USER_CET_ENVIRONMENT_VBS_BASIC_ENCLAVE: The virtualization-based security (VBS) basic enclave environment.
	USER_CET_ENVIRONMENT_VBS_BASIC_ENCLAVE Value = 0x00000011
	// USER_CET_ENVIRONMENT_VBS_ENCLAVE: The virtualization-based security (VBS) enclave environment.
	USER_CET_ENVIRONMENT_VBS_ENCLAVE Value = 0x00000010
	// USER_CET_ENVIRONMENT_WIN32_PROCESS: The Win32 environment.
	USER_CET_ENVIRONMENT_WIN32_PROCESS Value = 0x00000000
	// VER_BUILDNUMBER: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_BUILDNUMBER Value = 0x00000004
	// VER_MAJORVERSION: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_MAJORVERSION Value = 0x00000002
	// VER_MINORVERSION: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_MINORVERSION Value = 0x00000001
	// VER_PLATFORMID: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_PLATFORMID Value = 0x00000008
	// VER_PRODUCT_TYPE: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_PRODUCT_TYPE Value = 0x00000080
	// VER_SERVICEPACKMAJOR: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_SERVICEPACKMAJOR Value = 0x00000020
	// VER_SERVICEPACKMINOR: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_SERVICEPACKMINOR Value = 0x00000010
	// VER_SUITENAME: Documentation varies per use. Refer to each: VER_SET_CONDITION , VerifyVersionInfo ,
	// VerifyVersionInfo , VerifyVersionInfoA , VerifyVersionInfoA , VerifyVersionInfoW , VerifyVersionInfoW ,
	// VerSetConditionMask .
	VER_SUITENAME Value = 0x00000040
)

// Name returns the canonical symbolic name for value.
func Name(value Value) (string, bool) {
	switch value {
	case Value(0x00000000):
		return "CacheUnified", true
	case Value(0x00000001):
		return "CacheInstruction", true
	case Value(0x00000002):
		return "CacheData", true
	case Value(0x00000003):
		return "CacheTrace", true
	case Value(0x00000004):
		return "CacheUnknown", true
	case Value(0x00000005):
		return "ComputerNamePhysicalDnsHostname", true
	case Value(0x00000006):
		return "ComputerNamePhysicalDnsDomain", true
	case Value(0x00000007):
		return "ComputerNamePhysicalDnsFullyQualified", true
	case Value(0x00000008):
		return "ComputerNameMax", true
	case Value(0x00000009):
		return "DEVICEFAMILYDEVICEFORM_PUCK", true
	case Value(0x0000000A):
		return "DEVICEFAMILYDEVICEFORM_LARGESCREEN", true
	case Value(0x0000000B):
		return "DEVICEFAMILYDEVICEFORM_HMD", true
	case Value(0x0000000C):
		return "DEVICEFAMILYDEVICEFORM_INDUSTRY_HANDHELD", true
	case Value(0x0000000D):
		return "DEVICEFAMILYDEVICEFORM_INDUSTRY_TABLET", true
	case Value(0x0000000E):
		return "DEVICEFAMILYDEVICEFORM_BANKING", true
	case Value(0x0000000F):
		return "DEVICEFAMILYDEVICEFORM_BUILDING_AUTOMATION", true
	case Value(0x00000010):
		return "DEVICEFAMILYDEVICEFORM_DIGITAL_SIGNAGE", true
	case Value(0x00000011):
		return "DEVICEFAMILYDEVICEFORM_GAMING", true
	case Value(0x00000012):
		return "DEVICEFAMILYDEVICEFORM_HOME_AUTOMATION", true
	case Value(0x00000013):
		return "DEVICEFAMILYDEVICEFORM_INDUSTRIAL_AUTOMATION", true
	case Value(0x00000014):
		return "DEVICEFAMILYDEVICEFORM_KIOSK", true
	case Value(0x00000015):
		return "DEVICEFAMILYDEVICEFORM_MAKER_BOARD", true
	case Value(0x00000016):
		return "DEVICEFAMILYDEVICEFORM_MEDICAL", true
	case Value(0x00000017):
		return "DEVICEFAMILYDEVICEFORM_NETWORKING", true
	case Value(0x00000018):
		return "DEVICEFAMILYDEVICEFORM_POINT_OF_SERVICE", true
	case Value(0x00000019):
		return "DEVICEFAMILYDEVICEFORM_PRINTING", true
	case Value(0x0000001A):
		return "DEVICEFAMILYDEVICEFORM_THIN_CLIENT", true
	case Value(0x0000001B):
		return "DEVICEFAMILYDEVICEFORM_TOY", true
	case Value(0x0000001C):
		return "DEVICEFAMILYDEVICEFORM_VENDING", true
	case Value(0x0000001D):
		return "DEVICEFAMILYDEVICEFORM_INDUSTRY_OTHER", true
	case Value(0x0000001E):
		return "DEVICEFAMILYDEVICEFORM_XBOX_ONE", true
	case Value(0x0000001F):
		return "DEVICEFAMILYDEVICEFORM_XBOX_ONE_S", true
	case Value(0x00000020):
		return "DEVICEFAMILYDEVICEFORM_XBOX_ONE_X", true
	case Value(0x00000021):
		return "DEVICEFAMILYDEVICEFORM_XBOX_ONE_X_DEVKIT", true
	case Value(0x00000022):
		return "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X", true
	case Value(0x00000023):
		return "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X_DEVKIT", true
	case Value(0x00000024):
		return "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_S", true
	case Value(0x00000025):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_01", true
	case Value(0x00000026):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_02", true
	case Value(0x00000027):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_03", true
	case Value(0x00000028):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_04", true
	case Value(0x00000029):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_05", true
	case Value(0x0000002A):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_06", true
	case Value(0x0000002B):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_07", true
	case Value(0x0000002C):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_08", true
	case Value(0x0000002D):
		return "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_09", true
	case Value(0x0000002E):
		return "DEVICEFAMILYDEVICEFORM_GAMING_HANDHELD", true
	case Value(0x0000002F):
		return "DEVICEFAMILYDEVICEFORM_GAMING_CONSOLE", true
	case Value(0x00000030):
		return "PRODUCT_PROFESSIONAL", true
	case Value(0x00000031):
		return "PRODUCT_PROFESSIONAL_N", true
	case Value(0x00000032):
		return "PRODUCT_SB_SOLUTION_SERVER", true
	case Value(0x00000033):
		return "PRODUCT_SERVER_FOR_SB_SOLUTIONS", true
	case Value(0x00000034):
		return "PRODUCT_STANDARD_SERVER_SOLUTIONS", true
	case Value(0x00000035):
		return "PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE", true
	case Value(0x00000036):
		return "PRODUCT_SB_SOLUTION_SERVER_EM", true
	case Value(0x00000037):
		return "PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM", true
	case Value(0x00000038):
		return "PRODUCT_SOLUTION_EMBEDDEDSERVER", true
	case Value(0x00000039):
		return "PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE", true
	case Value(0x0000003A):
		return "PRODUCT_PROFESSIONAL_EMBEDDED", true
	case Value(0x0000003B):
		return "PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT", true
	case Value(0x0000003C):
		return "PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL", true
	case Value(0x0000003D):
		return "PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC", true
	case Value(0x0000003E):
		return "PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC", true
	case Value(0x0000003F):
		return "PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE", true
	case Value(0x00000040):
		return "PRODUCT_CLUSTER_SERVER_V", true
	case Value(0x00000041):
		return "PRODUCT_EMBEDDED", true
	case Value(0x00000042):
		return "PRODUCT_STARTER_E", true
	case Value(0x00000043):
		return "PRODUCT_HOME_BASIC_E", true
	case Value(0x00000044):
		return "PRODUCT_HOME_PREMIUM_E", true
	case Value(0x00000045):
		return "PRODUCT_PROFESSIONAL_E", true
	case Value(0x00000046):
		return "PRODUCT_ENTERPRISE_E", true
	case Value(0x00000047):
		return "PRODUCT_ULTIMATE_E", true
	case Value(0x00000048):
		return "PRODUCT_ENTERPRISE_EVALUATION", true
	case Value(0x0000004C):
		return "PRODUCT_MULTIPOINT_STANDARD_SERVER", true
	case Value(0x0000004D):
		return "PRODUCT_MULTIPOINT_PREMIUM_SERVER", true
	case Value(0x0000004F):
		return "PRODUCT_STANDARD_EVALUATION_SERVER", true
	case Value(0x00000050):
		return "PRODUCT_DATACENTER_EVALUATION_SERVER", true
	case Value(0x00000054):
		return "PRODUCT_ENTERPRISE_N_EVALUATION", true
	case Value(0x00000055):
		return "PRODUCT_EMBEDDED_AUTOMOTIVE", true
	case Value(0x00000056):
		return "PRODUCT_EMBEDDED_INDUSTRY_A", true
	case Value(0x00000057):
		return "PRODUCT_THINPC", true
	case Value(0x00000058):
		return "PRODUCT_EMBEDDED_A", true
	case Value(0x00000059):
		return "PRODUCT_EMBEDDED_INDUSTRY", true
	case Value(0x0000005A):
		return "PRODUCT_EMBEDDED_E", true
	case Value(0x0000005B):
		return "PRODUCT_EMBEDDED_INDUSTRY_E", true
	case Value(0x0000005C):
		return "PRODUCT_EMBEDDED_INDUSTRY_A_E", true
	case Value(0x0000005F):
		return "PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER", true
	case Value(0x00000060):
		return "PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER", true
	case Value(0x00000061):
		return "PRODUCT_CORE_ARM", true
	case Value(0x00000062):
		return "PRODUCT_CORE_N", true
	case Value(0x00000063):
		return "PRODUCT_CORE_COUNTRYSPECIFIC", true
	case Value(0x00000064):
		return "PRODUCT_CORE_SINGLELANGUAGE", true
	case Value(0x00000065):
		return "PRODUCT_CORE", true
	case Value(0x00000067):
		return "PRODUCT_PROFESSIONAL_WMC", true
	case Value(0x00000069):
		return "PRODUCT_EMBEDDED_INDUSTRY_EVAL", true
	case Value(0x0000006A):
		return "PRODUCT_EMBEDDED_INDUSTRY_E_EVAL", true
	case Value(0x0000006B):
		return "PRODUCT_EMBEDDED_EVAL", true
	case Value(0x0000006C):
		return "PRODUCT_EMBEDDED_E_EVAL", true
	case Value(0x0000006D):
		return "PRODUCT_NANO_SERVER", true
	case Value(0x0000006E):
		return "PRODUCT_CLOUD_STORAGE_SERVER", true
	case Value(0x0000006F):
		return "PRODUCT_CORE_CONNECTED", true
	case Value(0x00000070):
		return "PRODUCT_PROFESSIONAL_STUDENT", true
	case Value(0x00000071):
		return "PRODUCT_CORE_CONNECTED_N", true
	case Value(0x00000072):
		return "PRODUCT_PROFESSIONAL_STUDENT_N", true
	case Value(0x00000073):
		return "PRODUCT_CORE_CONNECTED_SINGLELANGUAGE", true
	case Value(0x00000074):
		return "PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC", true
	case Value(0x00000075):
		return "PRODUCT_CONNECTED_CAR", true
	case Value(0x00000076):
		return "PRODUCT_INDUSTRY_HANDHELD", true
	case Value(0x00000077):
		return "PRODUCT_PPI_PRO", true
	case Value(0x00000078):
		return "PRODUCT_ARM64_SERVER", true
	case Value(0x00000079):
		return "PRODUCT_EDUCATION", true
	case Value(0x0000007A):
		return "PRODUCT_EDUCATION_N", true
	case Value(0x0000007B):
		return "PRODUCT_IOTUAP", true
	case Value(0x0000007C):
		return "PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER", true
	case Value(0x0000007D):
		return "PRODUCT_ENTERPRISE_S", true
	case Value(0x0000007E):
		return "PRODUCT_ENTERPRISE_S_N", true
	case Value(0x0000007F):
		return "PRODUCT_PROFESSIONAL_S", true
	case Value(0x00000080):
		return "PRODUCT_PROFESSIONAL_S_N", true
	case Value(0x00000081):
		return "PRODUCT_ENTERPRISE_S_EVALUATION", true
	case Value(0x00000082):
		return "PRODUCT_ENTERPRISE_S_N_EVALUATION", true
	case Value(0x00000087):
		return "PRODUCT_HOLOGRAPHIC", true
	case Value(0x00000088):
		return "PRODUCT_HOLOGRAPHIC_BUSINESS", true
	case Value(0x0000008A):
		return "PRODUCT_PRO_SINGLE_LANGUAGE", true
	case Value(0x0000008B):
		return "PRODUCT_PRO_CHINA", true
	case Value(0x0000008C):
		return "PRODUCT_ENTERPRISE_SUBSCRIPTION", true
	case Value(0x0000008D):
		return "PRODUCT_ENTERPRISE_SUBSCRIPTION_N", true
	case Value(0x0000008F):
		return "PRODUCT_DATACENTER_NANO_SERVER", true
	case Value(0x00000090):
		return "PRODUCT_STANDARD_NANO_SERVER", true
	case Value(0x00000091):
		return "PRODUCT_DATACENTER_A_SERVER_CORE", true
	case Value(0x00000092):
		return "PRODUCT_STANDARD_A_SERVER_CORE", true
	case Value(0x00000093):
		return "PRODUCT_DATACENTER_WS_SERVER_CORE", true
	case Value(0x00000094):
		return "PRODUCT_STANDARD_WS_SERVER_CORE", true
	case Value(0x00000095):
		return "PRODUCT_UTILITY_VM", true
	case Value(0x0000009F):
		return "PRODUCT_DATACENTER_EVALUATION_SERVER_CORE", true
	case Value(0x000000A0):
		return "PRODUCT_STANDARD_EVALUATION_SERVER_CORE", true
	case Value(0x000000A1):
		return "PRODUCT_PRO_WORKSTATION", true
	case Value(0x000000A2):
		return "PRODUCT_PRO_WORKSTATION_N", true
	case Value(0x000000A4):
		return "PRODUCT_PRO_FOR_EDUCATION", true
	case Value(0x000000A5):
		return "PRODUCT_PRO_FOR_EDUCATION_N", true
	case Value(0x000000A8):
		return "PRODUCT_AZURE_SERVER_CORE", true
	case Value(0x000000A9):
		return "PRODUCT_AZURE_NANO_SERVER", true
	case Value(0x000000AB):
		return "PRODUCT_ENTERPRISEG", true
	case Value(0x000000AC):
		return "PRODUCT_ENTERPRISEGN", true
	case Value(0x000000AF):
		return "PRODUCT_SERVERRDSH", true
	case Value(0x000000B2):
		return "PRODUCT_CLOUD", true
	case Value(0x000000B3):
		return "PRODUCT_CLOUDN", true
	case Value(0x000000B4):
		return "PRODUCT_HUBOS", true
	case Value(0x000000B6):
		return "PRODUCT_ONECOREUPDATEOS", true
	case Value(0x000000B7):
		return "PRODUCT_CLOUDE", true
	case Value(0x000000B9):
		return "PRODUCT_IOTOS", true
	case Value(0x000000BA):
		return "PRODUCT_CLOUDEN", true
	case Value(0x000000BB):
		return "PRODUCT_IOTEDGEOS", true
	case Value(0x000000BC):
		return "PRODUCT_IOTENTERPRISE", true
	case Value(0x000000BD):
		return "PRODUCT_LITE", true
	case Value(0x000000BF):
		return "PRODUCT_IOTENTERPRISES", true
	case Value(0x000000C0):
		return "PRODUCT_XBOX_SYSTEMOS", true
	case Value(0x000000C2):
		return "PRODUCT_XBOX_GAMEOS", true
	case Value(0x000000C3):
		return "PRODUCT_XBOX_ERAOS", true
	case Value(0x000000C4):
		return "PRODUCT_XBOX_DURANGOHOSTOS", true
	case Value(0x000000C5):
		return "PRODUCT_XBOX_SCARLETTHOSTOS", true
	case Value(0x000000C6):
		return "PRODUCT_XBOX_KEYSTONE", true
	case Value(0x000000C7):
		return "PRODUCT_AZURE_SERVER_CLOUDHOST", true
	case Value(0x000000C8):
		return "PRODUCT_AZURE_SERVER_CLOUDMOS", true
	case Value(0x000000CA):
		return "PRODUCT_CLOUDEDITIONN", true
	case Value(0x000000CB):
		return "PRODUCT_CLOUDEDITION", true
	case Value(0x000000CC):
		return "PRODUCT_VALIDATION", true
	case Value(0x000000CD):
		return "PRODUCT_IOTENTERPRISESK", true
	case Value(0x000000CE):
		return "PRODUCT_IOTENTERPRISEK", true
	case Value(0x000000CF):
		return "PRODUCT_IOTENTERPRISESEVAL", true
	case Value(0x000000D0):
		return "PRODUCT_AZURE_SERVER_AGENTBRIDGE", true
	case Value(0x000000D1):
		return "PRODUCT_AZURE_SERVER_NANOHOST", true
	case Value(0x000000D2):
		return "PRODUCT_WNC", true
	case Value(0x0000014C):
		return "IMAGE_FILE_MACHINE_I386", true
	case Value(0x00000162):
		return "IMAGE_FILE_MACHINE_R3000", true
	case Value(0x00000166):
		return "IMAGE_FILE_MACHINE_R4000", true
	case Value(0x00000168):
		return "IMAGE_FILE_MACHINE_R10000", true
	case Value(0x00000169):
		return "IMAGE_FILE_MACHINE_WCEMIPSV2", true
	case Value(0x00000184):
		return "IMAGE_FILE_MACHINE_ALPHA", true
	case Value(0x00000196):
		return "PRODUCT_AZURESTACKHCI_SERVER_CORE", true
	case Value(0x00000197):
		return "PRODUCT_DATACENTER_SERVER_AZURE_EDITION", true
	case Value(0x00000198):
		return "PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION", true
	case Value(0x00000199):
		return "PRODUCT_DATACENTER_WS_SERVER_CORE_AZURE_EDITION", true
	case Value(0x000001A2):
		return "IMAGE_FILE_MACHINE_SH3", true
	case Value(0x000001A3):
		return "IMAGE_FILE_MACHINE_SH3DSP", true
	case Value(0x000001A4):
		return "IMAGE_FILE_MACHINE_SH3E", true
	case Value(0x000001A6):
		return "IMAGE_FILE_MACHINE_SH4", true
	case Value(0x000001A8):
		return "IMAGE_FILE_MACHINE_SH5", true
	case Value(0x000001C0):
		return "IMAGE_FILE_MACHINE_ARM", true
	case Value(0x000001C2):
		return "IMAGE_FILE_MACHINE_THUMB", true
	case Value(0x000001C4):
		return "IMAGE_FILE_MACHINE_ARMNT", true
	case Value(0x000001D3):
		return "IMAGE_FILE_MACHINE_AM33", true
	case Value(0x000001F0):
		return "IMAGE_FILE_MACHINE_POWERPC", true
	case Value(0x000001F1):
		return "IMAGE_FILE_MACHINE_POWERPCFP", true
	case Value(0x00000200):
		return "IMAGE_FILE_MACHINE_IA64", true
	case Value(0x00000266):
		return "IMAGE_FILE_MACHINE_MIPS16", true
	case Value(0x00000284):
		return "IMAGE_FILE_MACHINE_ALPHA64", true
	case Value(0x00000366):
		return "IMAGE_FILE_MACHINE_MIPSFPU", true
	case Value(0x00000466):
		return "IMAGE_FILE_MACHINE_MIPSFPU16", true
	case Value(0x00000520):
		return "IMAGE_FILE_MACHINE_TRICORE", true
	case Value(0x00000CEF):
		return "IMAGE_FILE_MACHINE_CEF", true
	case Value(0x00000EBC):
		return "IMAGE_FILE_MACHINE_EBC", true
	case Value(0x00008664):
		return "IMAGE_FILE_MACHINE_AMD64", true
	case Value(0x00009041):
		return "IMAGE_FILE_MACHINE_M32R", true
	case Value(0x0000AA64):
		return "IMAGE_FILE_MACHINE_ARM64", true
	case Value(0x0000C0EE):
		return "IMAGE_FILE_MACHINE_CEE", true
	case Value(0x0000FFFF):
		return "PROCESSOR_ARCHITECTURE_UNKNOWN", true
	case Value(0x41435049):
		return "ACPI", true
	case Value(0x4649524D):
		return "FIRM", true
	case Value(0x52534D42):
		return "RSMB", true
	case Value(0xABCDABCD):
		return "PRODUCT_UNLICENSED", true
	default:
		return "", false
	}
}

// Names returns every symbolic alias for value in lexical order.
func Names(value Value) []string {
	switch value {
	case Value(0x00000000):
		return []string{"CacheUnified", "ComputerNameNetBIOS", "CpuSetInformation", "DEPPolicyAlwaysOff", "DEVICEFAMILYDEVICEFORM_UNKNOWN", "DEVICEFAMILYINFOENUM_UAP", "DeveloperDriveEnablementStateError", "FirmwareTypeUnknown", "GlobalDataIdUnknown", "IMAGE_FILE_MACHINE_UNKNOWN", "PROCESSOR_ARCHITECTURE_INTEL", "PRODUCT_UNDEFINED", "RelationProcessorCore", "USER_CET_ENVIRONMENT_WIN32_PROCESS"}
	case Value(0x00000001):
		return []string{"CacheInstruction", "ComputerNameDnsHostname", "DEPPolicyAlwaysOn", "DEVICEFAMILYDEVICEFORM_PHONE", "DEVICEFAMILYINFOENUM_WINDOWS_8X", "DeveloperDriveEnabled", "FirmwareTypeBios", "GlobalDataIdRngSeedVersion", "IMAGE_FILE_MACHINE_TARGET_HOST", "OS_DEPLOYMENT_STANDARD", "PROCESSOR_ARCHITECTURE_MIPS", "PRODUCT_ULTIMATE", "RelationNumaNode", "VER_MINORVERSION"}
	case Value(0x00000002):
		return []string{"CacheData", "ComputerNameDnsDomain", "DEPPolicyOptIn", "DEVICEFAMILYDEVICEFORM_TABLET", "DEVICEFAMILYINFOENUM_WINDOWS_PHONE_8X", "DeveloperDriveDisabledBySystemPolicy", "FirmwareTypeUefi", "GlobalDataIdInterruptTime", "OS_DEPLOYMENT_COMPACT", "PROCESSOR_ARCHITECTURE_ALPHA", "PRODUCT_HOME_BASIC", "RelationCache", "USER_CET_ENVIRONMENT_SGX2_ENCLAVE", "VER_MAJORVERSION"}
	case Value(0x00000003):
		return []string{"CacheTrace", "ComputerNameDnsFullyQualified", "DEPPolicyOptOut", "DEVICEFAMILYDEVICEFORM_DESKTOP", "DEVICEFAMILYINFOENUM_DESKTOP", "DeveloperDriveDisabledByGroupPolicy", "FirmwareTypeMax", "GlobalDataIdTimeZoneBias", "PROCESSOR_ARCHITECTURE_PPC", "PRODUCT_HOME_PREMIUM", "RelationProcessorPackage"}
	case Value(0x00000004):
		return []string{"CacheUnknown", "ComputerNamePhysicalNetBIOS", "DEPTotalPolicyCount", "DEVICEFAMILYDEVICEFORM_NOTEBOOK", "DEVICEFAMILYINFOENUM_MOBILE", "GlobalDataIdImageNumberLow", "PROCESSOR_ARCHITECTURE_SHX", "PRODUCT_ENTERPRISE", "RelationGroup", "VER_BUILDNUMBER"}
	case Value(0x00000005):
		return []string{"ComputerNamePhysicalDnsHostname", "DEVICEFAMILYDEVICEFORM_CONVERTIBLE", "DEVICEFAMILYINFOENUM_XBOX", "GlobalDataIdImageNumberHigh", "PROCESSOR_ARCHITECTURE_ARM", "PRODUCT_HOME_BASIC_N", "RelationProcessorDie"}
	case Value(0x00000006):
		return []string{"ComputerNamePhysicalDnsDomain", "DEVICEFAMILYDEVICEFORM_DETACHABLE", "DEVICEFAMILYINFOENUM_TEAM", "GlobalDataIdTimeZoneId", "PROCESSOR_ARCHITECTURE_IA64", "PRODUCT_BUSINESS", "RelationNumaNodeEx"}
	case Value(0x00000007):
		return []string{"ComputerNamePhysicalDnsFullyQualified", "DEVICEFAMILYDEVICEFORM_ALLINONE", "DEVICEFAMILYINFOENUM_IOT", "GlobalDataIdNtMajorVersion", "PROCESSOR_ARCHITECTURE_ALPHA64", "PRODUCT_STANDARD_SERVER", "RelationProcessorModule"}
	case Value(0x00000008):
		return []string{"ComputerNameMax", "DEVICEFAMILYDEVICEFORM_STICKPC", "DEVICEFAMILYINFOENUM_IOT_HEADLESS", "GlobalDataIdNtMinorVersion", "PROCESSOR_ARCHITECTURE_MSIL", "PRODUCT_DATACENTER_SERVER", "VER_PLATFORMID"}
	case Value(0x00000009):
		return []string{"DEVICEFAMILYDEVICEFORM_PUCK", "DEVICEFAMILYINFOENUM_SERVER", "GlobalDataIdSystemExpirationDate", "PROCESSOR_ARCHITECTURE_AMD64", "PRODUCT_SMALLBUSINESS_SERVER"}
	case Value(0x0000000A):
		return []string{"DEVICEFAMILYDEVICEFORM_LARGESCREEN", "DEVICEFAMILYINFOENUM_HOLOGRAPHIC", "GlobalDataIdKdDebuggerEnabled", "PROCESSOR_ARCHITECTURE_IA32_ON_WIN64", "PRODUCT_ENTERPRISE_SERVER"}
	case Value(0x0000000B):
		return []string{"DEVICEFAMILYDEVICEFORM_HMD", "DEVICEFAMILYINFOENUM_XBOXSRA", "GlobalDataIdCyclesPerYield", "PROCESSOR_ARCHITECTURE_NEUTRAL", "PRODUCT_STARTER"}
	case Value(0x0000000C):
		return []string{"DEVICEFAMILYDEVICEFORM_INDUSTRY_HANDHELD", "DEVICEFAMILYINFOENUM_XBOXERA", "GlobalDataIdSafeBootMode", "PROCESSOR_ARCHITECTURE_ARM64", "PRODUCT_DATACENTER_SERVER_CORE"}
	case Value(0x0000000D):
		return []string{"DEVICEFAMILYDEVICEFORM_INDUSTRY_TABLET", "DEVICEFAMILYINFOENUM_SERVER_NANO", "GlobalDataIdLastSystemRITEventTickCount", "PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64", "PRODUCT_STANDARD_SERVER_CORE"}
	case Value(0x0000000E):
		return []string{"DEVICEFAMILYDEVICEFORM_BANKING", "DEVICEFAMILYINFOENUM_8828080", "GlobalDataIdConsoleSharedDataFlags", "PROCESSOR_ARCHITECTURE_IA32_ON_ARM64", "PRODUCT_ENTERPRISE_SERVER_CORE"}
	case Value(0x0000000F):
		return []string{"DEVICEFAMILYDEVICEFORM_BUILDING_AUTOMATION", "DEVICEFAMILYINFOENUM_7067329", "GlobalDataIdNtSystemRootDrive", "PRODUCT_ENTERPRISE_SERVER_IA64"}
	case Value(0x00000010):
		return []string{"DEVICEFAMILYDEVICEFORM_DIGITAL_SIGNAGE", "DEVICEFAMILYINFOENUM_WINDOWS_CORE", "GlobalDataIdQpcBypassEnabled", "PRODUCT_BUSINESS_N", "USER_CET_ENVIRONMENT_VBS_ENCLAVE", "VER_SERVICEPACKMINOR"}
	case Value(0x00000011):
		return []string{"DEVICEFAMILYDEVICEFORM_GAMING", "DEVICEFAMILYINFOENUM_MAX", "DEVICEFAMILYINFOENUM_WINDOWS_CORE_HEADLESS", "GlobalDataIdQpcData", "PRODUCT_WEB_SERVER", "USER_CET_ENVIRONMENT_VBS_BASIC_ENCLAVE"}
	case Value(0x00000012):
		return []string{"DEVICEFAMILYDEVICEFORM_HOME_AUTOMATION", "GlobalDataIdQpcBias", "PRODUCT_CLUSTER_SERVER"}
	case Value(0x00000013):
		return []string{"DEVICEFAMILYDEVICEFORM_INDUSTRIAL_AUTOMATION", "PRODUCT_HOME_SERVER"}
	case Value(0x00000014):
		return []string{"DEVICEFAMILYDEVICEFORM_KIOSK", "PRODUCT_STORAGE_EXPRESS_SERVER"}
	case Value(0x00000015):
		return []string{"DEVICEFAMILYDEVICEFORM_MAKER_BOARD", "PRODUCT_STORAGE_STANDARD_SERVER"}
	case Value(0x00000016):
		return []string{"DEVICEFAMILYDEVICEFORM_MEDICAL", "PRODUCT_STORAGE_WORKGROUP_SERVER"}
	case Value(0x00000017):
		return []string{"DEVICEFAMILYDEVICEFORM_NETWORKING", "PRODUCT_STORAGE_ENTERPRISE_SERVER"}
	case Value(0x00000018):
		return []string{"DEVICEFAMILYDEVICEFORM_POINT_OF_SERVICE", "PRODUCT_SERVER_FOR_SMALLBUSINESS"}
	case Value(0x00000019):
		return []string{"DEVICEFAMILYDEVICEFORM_PRINTING", "PRODUCT_SMALLBUSINESS_SERVER_PREMIUM"}
	case Value(0x0000001A):
		return []string{"DEVICEFAMILYDEVICEFORM_THIN_CLIENT", "PRODUCT_HOME_PREMIUM_N"}
	case Value(0x0000001B):
		return []string{"DEVICEFAMILYDEVICEFORM_TOY", "PRODUCT_ENTERPRISE_N"}
	case Value(0x0000001C):
		return []string{"DEVICEFAMILYDEVICEFORM_VENDING", "PRODUCT_ULTIMATE_N"}
	case Value(0x0000001D):
		return []string{"DEVICEFAMILYDEVICEFORM_INDUSTRY_OTHER", "PRODUCT_WEB_SERVER_CORE"}
	case Value(0x0000001E):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_ONE", "PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT"}
	case Value(0x0000001F):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_ONE_S", "PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY"}
	case Value(0x00000020):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_ONE_X", "PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING", "VER_SERVICEPACKMAJOR"}
	case Value(0x00000021):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_ONE_X_DEVKIT", "PRODUCT_SERVER_FOUNDATION"}
	case Value(0x00000022):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X", "PRODUCT_HOME_PREMIUM_SERVER"}
	case Value(0x00000023):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X_DEVKIT", "PRODUCT_SERVER_FOR_SMALLBUSINESS_V"}
	case Value(0x00000024):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_SERIES_S", "PRODUCT_STANDARD_SERVER_V"}
	case Value(0x00000025):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_01", "PRODUCT_DATACENTER_SERVER_V"}
	case Value(0x00000026):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_02", "PRODUCT_ENTERPRISE_SERVER_V"}
	case Value(0x00000027):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_03", "PRODUCT_DATACENTER_SERVER_CORE_V"}
	case Value(0x00000028):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_04", "PRODUCT_STANDARD_SERVER_CORE_V"}
	case Value(0x00000029):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_05", "PRODUCT_ENTERPRISE_SERVER_CORE_V"}
	case Value(0x0000002A):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_06", "PRODUCT_HYPERV"}
	case Value(0x0000002B):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_07", "PRODUCT_STORAGE_EXPRESS_SERVER_CORE"}
	case Value(0x0000002C):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_08", "PRODUCT_STORAGE_STANDARD_SERVER_CORE"}
	case Value(0x0000002D):
		return []string{"DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_09", "PRODUCT_STORAGE_WORKGROUP_SERVER_CORE"}
	case Value(0x0000002E):
		return []string{"DEVICEFAMILYDEVICEFORM_GAMING_HANDHELD", "PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE"}
	case Value(0x0000002F):
		return []string{"DEVICEFAMILYDEVICEFORM_GAMING_CONSOLE", "DEVICEFAMILYDEVICEFORM_MAX", "PRODUCT_STARTER_N"}
	case Value(0x00000030):
		return []string{"PRODUCT_PROFESSIONAL"}
	case Value(0x00000031):
		return []string{"PRODUCT_PROFESSIONAL_N"}
	case Value(0x00000032):
		return []string{"PRODUCT_SB_SOLUTION_SERVER"}
	case Value(0x00000033):
		return []string{"PRODUCT_SERVER_FOR_SB_SOLUTIONS"}
	case Value(0x00000034):
		return []string{"PRODUCT_STANDARD_SERVER_SOLUTIONS"}
	case Value(0x00000035):
		return []string{"PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE"}
	case Value(0x00000036):
		return []string{"PRODUCT_SB_SOLUTION_SERVER_EM"}
	case Value(0x00000037):
		return []string{"PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM"}
	case Value(0x00000038):
		return []string{"PRODUCT_SOLUTION_EMBEDDEDSERVER"}
	case Value(0x00000039):
		return []string{"PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE"}
	case Value(0x0000003A):
		return []string{"PRODUCT_PROFESSIONAL_EMBEDDED"}
	case Value(0x0000003B):
		return []string{"PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT"}
	case Value(0x0000003C):
		return []string{"PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL"}
	case Value(0x0000003D):
		return []string{"PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC"}
	case Value(0x0000003E):
		return []string{"PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC"}
	case Value(0x0000003F):
		return []string{"PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE"}
	case Value(0x00000040):
		return []string{"PRODUCT_CLUSTER_SERVER_V", "VER_SUITENAME"}
	case Value(0x00000041):
		return []string{"PRODUCT_EMBEDDED"}
	case Value(0x00000042):
		return []string{"PRODUCT_STARTER_E"}
	case Value(0x00000043):
		return []string{"PRODUCT_HOME_BASIC_E"}
	case Value(0x00000044):
		return []string{"PRODUCT_HOME_PREMIUM_E"}
	case Value(0x00000045):
		return []string{"PRODUCT_PROFESSIONAL_E"}
	case Value(0x00000046):
		return []string{"PRODUCT_ENTERPRISE_E"}
	case Value(0x00000047):
		return []string{"PRODUCT_ULTIMATE_E"}
	case Value(0x00000048):
		return []string{"PRODUCT_ENTERPRISE_EVALUATION"}
	case Value(0x0000004C):
		return []string{"PRODUCT_MULTIPOINT_STANDARD_SERVER"}
	case Value(0x0000004D):
		return []string{"PRODUCT_MULTIPOINT_PREMIUM_SERVER"}
	case Value(0x0000004F):
		return []string{"PRODUCT_STANDARD_EVALUATION_SERVER"}
	case Value(0x00000050):
		return []string{"PRODUCT_DATACENTER_EVALUATION_SERVER"}
	case Value(0x00000054):
		return []string{"PRODUCT_ENTERPRISE_N_EVALUATION"}
	case Value(0x00000055):
		return []string{"PRODUCT_EMBEDDED_AUTOMOTIVE"}
	case Value(0x00000056):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY_A"}
	case Value(0x00000057):
		return []string{"PRODUCT_THINPC"}
	case Value(0x00000058):
		return []string{"PRODUCT_EMBEDDED_A"}
	case Value(0x00000059):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY"}
	case Value(0x0000005A):
		return []string{"PRODUCT_EMBEDDED_E"}
	case Value(0x0000005B):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY_E"}
	case Value(0x0000005C):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY_A_E"}
	case Value(0x0000005F):
		return []string{"PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER"}
	case Value(0x00000060):
		return []string{"PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER"}
	case Value(0x00000061):
		return []string{"PRODUCT_CORE_ARM"}
	case Value(0x00000062):
		return []string{"PRODUCT_CORE_N"}
	case Value(0x00000063):
		return []string{"PRODUCT_CORE_COUNTRYSPECIFIC"}
	case Value(0x00000064):
		return []string{"PRODUCT_CORE_SINGLELANGUAGE"}
	case Value(0x00000065):
		return []string{"PRODUCT_CORE"}
	case Value(0x00000067):
		return []string{"PRODUCT_PROFESSIONAL_WMC"}
	case Value(0x00000069):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY_EVAL"}
	case Value(0x0000006A):
		return []string{"PRODUCT_EMBEDDED_INDUSTRY_E_EVAL"}
	case Value(0x0000006B):
		return []string{"PRODUCT_EMBEDDED_EVAL"}
	case Value(0x0000006C):
		return []string{"PRODUCT_EMBEDDED_E_EVAL"}
	case Value(0x0000006D):
		return []string{"PRODUCT_NANO_SERVER"}
	case Value(0x0000006E):
		return []string{"PRODUCT_CLOUD_STORAGE_SERVER"}
	case Value(0x0000006F):
		return []string{"PRODUCT_CORE_CONNECTED"}
	case Value(0x00000070):
		return []string{"PRODUCT_PROFESSIONAL_STUDENT"}
	case Value(0x00000071):
		return []string{"PRODUCT_CORE_CONNECTED_N"}
	case Value(0x00000072):
		return []string{"PRODUCT_PROFESSIONAL_STUDENT_N"}
	case Value(0x00000073):
		return []string{"PRODUCT_CORE_CONNECTED_SINGLELANGUAGE"}
	case Value(0x00000074):
		return []string{"PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC"}
	case Value(0x00000075):
		return []string{"PRODUCT_CONNECTED_CAR"}
	case Value(0x00000076):
		return []string{"PRODUCT_INDUSTRY_HANDHELD"}
	case Value(0x00000077):
		return []string{"PRODUCT_PPI_PRO"}
	case Value(0x00000078):
		return []string{"PRODUCT_ARM64_SERVER"}
	case Value(0x00000079):
		return []string{"PRODUCT_EDUCATION"}
	case Value(0x0000007A):
		return []string{"PRODUCT_EDUCATION_N"}
	case Value(0x0000007B):
		return []string{"PRODUCT_IOTUAP"}
	case Value(0x0000007C):
		return []string{"PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER"}
	case Value(0x0000007D):
		return []string{"PRODUCT_ENTERPRISE_S"}
	case Value(0x0000007E):
		return []string{"PRODUCT_ENTERPRISE_S_N"}
	case Value(0x0000007F):
		return []string{"PRODUCT_PROFESSIONAL_S"}
	case Value(0x00000080):
		return []string{"PRODUCT_PROFESSIONAL_S_N", "VER_PRODUCT_TYPE"}
	case Value(0x00000081):
		return []string{"PRODUCT_ENTERPRISE_S_EVALUATION"}
	case Value(0x00000082):
		return []string{"PRODUCT_ENTERPRISE_S_N_EVALUATION"}
	case Value(0x00000087):
		return []string{"PRODUCT_HOLOGRAPHIC"}
	case Value(0x00000088):
		return []string{"PRODUCT_HOLOGRAPHIC_BUSINESS"}
	case Value(0x0000008A):
		return []string{"PRODUCT_PRO_SINGLE_LANGUAGE"}
	case Value(0x0000008B):
		return []string{"PRODUCT_PRO_CHINA"}
	case Value(0x0000008C):
		return []string{"PRODUCT_ENTERPRISE_SUBSCRIPTION"}
	case Value(0x0000008D):
		return []string{"PRODUCT_ENTERPRISE_SUBSCRIPTION_N"}
	case Value(0x0000008F):
		return []string{"PRODUCT_DATACENTER_NANO_SERVER"}
	case Value(0x00000090):
		return []string{"PRODUCT_STANDARD_NANO_SERVER"}
	case Value(0x00000091):
		return []string{"PRODUCT_DATACENTER_A_SERVER_CORE"}
	case Value(0x00000092):
		return []string{"PRODUCT_STANDARD_A_SERVER_CORE"}
	case Value(0x00000093):
		return []string{"PRODUCT_DATACENTER_WS_SERVER_CORE"}
	case Value(0x00000094):
		return []string{"PRODUCT_STANDARD_WS_SERVER_CORE"}
	case Value(0x00000095):
		return []string{"PRODUCT_UTILITY_VM"}
	case Value(0x0000009F):
		return []string{"PRODUCT_DATACENTER_EVALUATION_SERVER_CORE"}
	case Value(0x000000A0):
		return []string{"PRODUCT_STANDARD_EVALUATION_SERVER_CORE"}
	case Value(0x000000A1):
		return []string{"PRODUCT_PRO_WORKSTATION"}
	case Value(0x000000A2):
		return []string{"PRODUCT_PRO_WORKSTATION_N"}
	case Value(0x000000A4):
		return []string{"PRODUCT_PRO_FOR_EDUCATION"}
	case Value(0x000000A5):
		return []string{"PRODUCT_PRO_FOR_EDUCATION_N"}
	case Value(0x000000A8):
		return []string{"PRODUCT_AZURE_SERVER_CORE"}
	case Value(0x000000A9):
		return []string{"PRODUCT_AZURE_NANO_SERVER"}
	case Value(0x000000AB):
		return []string{"PRODUCT_ENTERPRISEG"}
	case Value(0x000000AC):
		return []string{"PRODUCT_ENTERPRISEGN"}
	case Value(0x000000AF):
		return []string{"PRODUCT_SERVERRDSH"}
	case Value(0x000000B2):
		return []string{"PRODUCT_CLOUD"}
	case Value(0x000000B3):
		return []string{"PRODUCT_CLOUDN"}
	case Value(0x000000B4):
		return []string{"PRODUCT_HUBOS"}
	case Value(0x000000B6):
		return []string{"PRODUCT_ONECOREUPDATEOS"}
	case Value(0x000000B7):
		return []string{"PRODUCT_CLOUDE"}
	case Value(0x000000B9):
		return []string{"PRODUCT_IOTOS"}
	case Value(0x000000BA):
		return []string{"PRODUCT_CLOUDEN"}
	case Value(0x000000BB):
		return []string{"PRODUCT_IOTEDGEOS"}
	case Value(0x000000BC):
		return []string{"PRODUCT_IOTENTERPRISE"}
	case Value(0x000000BD):
		return []string{"PRODUCT_LITE"}
	case Value(0x000000BF):
		return []string{"PRODUCT_IOTENTERPRISES"}
	case Value(0x000000C0):
		return []string{"PRODUCT_XBOX_SYSTEMOS"}
	case Value(0x000000C2):
		return []string{"PRODUCT_XBOX_GAMEOS"}
	case Value(0x000000C3):
		return []string{"PRODUCT_XBOX_ERAOS"}
	case Value(0x000000C4):
		return []string{"PRODUCT_XBOX_DURANGOHOSTOS"}
	case Value(0x000000C5):
		return []string{"PRODUCT_XBOX_SCARLETTHOSTOS"}
	case Value(0x000000C6):
		return []string{"PRODUCT_XBOX_KEYSTONE"}
	case Value(0x000000C7):
		return []string{"PRODUCT_AZURE_SERVER_CLOUDHOST"}
	case Value(0x000000C8):
		return []string{"PRODUCT_AZURE_SERVER_CLOUDMOS"}
	case Value(0x000000CA):
		return []string{"PRODUCT_CLOUDEDITIONN"}
	case Value(0x000000CB):
		return []string{"PRODUCT_CLOUDEDITION"}
	case Value(0x000000CC):
		return []string{"PRODUCT_VALIDATION"}
	case Value(0x000000CD):
		return []string{"PRODUCT_IOTENTERPRISESK"}
	case Value(0x000000CE):
		return []string{"PRODUCT_IOTENTERPRISEK"}
	case Value(0x000000CF):
		return []string{"PRODUCT_IOTENTERPRISESEVAL"}
	case Value(0x000000D0):
		return []string{"PRODUCT_AZURE_SERVER_AGENTBRIDGE"}
	case Value(0x000000D1):
		return []string{"PRODUCT_AZURE_SERVER_NANOHOST"}
	case Value(0x000000D2):
		return []string{"PRODUCT_WNC"}
	case Value(0x0000014C):
		return []string{"IMAGE_FILE_MACHINE_I386"}
	case Value(0x00000162):
		return []string{"IMAGE_FILE_MACHINE_R3000"}
	case Value(0x00000166):
		return []string{"IMAGE_FILE_MACHINE_R4000"}
	case Value(0x00000168):
		return []string{"IMAGE_FILE_MACHINE_R10000"}
	case Value(0x00000169):
		return []string{"IMAGE_FILE_MACHINE_WCEMIPSV2"}
	case Value(0x00000184):
		return []string{"IMAGE_FILE_MACHINE_ALPHA"}
	case Value(0x00000196):
		return []string{"PRODUCT_AZURESTACKHCI_SERVER_CORE"}
	case Value(0x00000197):
		return []string{"PRODUCT_DATACENTER_SERVER_AZURE_EDITION"}
	case Value(0x00000198):
		return []string{"PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION"}
	case Value(0x00000199):
		return []string{"PRODUCT_DATACENTER_WS_SERVER_CORE_AZURE_EDITION"}
	case Value(0x000001A2):
		return []string{"IMAGE_FILE_MACHINE_SH3"}
	case Value(0x000001A3):
		return []string{"IMAGE_FILE_MACHINE_SH3DSP"}
	case Value(0x000001A4):
		return []string{"IMAGE_FILE_MACHINE_SH3E"}
	case Value(0x000001A6):
		return []string{"IMAGE_FILE_MACHINE_SH4"}
	case Value(0x000001A8):
		return []string{"IMAGE_FILE_MACHINE_SH5"}
	case Value(0x000001C0):
		return []string{"IMAGE_FILE_MACHINE_ARM"}
	case Value(0x000001C2):
		return []string{"IMAGE_FILE_MACHINE_THUMB"}
	case Value(0x000001C4):
		return []string{"IMAGE_FILE_MACHINE_ARMNT"}
	case Value(0x000001D3):
		return []string{"IMAGE_FILE_MACHINE_AM33"}
	case Value(0x000001F0):
		return []string{"IMAGE_FILE_MACHINE_POWERPC"}
	case Value(0x000001F1):
		return []string{"IMAGE_FILE_MACHINE_POWERPCFP"}
	case Value(0x00000200):
		return []string{"IMAGE_FILE_MACHINE_IA64"}
	case Value(0x00000266):
		return []string{"IMAGE_FILE_MACHINE_MIPS16"}
	case Value(0x00000284):
		return []string{"IMAGE_FILE_MACHINE_ALPHA64", "IMAGE_FILE_MACHINE_AXP64"}
	case Value(0x00000366):
		return []string{"IMAGE_FILE_MACHINE_MIPSFPU"}
	case Value(0x00000466):
		return []string{"IMAGE_FILE_MACHINE_MIPSFPU16"}
	case Value(0x00000520):
		return []string{"IMAGE_FILE_MACHINE_TRICORE"}
	case Value(0x00000CEF):
		return []string{"IMAGE_FILE_MACHINE_CEF"}
	case Value(0x00000EBC):
		return []string{"IMAGE_FILE_MACHINE_EBC"}
	case Value(0x00008664):
		return []string{"IMAGE_FILE_MACHINE_AMD64"}
	case Value(0x00009041):
		return []string{"IMAGE_FILE_MACHINE_M32R"}
	case Value(0x0000AA64):
		return []string{"IMAGE_FILE_MACHINE_ARM64"}
	case Value(0x0000C0EE):
		return []string{"IMAGE_FILE_MACHINE_CEE"}
	case Value(0x0000FFFF):
		return []string{"PROCESSOR_ARCHITECTURE_UNKNOWN", "RelationAll"}
	case Value(0x41435049):
		return []string{"ACPI"}
	case Value(0x4649524D):
		return []string{"FIRM"}
	case Value(0x52534D42):
		return []string{"RSMB"}
	case Value(0xABCDABCD):
		return []string{"PRODUCT_UNLICENSED"}
	default:
		return nil
	}
}

// Parse returns the numeric value associated with an exact symbolic name.
func Parse(name string) (Value, bool) {
	switch name {
	case "ACPI":
		return ACPI, true
	case "CacheData":
		return CacheData, true
	case "CacheInstruction":
		return CacheInstruction, true
	case "CacheTrace":
		return CacheTrace, true
	case "CacheUnified":
		return CacheUnified, true
	case "CacheUnknown":
		return CacheUnknown, true
	case "ComputerNameDnsDomain":
		return ComputerNameDnsDomain, true
	case "ComputerNameDnsFullyQualified":
		return ComputerNameDnsFullyQualified, true
	case "ComputerNameDnsHostname":
		return ComputerNameDnsHostname, true
	case "ComputerNameMax":
		return ComputerNameMax, true
	case "ComputerNameNetBIOS":
		return ComputerNameNetBIOS, true
	case "ComputerNamePhysicalDnsDomain":
		return ComputerNamePhysicalDnsDomain, true
	case "ComputerNamePhysicalDnsFullyQualified":
		return ComputerNamePhysicalDnsFullyQualified, true
	case "ComputerNamePhysicalDnsHostname":
		return ComputerNamePhysicalDnsHostname, true
	case "ComputerNamePhysicalNetBIOS":
		return ComputerNamePhysicalNetBIOS, true
	case "CpuSetInformation":
		return CpuSetInformation, true
	case "DEPPolicyAlwaysOff":
		return DEPPolicyAlwaysOff, true
	case "DEPPolicyAlwaysOn":
		return DEPPolicyAlwaysOn, true
	case "DEPPolicyOptIn":
		return DEPPolicyOptIn, true
	case "DEPPolicyOptOut":
		return DEPPolicyOptOut, true
	case "DEPTotalPolicyCount":
		return DEPTotalPolicyCount, true
	case "DEVICEFAMILYDEVICEFORM_ALLINONE":
		return DEVICEFAMILYDEVICEFORM_ALLINONE, true
	case "DEVICEFAMILYDEVICEFORM_BANKING":
		return DEVICEFAMILYDEVICEFORM_BANKING, true
	case "DEVICEFAMILYDEVICEFORM_BUILDING_AUTOMATION":
		return DEVICEFAMILYDEVICEFORM_BUILDING_AUTOMATION, true
	case "DEVICEFAMILYDEVICEFORM_CONVERTIBLE":
		return DEVICEFAMILYDEVICEFORM_CONVERTIBLE, true
	case "DEVICEFAMILYDEVICEFORM_DESKTOP":
		return DEVICEFAMILYDEVICEFORM_DESKTOP, true
	case "DEVICEFAMILYDEVICEFORM_DETACHABLE":
		return DEVICEFAMILYDEVICEFORM_DETACHABLE, true
	case "DEVICEFAMILYDEVICEFORM_DIGITAL_SIGNAGE":
		return DEVICEFAMILYDEVICEFORM_DIGITAL_SIGNAGE, true
	case "DEVICEFAMILYDEVICEFORM_GAMING":
		return DEVICEFAMILYDEVICEFORM_GAMING, true
	case "DEVICEFAMILYDEVICEFORM_GAMING_CONSOLE":
		return DEVICEFAMILYDEVICEFORM_GAMING_CONSOLE, true
	case "DEVICEFAMILYDEVICEFORM_GAMING_HANDHELD":
		return DEVICEFAMILYDEVICEFORM_GAMING_HANDHELD, true
	case "DEVICEFAMILYDEVICEFORM_HMD":
		return DEVICEFAMILYDEVICEFORM_HMD, true
	case "DEVICEFAMILYDEVICEFORM_HOME_AUTOMATION":
		return DEVICEFAMILYDEVICEFORM_HOME_AUTOMATION, true
	case "DEVICEFAMILYDEVICEFORM_INDUSTRIAL_AUTOMATION":
		return DEVICEFAMILYDEVICEFORM_INDUSTRIAL_AUTOMATION, true
	case "DEVICEFAMILYDEVICEFORM_INDUSTRY_HANDHELD":
		return DEVICEFAMILYDEVICEFORM_INDUSTRY_HANDHELD, true
	case "DEVICEFAMILYDEVICEFORM_INDUSTRY_OTHER":
		return DEVICEFAMILYDEVICEFORM_INDUSTRY_OTHER, true
	case "DEVICEFAMILYDEVICEFORM_INDUSTRY_TABLET":
		return DEVICEFAMILYDEVICEFORM_INDUSTRY_TABLET, true
	case "DEVICEFAMILYDEVICEFORM_KIOSK":
		return DEVICEFAMILYDEVICEFORM_KIOSK, true
	case "DEVICEFAMILYDEVICEFORM_LARGESCREEN":
		return DEVICEFAMILYDEVICEFORM_LARGESCREEN, true
	case "DEVICEFAMILYDEVICEFORM_MAKER_BOARD":
		return DEVICEFAMILYDEVICEFORM_MAKER_BOARD, true
	case "DEVICEFAMILYDEVICEFORM_MAX":
		return DEVICEFAMILYDEVICEFORM_MAX, true
	case "DEVICEFAMILYDEVICEFORM_MEDICAL":
		return DEVICEFAMILYDEVICEFORM_MEDICAL, true
	case "DEVICEFAMILYDEVICEFORM_NETWORKING":
		return DEVICEFAMILYDEVICEFORM_NETWORKING, true
	case "DEVICEFAMILYDEVICEFORM_NOTEBOOK":
		return DEVICEFAMILYDEVICEFORM_NOTEBOOK, true
	case "DEVICEFAMILYDEVICEFORM_PHONE":
		return DEVICEFAMILYDEVICEFORM_PHONE, true
	case "DEVICEFAMILYDEVICEFORM_POINT_OF_SERVICE":
		return DEVICEFAMILYDEVICEFORM_POINT_OF_SERVICE, true
	case "DEVICEFAMILYDEVICEFORM_PRINTING":
		return DEVICEFAMILYDEVICEFORM_PRINTING, true
	case "DEVICEFAMILYDEVICEFORM_PUCK":
		return DEVICEFAMILYDEVICEFORM_PUCK, true
	case "DEVICEFAMILYDEVICEFORM_STICKPC":
		return DEVICEFAMILYDEVICEFORM_STICKPC, true
	case "DEVICEFAMILYDEVICEFORM_TABLET":
		return DEVICEFAMILYDEVICEFORM_TABLET, true
	case "DEVICEFAMILYDEVICEFORM_THIN_CLIENT":
		return DEVICEFAMILYDEVICEFORM_THIN_CLIENT, true
	case "DEVICEFAMILYDEVICEFORM_TOY":
		return DEVICEFAMILYDEVICEFORM_TOY, true
	case "DEVICEFAMILYDEVICEFORM_UNKNOWN":
		return DEVICEFAMILYDEVICEFORM_UNKNOWN, true
	case "DEVICEFAMILYDEVICEFORM_VENDING":
		return DEVICEFAMILYDEVICEFORM_VENDING, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_ONE":
		return DEVICEFAMILYDEVICEFORM_XBOX_ONE, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_ONE_S":
		return DEVICEFAMILYDEVICEFORM_XBOX_ONE_S, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_ONE_X":
		return DEVICEFAMILYDEVICEFORM_XBOX_ONE_X, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_ONE_X_DEVKIT":
		return DEVICEFAMILYDEVICEFORM_XBOX_ONE_X_DEVKIT, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_01":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_01, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_02":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_02, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_03":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_03, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_04":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_04, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_05":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_05, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_06":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_06, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_07":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_07, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_08":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_08, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_09":
		return DEVICEFAMILYDEVICEFORM_XBOX_RESERVED_09, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_S":
		return DEVICEFAMILYDEVICEFORM_XBOX_SERIES_S, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X":
		return DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X, true
	case "DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X_DEVKIT":
		return DEVICEFAMILYDEVICEFORM_XBOX_SERIES_X_DEVKIT, true
	case "DEVICEFAMILYINFOENUM_7067329":
		return DEVICEFAMILYINFOENUM_7067329, true
	case "DEVICEFAMILYINFOENUM_8828080":
		return DEVICEFAMILYINFOENUM_8828080, true
	case "DEVICEFAMILYINFOENUM_DESKTOP":
		return DEVICEFAMILYINFOENUM_DESKTOP, true
	case "DEVICEFAMILYINFOENUM_HOLOGRAPHIC":
		return DEVICEFAMILYINFOENUM_HOLOGRAPHIC, true
	case "DEVICEFAMILYINFOENUM_IOT":
		return DEVICEFAMILYINFOENUM_IOT, true
	case "DEVICEFAMILYINFOENUM_IOT_HEADLESS":
		return DEVICEFAMILYINFOENUM_IOT_HEADLESS, true
	case "DEVICEFAMILYINFOENUM_MAX":
		return DEVICEFAMILYINFOENUM_MAX, true
	case "DEVICEFAMILYINFOENUM_MOBILE":
		return DEVICEFAMILYINFOENUM_MOBILE, true
	case "DEVICEFAMILYINFOENUM_SERVER":
		return DEVICEFAMILYINFOENUM_SERVER, true
	case "DEVICEFAMILYINFOENUM_SERVER_NANO":
		return DEVICEFAMILYINFOENUM_SERVER_NANO, true
	case "DEVICEFAMILYINFOENUM_TEAM":
		return DEVICEFAMILYINFOENUM_TEAM, true
	case "DEVICEFAMILYINFOENUM_UAP":
		return DEVICEFAMILYINFOENUM_UAP, true
	case "DEVICEFAMILYINFOENUM_WINDOWS_8X":
		return DEVICEFAMILYINFOENUM_WINDOWS_8X, true
	case "DEVICEFAMILYINFOENUM_WINDOWS_CORE":
		return DEVICEFAMILYINFOENUM_WINDOWS_CORE, true
	case "DEVICEFAMILYINFOENUM_WINDOWS_CORE_HEADLESS":
		return DEVICEFAMILYINFOENUM_WINDOWS_CORE_HEADLESS, true
	case "DEVICEFAMILYINFOENUM_WINDOWS_PHONE_8X":
		return DEVICEFAMILYINFOENUM_WINDOWS_PHONE_8X, true
	case "DEVICEFAMILYINFOENUM_XBOX":
		return DEVICEFAMILYINFOENUM_XBOX, true
	case "DEVICEFAMILYINFOENUM_XBOXERA":
		return DEVICEFAMILYINFOENUM_XBOXERA, true
	case "DEVICEFAMILYINFOENUM_XBOXSRA":
		return DEVICEFAMILYINFOENUM_XBOXSRA, true
	case "DeveloperDriveDisabledByGroupPolicy":
		return DeveloperDriveDisabledByGroupPolicy, true
	case "DeveloperDriveDisabledBySystemPolicy":
		return DeveloperDriveDisabledBySystemPolicy, true
	case "DeveloperDriveEnabled":
		return DeveloperDriveEnabled, true
	case "DeveloperDriveEnablementStateError":
		return DeveloperDriveEnablementStateError, true
	case "FIRM":
		return FIRM, true
	case "FirmwareTypeBios":
		return FirmwareTypeBios, true
	case "FirmwareTypeMax":
		return FirmwareTypeMax, true
	case "FirmwareTypeUefi":
		return FirmwareTypeUefi, true
	case "FirmwareTypeUnknown":
		return FirmwareTypeUnknown, true
	case "GlobalDataIdConsoleSharedDataFlags":
		return GlobalDataIdConsoleSharedDataFlags, true
	case "GlobalDataIdCyclesPerYield":
		return GlobalDataIdCyclesPerYield, true
	case "GlobalDataIdImageNumberHigh":
		return GlobalDataIdImageNumberHigh, true
	case "GlobalDataIdImageNumberLow":
		return GlobalDataIdImageNumberLow, true
	case "GlobalDataIdInterruptTime":
		return GlobalDataIdInterruptTime, true
	case "GlobalDataIdKdDebuggerEnabled":
		return GlobalDataIdKdDebuggerEnabled, true
	case "GlobalDataIdLastSystemRITEventTickCount":
		return GlobalDataIdLastSystemRITEventTickCount, true
	case "GlobalDataIdNtMajorVersion":
		return GlobalDataIdNtMajorVersion, true
	case "GlobalDataIdNtMinorVersion":
		return GlobalDataIdNtMinorVersion, true
	case "GlobalDataIdNtSystemRootDrive":
		return GlobalDataIdNtSystemRootDrive, true
	case "GlobalDataIdQpcBias":
		return GlobalDataIdQpcBias, true
	case "GlobalDataIdQpcBypassEnabled":
		return GlobalDataIdQpcBypassEnabled, true
	case "GlobalDataIdQpcData":
		return GlobalDataIdQpcData, true
	case "GlobalDataIdRngSeedVersion":
		return GlobalDataIdRngSeedVersion, true
	case "GlobalDataIdSafeBootMode":
		return GlobalDataIdSafeBootMode, true
	case "GlobalDataIdSystemExpirationDate":
		return GlobalDataIdSystemExpirationDate, true
	case "GlobalDataIdTimeZoneBias":
		return GlobalDataIdTimeZoneBias, true
	case "GlobalDataIdTimeZoneId":
		return GlobalDataIdTimeZoneId, true
	case "GlobalDataIdUnknown":
		return GlobalDataIdUnknown, true
	case "IMAGE_FILE_MACHINE_ALPHA":
		return IMAGE_FILE_MACHINE_ALPHA, true
	case "IMAGE_FILE_MACHINE_ALPHA64":
		return IMAGE_FILE_MACHINE_ALPHA64, true
	case "IMAGE_FILE_MACHINE_AM33":
		return IMAGE_FILE_MACHINE_AM33, true
	case "IMAGE_FILE_MACHINE_AMD64":
		return IMAGE_FILE_MACHINE_AMD64, true
	case "IMAGE_FILE_MACHINE_ARM":
		return IMAGE_FILE_MACHINE_ARM, true
	case "IMAGE_FILE_MACHINE_ARM64":
		return IMAGE_FILE_MACHINE_ARM64, true
	case "IMAGE_FILE_MACHINE_ARMNT":
		return IMAGE_FILE_MACHINE_ARMNT, true
	case "IMAGE_FILE_MACHINE_AXP64":
		return IMAGE_FILE_MACHINE_AXP64, true
	case "IMAGE_FILE_MACHINE_CEE":
		return IMAGE_FILE_MACHINE_CEE, true
	case "IMAGE_FILE_MACHINE_CEF":
		return IMAGE_FILE_MACHINE_CEF, true
	case "IMAGE_FILE_MACHINE_EBC":
		return IMAGE_FILE_MACHINE_EBC, true
	case "IMAGE_FILE_MACHINE_I386":
		return IMAGE_FILE_MACHINE_I386, true
	case "IMAGE_FILE_MACHINE_IA64":
		return IMAGE_FILE_MACHINE_IA64, true
	case "IMAGE_FILE_MACHINE_M32R":
		return IMAGE_FILE_MACHINE_M32R, true
	case "IMAGE_FILE_MACHINE_MIPS16":
		return IMAGE_FILE_MACHINE_MIPS16, true
	case "IMAGE_FILE_MACHINE_MIPSFPU":
		return IMAGE_FILE_MACHINE_MIPSFPU, true
	case "IMAGE_FILE_MACHINE_MIPSFPU16":
		return IMAGE_FILE_MACHINE_MIPSFPU16, true
	case "IMAGE_FILE_MACHINE_POWERPC":
		return IMAGE_FILE_MACHINE_POWERPC, true
	case "IMAGE_FILE_MACHINE_POWERPCFP":
		return IMAGE_FILE_MACHINE_POWERPCFP, true
	case "IMAGE_FILE_MACHINE_R10000":
		return IMAGE_FILE_MACHINE_R10000, true
	case "IMAGE_FILE_MACHINE_R3000":
		return IMAGE_FILE_MACHINE_R3000, true
	case "IMAGE_FILE_MACHINE_R4000":
		return IMAGE_FILE_MACHINE_R4000, true
	case "IMAGE_FILE_MACHINE_SH3":
		return IMAGE_FILE_MACHINE_SH3, true
	case "IMAGE_FILE_MACHINE_SH3DSP":
		return IMAGE_FILE_MACHINE_SH3DSP, true
	case "IMAGE_FILE_MACHINE_SH3E":
		return IMAGE_FILE_MACHINE_SH3E, true
	case "IMAGE_FILE_MACHINE_SH4":
		return IMAGE_FILE_MACHINE_SH4, true
	case "IMAGE_FILE_MACHINE_SH5":
		return IMAGE_FILE_MACHINE_SH5, true
	case "IMAGE_FILE_MACHINE_TARGET_HOST":
		return IMAGE_FILE_MACHINE_TARGET_HOST, true
	case "IMAGE_FILE_MACHINE_THUMB":
		return IMAGE_FILE_MACHINE_THUMB, true
	case "IMAGE_FILE_MACHINE_TRICORE":
		return IMAGE_FILE_MACHINE_TRICORE, true
	case "IMAGE_FILE_MACHINE_UNKNOWN":
		return IMAGE_FILE_MACHINE_UNKNOWN, true
	case "IMAGE_FILE_MACHINE_WCEMIPSV2":
		return IMAGE_FILE_MACHINE_WCEMIPSV2, true
	case "OS_DEPLOYMENT_COMPACT":
		return OS_DEPLOYMENT_COMPACT, true
	case "OS_DEPLOYMENT_STANDARD":
		return OS_DEPLOYMENT_STANDARD, true
	case "PROCESSOR_ARCHITECTURE_ALPHA":
		return PROCESSOR_ARCHITECTURE_ALPHA, true
	case "PROCESSOR_ARCHITECTURE_ALPHA64":
		return PROCESSOR_ARCHITECTURE_ALPHA64, true
	case "PROCESSOR_ARCHITECTURE_AMD64":
		return PROCESSOR_ARCHITECTURE_AMD64, true
	case "PROCESSOR_ARCHITECTURE_ARM":
		return PROCESSOR_ARCHITECTURE_ARM, true
	case "PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64":
		return PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64, true
	case "PROCESSOR_ARCHITECTURE_ARM64":
		return PROCESSOR_ARCHITECTURE_ARM64, true
	case "PROCESSOR_ARCHITECTURE_IA32_ON_ARM64":
		return PROCESSOR_ARCHITECTURE_IA32_ON_ARM64, true
	case "PROCESSOR_ARCHITECTURE_IA32_ON_WIN64":
		return PROCESSOR_ARCHITECTURE_IA32_ON_WIN64, true
	case "PROCESSOR_ARCHITECTURE_IA64":
		return PROCESSOR_ARCHITECTURE_IA64, true
	case "PROCESSOR_ARCHITECTURE_INTEL":
		return PROCESSOR_ARCHITECTURE_INTEL, true
	case "PROCESSOR_ARCHITECTURE_MIPS":
		return PROCESSOR_ARCHITECTURE_MIPS, true
	case "PROCESSOR_ARCHITECTURE_MSIL":
		return PROCESSOR_ARCHITECTURE_MSIL, true
	case "PROCESSOR_ARCHITECTURE_NEUTRAL":
		return PROCESSOR_ARCHITECTURE_NEUTRAL, true
	case "PROCESSOR_ARCHITECTURE_PPC":
		return PROCESSOR_ARCHITECTURE_PPC, true
	case "PROCESSOR_ARCHITECTURE_SHX":
		return PROCESSOR_ARCHITECTURE_SHX, true
	case "PROCESSOR_ARCHITECTURE_UNKNOWN":
		return PROCESSOR_ARCHITECTURE_UNKNOWN, true
	case "PRODUCT_ARM64_SERVER":
		return PRODUCT_ARM64_SERVER, true
	case "PRODUCT_AZURESTACKHCI_SERVER_CORE":
		return PRODUCT_AZURESTACKHCI_SERVER_CORE, true
	case "PRODUCT_AZURE_NANO_SERVER":
		return PRODUCT_AZURE_NANO_SERVER, true
	case "PRODUCT_AZURE_SERVER_AGENTBRIDGE":
		return PRODUCT_AZURE_SERVER_AGENTBRIDGE, true
	case "PRODUCT_AZURE_SERVER_CLOUDHOST":
		return PRODUCT_AZURE_SERVER_CLOUDHOST, true
	case "PRODUCT_AZURE_SERVER_CLOUDMOS":
		return PRODUCT_AZURE_SERVER_CLOUDMOS, true
	case "PRODUCT_AZURE_SERVER_CORE":
		return PRODUCT_AZURE_SERVER_CORE, true
	case "PRODUCT_AZURE_SERVER_NANOHOST":
		return PRODUCT_AZURE_SERVER_NANOHOST, true
	case "PRODUCT_BUSINESS":
		return PRODUCT_BUSINESS, true
	case "PRODUCT_BUSINESS_N":
		return PRODUCT_BUSINESS_N, true
	case "PRODUCT_CLOUD":
		return PRODUCT_CLOUD, true
	case "PRODUCT_CLOUDE":
		return PRODUCT_CLOUDE, true
	case "PRODUCT_CLOUDEDITION":
		return PRODUCT_CLOUDEDITION, true
	case "PRODUCT_CLOUDEDITIONN":
		return PRODUCT_CLOUDEDITIONN, true
	case "PRODUCT_CLOUDEN":
		return PRODUCT_CLOUDEN, true
	case "PRODUCT_CLOUDN":
		return PRODUCT_CLOUDN, true
	case "PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER":
		return PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER, true
	case "PRODUCT_CLOUD_STORAGE_SERVER":
		return PRODUCT_CLOUD_STORAGE_SERVER, true
	case "PRODUCT_CLUSTER_SERVER":
		return PRODUCT_CLUSTER_SERVER, true
	case "PRODUCT_CLUSTER_SERVER_V":
		return PRODUCT_CLUSTER_SERVER_V, true
	case "PRODUCT_CONNECTED_CAR":
		return PRODUCT_CONNECTED_CAR, true
	case "PRODUCT_CORE":
		return PRODUCT_CORE, true
	case "PRODUCT_CORE_ARM":
		return PRODUCT_CORE_ARM, true
	case "PRODUCT_CORE_CONNECTED":
		return PRODUCT_CORE_CONNECTED, true
	case "PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC":
		return PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC, true
	case "PRODUCT_CORE_CONNECTED_N":
		return PRODUCT_CORE_CONNECTED_N, true
	case "PRODUCT_CORE_CONNECTED_SINGLELANGUAGE":
		return PRODUCT_CORE_CONNECTED_SINGLELANGUAGE, true
	case "PRODUCT_CORE_COUNTRYSPECIFIC":
		return PRODUCT_CORE_COUNTRYSPECIFIC, true
	case "PRODUCT_CORE_N":
		return PRODUCT_CORE_N, true
	case "PRODUCT_CORE_SINGLELANGUAGE":
		return PRODUCT_CORE_SINGLELANGUAGE, true
	case "PRODUCT_DATACENTER_A_SERVER_CORE":
		return PRODUCT_DATACENTER_A_SERVER_CORE, true
	case "PRODUCT_DATACENTER_EVALUATION_SERVER":
		return PRODUCT_DATACENTER_EVALUATION_SERVER, true
	case "PRODUCT_DATACENTER_EVALUATION_SERVER_CORE":
		return PRODUCT_DATACENTER_EVALUATION_SERVER_CORE, true
	case "PRODUCT_DATACENTER_NANO_SERVER":
		return PRODUCT_DATACENTER_NANO_SERVER, true
	case "PRODUCT_DATACENTER_SERVER":
		return PRODUCT_DATACENTER_SERVER, true
	case "PRODUCT_DATACENTER_SERVER_AZURE_EDITION":
		return PRODUCT_DATACENTER_SERVER_AZURE_EDITION, true
	case "PRODUCT_DATACENTER_SERVER_CORE":
		return PRODUCT_DATACENTER_SERVER_CORE, true
	case "PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION":
		return PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION, true
	case "PRODUCT_DATACENTER_SERVER_CORE_V":
		return PRODUCT_DATACENTER_SERVER_CORE_V, true
	case "PRODUCT_DATACENTER_SERVER_V":
		return PRODUCT_DATACENTER_SERVER_V, true
	case "PRODUCT_DATACENTER_WS_SERVER_CORE":
		return PRODUCT_DATACENTER_WS_SERVER_CORE, true
	case "PRODUCT_DATACENTER_WS_SERVER_CORE_AZURE_EDITION":
		return PRODUCT_DATACENTER_WS_SERVER_CORE_AZURE_EDITION, true
	case "PRODUCT_EDUCATION":
		return PRODUCT_EDUCATION, true
	case "PRODUCT_EDUCATION_N":
		return PRODUCT_EDUCATION_N, true
	case "PRODUCT_EMBEDDED":
		return PRODUCT_EMBEDDED, true
	case "PRODUCT_EMBEDDED_A":
		return PRODUCT_EMBEDDED_A, true
	case "PRODUCT_EMBEDDED_AUTOMOTIVE":
		return PRODUCT_EMBEDDED_AUTOMOTIVE, true
	case "PRODUCT_EMBEDDED_E":
		return PRODUCT_EMBEDDED_E, true
	case "PRODUCT_EMBEDDED_EVAL":
		return PRODUCT_EMBEDDED_EVAL, true
	case "PRODUCT_EMBEDDED_E_EVAL":
		return PRODUCT_EMBEDDED_E_EVAL, true
	case "PRODUCT_EMBEDDED_INDUSTRY":
		return PRODUCT_EMBEDDED_INDUSTRY, true
	case "PRODUCT_EMBEDDED_INDUSTRY_A":
		return PRODUCT_EMBEDDED_INDUSTRY_A, true
	case "PRODUCT_EMBEDDED_INDUSTRY_A_E":
		return PRODUCT_EMBEDDED_INDUSTRY_A_E, true
	case "PRODUCT_EMBEDDED_INDUSTRY_E":
		return PRODUCT_EMBEDDED_INDUSTRY_E, true
	case "PRODUCT_EMBEDDED_INDUSTRY_EVAL":
		return PRODUCT_EMBEDDED_INDUSTRY_EVAL, true
	case "PRODUCT_EMBEDDED_INDUSTRY_E_EVAL":
		return PRODUCT_EMBEDDED_INDUSTRY_E_EVAL, true
	case "PRODUCT_ENTERPRISE":
		return PRODUCT_ENTERPRISE, true
	case "PRODUCT_ENTERPRISEG":
		return PRODUCT_ENTERPRISEG, true
	case "PRODUCT_ENTERPRISEGN":
		return PRODUCT_ENTERPRISEGN, true
	case "PRODUCT_ENTERPRISE_E":
		return PRODUCT_ENTERPRISE_E, true
	case "PRODUCT_ENTERPRISE_EVALUATION":
		return PRODUCT_ENTERPRISE_EVALUATION, true
	case "PRODUCT_ENTERPRISE_N":
		return PRODUCT_ENTERPRISE_N, true
	case "PRODUCT_ENTERPRISE_N_EVALUATION":
		return PRODUCT_ENTERPRISE_N_EVALUATION, true
	case "PRODUCT_ENTERPRISE_S":
		return PRODUCT_ENTERPRISE_S, true
	case "PRODUCT_ENTERPRISE_SERVER":
		return PRODUCT_ENTERPRISE_SERVER, true
	case "PRODUCT_ENTERPRISE_SERVER_CORE":
		return PRODUCT_ENTERPRISE_SERVER_CORE, true
	case "PRODUCT_ENTERPRISE_SERVER_CORE_V":
		return PRODUCT_ENTERPRISE_SERVER_CORE_V, true
	case "PRODUCT_ENTERPRISE_SERVER_IA64":
		return PRODUCT_ENTERPRISE_SERVER_IA64, true
	case "PRODUCT_ENTERPRISE_SERVER_V":
		return PRODUCT_ENTERPRISE_SERVER_V, true
	case "PRODUCT_ENTERPRISE_SUBSCRIPTION":
		return PRODUCT_ENTERPRISE_SUBSCRIPTION, true
	case "PRODUCT_ENTERPRISE_SUBSCRIPTION_N":
		return PRODUCT_ENTERPRISE_SUBSCRIPTION_N, true
	case "PRODUCT_ENTERPRISE_S_EVALUATION":
		return PRODUCT_ENTERPRISE_S_EVALUATION, true
	case "PRODUCT_ENTERPRISE_S_N":
		return PRODUCT_ENTERPRISE_S_N, true
	case "PRODUCT_ENTERPRISE_S_N_EVALUATION":
		return PRODUCT_ENTERPRISE_S_N_EVALUATION, true
	case "PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL":
		return PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL, true
	case "PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC":
		return PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC, true
	case "PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT":
		return PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT, true
	case "PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC":
		return PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC, true
	case "PRODUCT_HOLOGRAPHIC":
		return PRODUCT_HOLOGRAPHIC, true
	case "PRODUCT_HOLOGRAPHIC_BUSINESS":
		return PRODUCT_HOLOGRAPHIC_BUSINESS, true
	case "PRODUCT_HOME_BASIC":
		return PRODUCT_HOME_BASIC, true
	case "PRODUCT_HOME_BASIC_E":
		return PRODUCT_HOME_BASIC_E, true
	case "PRODUCT_HOME_BASIC_N":
		return PRODUCT_HOME_BASIC_N, true
	case "PRODUCT_HOME_PREMIUM":
		return PRODUCT_HOME_PREMIUM, true
	case "PRODUCT_HOME_PREMIUM_E":
		return PRODUCT_HOME_PREMIUM_E, true
	case "PRODUCT_HOME_PREMIUM_N":
		return PRODUCT_HOME_PREMIUM_N, true
	case "PRODUCT_HOME_PREMIUM_SERVER":
		return PRODUCT_HOME_PREMIUM_SERVER, true
	case "PRODUCT_HOME_SERVER":
		return PRODUCT_HOME_SERVER, true
	case "PRODUCT_HUBOS":
		return PRODUCT_HUBOS, true
	case "PRODUCT_HYPERV":
		return PRODUCT_HYPERV, true
	case "PRODUCT_INDUSTRY_HANDHELD":
		return PRODUCT_INDUSTRY_HANDHELD, true
	case "PRODUCT_IOTEDGEOS":
		return PRODUCT_IOTEDGEOS, true
	case "PRODUCT_IOTENTERPRISE":
		return PRODUCT_IOTENTERPRISE, true
	case "PRODUCT_IOTENTERPRISEK":
		return PRODUCT_IOTENTERPRISEK, true
	case "PRODUCT_IOTENTERPRISES":
		return PRODUCT_IOTENTERPRISES, true
	case "PRODUCT_IOTENTERPRISESEVAL":
		return PRODUCT_IOTENTERPRISESEVAL, true
	case "PRODUCT_IOTENTERPRISESK":
		return PRODUCT_IOTENTERPRISESK, true
	case "PRODUCT_IOTOS":
		return PRODUCT_IOTOS, true
	case "PRODUCT_IOTUAP":
		return PRODUCT_IOTUAP, true
	case "PRODUCT_LITE":
		return PRODUCT_LITE, true
	case "PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT":
		return PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT, true
	case "PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING":
		return PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING, true
	case "PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY":
		return PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY, true
	case "PRODUCT_MULTIPOINT_PREMIUM_SERVER":
		return PRODUCT_MULTIPOINT_PREMIUM_SERVER, true
	case "PRODUCT_MULTIPOINT_STANDARD_SERVER":
		return PRODUCT_MULTIPOINT_STANDARD_SERVER, true
	case "PRODUCT_NANO_SERVER":
		return PRODUCT_NANO_SERVER, true
	case "PRODUCT_ONECOREUPDATEOS":
		return PRODUCT_ONECOREUPDATEOS, true
	case "PRODUCT_PPI_PRO":
		return PRODUCT_PPI_PRO, true
	case "PRODUCT_PROFESSIONAL":
		return PRODUCT_PROFESSIONAL, true
	case "PRODUCT_PROFESSIONAL_E":
		return PRODUCT_PROFESSIONAL_E, true
	case "PRODUCT_PROFESSIONAL_EMBEDDED":
		return PRODUCT_PROFESSIONAL_EMBEDDED, true
	case "PRODUCT_PROFESSIONAL_N":
		return PRODUCT_PROFESSIONAL_N, true
	case "PRODUCT_PROFESSIONAL_S":
		return PRODUCT_PROFESSIONAL_S, true
	case "PRODUCT_PROFESSIONAL_STUDENT":
		return PRODUCT_PROFESSIONAL_STUDENT, true
	case "PRODUCT_PROFESSIONAL_STUDENT_N":
		return PRODUCT_PROFESSIONAL_STUDENT_N, true
	case "PRODUCT_PROFESSIONAL_S_N":
		return PRODUCT_PROFESSIONAL_S_N, true
	case "PRODUCT_PROFESSIONAL_WMC":
		return PRODUCT_PROFESSIONAL_WMC, true
	case "PRODUCT_PRO_CHINA":
		return PRODUCT_PRO_CHINA, true
	case "PRODUCT_PRO_FOR_EDUCATION":
		return PRODUCT_PRO_FOR_EDUCATION, true
	case "PRODUCT_PRO_FOR_EDUCATION_N":
		return PRODUCT_PRO_FOR_EDUCATION_N, true
	case "PRODUCT_PRO_SINGLE_LANGUAGE":
		return PRODUCT_PRO_SINGLE_LANGUAGE, true
	case "PRODUCT_PRO_WORKSTATION":
		return PRODUCT_PRO_WORKSTATION, true
	case "PRODUCT_PRO_WORKSTATION_N":
		return PRODUCT_PRO_WORKSTATION_N, true
	case "PRODUCT_SB_SOLUTION_SERVER":
		return PRODUCT_SB_SOLUTION_SERVER, true
	case "PRODUCT_SB_SOLUTION_SERVER_EM":
		return PRODUCT_SB_SOLUTION_SERVER_EM, true
	case "PRODUCT_SERVERRDSH":
		return PRODUCT_SERVERRDSH, true
	case "PRODUCT_SERVER_FOR_SB_SOLUTIONS":
		return PRODUCT_SERVER_FOR_SB_SOLUTIONS, true
	case "PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM":
		return PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM, true
	case "PRODUCT_SERVER_FOR_SMALLBUSINESS":
		return PRODUCT_SERVER_FOR_SMALLBUSINESS, true
	case "PRODUCT_SERVER_FOR_SMALLBUSINESS_V":
		return PRODUCT_SERVER_FOR_SMALLBUSINESS_V, true
	case "PRODUCT_SERVER_FOUNDATION":
		return PRODUCT_SERVER_FOUNDATION, true
	case "PRODUCT_SMALLBUSINESS_SERVER":
		return PRODUCT_SMALLBUSINESS_SERVER, true
	case "PRODUCT_SMALLBUSINESS_SERVER_PREMIUM":
		return PRODUCT_SMALLBUSINESS_SERVER_PREMIUM, true
	case "PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE":
		return PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE, true
	case "PRODUCT_SOLUTION_EMBEDDEDSERVER":
		return PRODUCT_SOLUTION_EMBEDDEDSERVER, true
	case "PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE":
		return PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE, true
	case "PRODUCT_STANDARD_A_SERVER_CORE":
		return PRODUCT_STANDARD_A_SERVER_CORE, true
	case "PRODUCT_STANDARD_EVALUATION_SERVER":
		return PRODUCT_STANDARD_EVALUATION_SERVER, true
	case "PRODUCT_STANDARD_EVALUATION_SERVER_CORE":
		return PRODUCT_STANDARD_EVALUATION_SERVER_CORE, true
	case "PRODUCT_STANDARD_NANO_SERVER":
		return PRODUCT_STANDARD_NANO_SERVER, true
	case "PRODUCT_STANDARD_SERVER":
		return PRODUCT_STANDARD_SERVER, true
	case "PRODUCT_STANDARD_SERVER_CORE":
		return PRODUCT_STANDARD_SERVER_CORE, true
	case "PRODUCT_STANDARD_SERVER_CORE_V":
		return PRODUCT_STANDARD_SERVER_CORE_V, true
	case "PRODUCT_STANDARD_SERVER_SOLUTIONS":
		return PRODUCT_STANDARD_SERVER_SOLUTIONS, true
	case "PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE":
		return PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE, true
	case "PRODUCT_STANDARD_SERVER_V":
		return PRODUCT_STANDARD_SERVER_V, true
	case "PRODUCT_STANDARD_WS_SERVER_CORE":
		return PRODUCT_STANDARD_WS_SERVER_CORE, true
	case "PRODUCT_STARTER":
		return PRODUCT_STARTER, true
	case "PRODUCT_STARTER_E":
		return PRODUCT_STARTER_E, true
	case "PRODUCT_STARTER_N":
		return PRODUCT_STARTER_N, true
	case "PRODUCT_STORAGE_ENTERPRISE_SERVER":
		return PRODUCT_STORAGE_ENTERPRISE_SERVER, true
	case "PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE":
		return PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE, true
	case "PRODUCT_STORAGE_EXPRESS_SERVER":
		return PRODUCT_STORAGE_EXPRESS_SERVER, true
	case "PRODUCT_STORAGE_EXPRESS_SERVER_CORE":
		return PRODUCT_STORAGE_EXPRESS_SERVER_CORE, true
	case "PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER":
		return PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER, true
	case "PRODUCT_STORAGE_STANDARD_SERVER":
		return PRODUCT_STORAGE_STANDARD_SERVER, true
	case "PRODUCT_STORAGE_STANDARD_SERVER_CORE":
		return PRODUCT_STORAGE_STANDARD_SERVER_CORE, true
	case "PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER":
		return PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER, true
	case "PRODUCT_STORAGE_WORKGROUP_SERVER":
		return PRODUCT_STORAGE_WORKGROUP_SERVER, true
	case "PRODUCT_STORAGE_WORKGROUP_SERVER_CORE":
		return PRODUCT_STORAGE_WORKGROUP_SERVER_CORE, true
	case "PRODUCT_THINPC":
		return PRODUCT_THINPC, true
	case "PRODUCT_ULTIMATE":
		return PRODUCT_ULTIMATE, true
	case "PRODUCT_ULTIMATE_E":
		return PRODUCT_ULTIMATE_E, true
	case "PRODUCT_ULTIMATE_N":
		return PRODUCT_ULTIMATE_N, true
	case "PRODUCT_UNDEFINED":
		return PRODUCT_UNDEFINED, true
	case "PRODUCT_UNLICENSED":
		return PRODUCT_UNLICENSED, true
	case "PRODUCT_UTILITY_VM":
		return PRODUCT_UTILITY_VM, true
	case "PRODUCT_VALIDATION":
		return PRODUCT_VALIDATION, true
	case "PRODUCT_WEB_SERVER":
		return PRODUCT_WEB_SERVER, true
	case "PRODUCT_WEB_SERVER_CORE":
		return PRODUCT_WEB_SERVER_CORE, true
	case "PRODUCT_WNC":
		return PRODUCT_WNC, true
	case "PRODUCT_XBOX_DURANGOHOSTOS":
		return PRODUCT_XBOX_DURANGOHOSTOS, true
	case "PRODUCT_XBOX_ERAOS":
		return PRODUCT_XBOX_ERAOS, true
	case "PRODUCT_XBOX_GAMEOS":
		return PRODUCT_XBOX_GAMEOS, true
	case "PRODUCT_XBOX_KEYSTONE":
		return PRODUCT_XBOX_KEYSTONE, true
	case "PRODUCT_XBOX_SCARLETTHOSTOS":
		return PRODUCT_XBOX_SCARLETTHOSTOS, true
	case "PRODUCT_XBOX_SYSTEMOS":
		return PRODUCT_XBOX_SYSTEMOS, true
	case "RSMB":
		return RSMB, true
	case "RelationAll":
		return RelationAll, true
	case "RelationCache":
		return RelationCache, true
	case "RelationGroup":
		return RelationGroup, true
	case "RelationNumaNode":
		return RelationNumaNode, true
	case "RelationNumaNodeEx":
		return RelationNumaNodeEx, true
	case "RelationProcessorCore":
		return RelationProcessorCore, true
	case "RelationProcessorDie":
		return RelationProcessorDie, true
	case "RelationProcessorModule":
		return RelationProcessorModule, true
	case "RelationProcessorPackage":
		return RelationProcessorPackage, true
	case "USER_CET_ENVIRONMENT_SGX2_ENCLAVE":
		return USER_CET_ENVIRONMENT_SGX2_ENCLAVE, true
	case "USER_CET_ENVIRONMENT_VBS_BASIC_ENCLAVE":
		return USER_CET_ENVIRONMENT_VBS_BASIC_ENCLAVE, true
	case "USER_CET_ENVIRONMENT_VBS_ENCLAVE":
		return USER_CET_ENVIRONMENT_VBS_ENCLAVE, true
	case "USER_CET_ENVIRONMENT_WIN32_PROCESS":
		return USER_CET_ENVIRONMENT_WIN32_PROCESS, true
	case "VER_BUILDNUMBER":
		return VER_BUILDNUMBER, true
	case "VER_MAJORVERSION":
		return VER_MAJORVERSION, true
	case "VER_MINORVERSION":
		return VER_MINORVERSION, true
	case "VER_PLATFORMID":
		return VER_PLATFORMID, true
	case "VER_PRODUCT_TYPE":
		return VER_PRODUCT_TYPE, true
	case "VER_SERVICEPACKMAJOR":
		return VER_SERVICEPACKMAJOR, true
	case "VER_SERVICEPACKMINOR":
		return VER_SERVICEPACKMINOR, true
	case "VER_SUITENAME":
		return VER_SUITENAME, true
	default:
		return Value(0), false
	}
}
