// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package sysinfo

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
)

// CACHE_DESCRIPTOR projects Windows.Win32.System.SystemInformation.CACHE_DESCRIPTOR.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-cache_descriptor.
type CACHE_DESCRIPTOR struct {
	Level         uint8
	Associativity uint8
	LineSize      uint16
	Size          uint32
	Type          PROCESSOR_CACHE_TYPE
}

// CPU_SET_INFORMATION_TYPE projects Windows.Win32.System.SystemInformation.CPU_SET_INFORMATION_TYPE.
// See https://learn.microsoft.com/windows/win32/ProcThread/cpu-set-information-type.
type CPU_SET_INFORMATION_TYPE int32

// GROUP_AFFINITY projects Windows.Win32.System.SystemInformation.GROUP_AFFINITY.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-group_affinity.
type GROUP_AFFINITY struct {
	Mask     uintptr
	Group    uint16
	Reserved [3]uint16
}

// GROUP_AFFINITY32 projects Windows.Win32.System.SystemInformation.GROUP_AFFINITY32.
type GROUP_AFFINITY32 struct {
	Mask     uint32
	Group    uint16
	Reserved [3]uint16
}

// GROUP_RELATIONSHIP projects Windows.Win32.System.SystemInformation.GROUP_RELATIONSHIP.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-group_relationship.
type GROUP_RELATIONSHIP struct {
	MaximumGroupCount uint16
	ActiveGroupCount  uint16
	Reserved          [20]uint8
	// Flexible array: this is the metadata-declared initial extent.
	// Additional elements require a larger native allocation.
	GroupInfo [1]PROCESSOR_GROUP_INFO
}

// IMAGE_FILE_MACHINE projects Windows.Win32.System.SystemInformation.IMAGE_FILE_MACHINE.
type IMAGE_FILE_MACHINE uint16

// LOGICAL_PROCESSOR_RELATIONSHIP projects Windows.Win32.System.SystemInformation.LOGICAL_PROCESSOR_RELATIONSHIP.
// See https://learn.microsoft.com/windows/win32/api/winnt/ne-winnt-logical_processor_relationship.
type LOGICAL_PROCESSOR_RELATIONSHIP int32

// MEMORYSTATUS projects Windows.Win32.System.SystemInformation.MEMORYSTATUS.
// See https://learn.microsoft.com/windows/win32/api/winbase/ns-winbase-memorystatus.
type MEMORYSTATUS struct {
	DwLength        uint32
	DwMemoryLoad    uint32
	DwTotalPhys     uintptr
	DwAvailPhys     uintptr
	DwTotalPageFile uintptr
	DwAvailPageFile uintptr
	DwTotalVirtual  uintptr
	DwAvailVirtual  uintptr
}

// OSVERSIONINFOA projects Windows.Win32.System.SystemInformation.OSVERSIONINFOA.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-osversioninfoa.
type OSVERSIONINFOA struct {
	DwOSVersionInfoSize uint32
	DwMajorVersion      uint32
	DwMinorVersion      uint32
	DwBuildNumber       uint32
	DwPlatformId        uint32
	SzCSDVersion        [128]foundation.CHAR
}

// OSVERSIONINFOEXA projects Windows.Win32.System.SystemInformation.OSVERSIONINFOEXA.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-osversioninfoexa.
type OSVERSIONINFOEXA struct {
	DwOSVersionInfoSize uint32
	DwMajorVersion      uint32
	DwMinorVersion      uint32
	DwBuildNumber       uint32
	DwPlatformId        uint32
	SzCSDVersion        [128]foundation.CHAR
	WServicePackMajor   uint16
	WServicePackMinor   uint16
	WSuiteMask          uint16
	WProductType        uint8
	WReserved           uint8
}

// OSVERSIONINFOEXW projects Windows.Win32.System.SystemInformation.OSVERSIONINFOEXW.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-osversioninfoexw.
type OSVERSIONINFOEXW struct {
	DwOSVersionInfoSize uint32
	DwMajorVersion      uint32
	DwMinorVersion      uint32
	DwBuildNumber       uint32
	DwPlatformId        uint32
	SzCSDVersion        [128]uint16
	WServicePackMajor   uint16
	WServicePackMinor   uint16
	WSuiteMask          uint16
	WProductType        uint8
	WReserved           uint8
}

// OSVERSIONINFOW projects Windows.Win32.System.SystemInformation.OSVERSIONINFOW.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-osversioninfow.
type OSVERSIONINFOW struct {
	DwOSVersionInfoSize uint32
	DwMajorVersion      uint32
	DwMinorVersion      uint32
	DwBuildNumber       uint32
	DwPlatformId        uint32
	SzCSDVersion        [128]uint16
}

// PROCESSOR_CACHE_TYPE projects Windows.Win32.System.SystemInformation.PROCESSOR_CACHE_TYPE.
// See https://learn.microsoft.com/windows/win32/api/winnt/ne-winnt-processor_cache_type.
type PROCESSOR_CACHE_TYPE int32

// PROCESSOR_GROUP_INFO projects Windows.Win32.System.SystemInformation.PROCESSOR_GROUP_INFO.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-processor_group_info.
type PROCESSOR_GROUP_INFO struct {
	MaximumProcessorCount uint8
	ActiveProcessorCount  uint8
	Reserved              [38]uint8
	ActiveProcessorMask   uintptr
}

// PROCESSOR_RELATIONSHIP projects Windows.Win32.System.SystemInformation.PROCESSOR_RELATIONSHIP.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-processor_relationship.
type PROCESSOR_RELATIONSHIP struct {
	Flags           uint8
	EfficiencyClass uint8
	Reserved        [20]uint8
	GroupCount      uint16
	// Flexible array: this is the metadata-declared initial extent.
	// Additional elements require a larger native allocation.
	GroupMask [1]GROUP_AFFINITY
}

// SYSTEM_POOL_ZEROING_INFORMATION projects Windows.Win32.System.SystemInformation.SYSTEM_POOL_ZEROING_INFORMATION.
type SYSTEM_POOL_ZEROING_INFORMATION struct {
	PoolZeroingSupportPresent foundation.BOOLEAN
}

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [12]byte                                      = [unsafe.Sizeof(*new(CACHE_DESCRIPTOR))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(CACHE_DESCRIPTOR))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(CACHE_DESCRIPTOR{}.Level)]byte{}
	_ [1]byte                                       = [unsafe.Offsetof(CACHE_DESCRIPTOR{}.Associativity)]byte{}
	_ [2]byte                                       = [unsafe.Offsetof(CACHE_DESCRIPTOR{}.LineSize)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(CACHE_DESCRIPTOR{}.Size)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(CACHE_DESCRIPTOR{}.Type)]byte{}
	_ [4]byte                                       = [unsafe.Sizeof(*new(CPU_SET_INFORMATION_TYPE))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(CPU_SET_INFORMATION_TYPE))]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Sizeof(*new(GROUP_AFFINITY))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Alignof(*new(GROUP_AFFINITY))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(GROUP_AFFINITY{}.Mask)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Offsetof(GROUP_AFFINITY{}.Group)]byte{}
	_ [6 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Offsetof(GROUP_AFFINITY{}.Reserved)]byte{}
	_ [12]byte                                      = [unsafe.Sizeof(*new(GROUP_AFFINITY32))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(GROUP_AFFINITY32))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(GROUP_AFFINITY32{}.Mask)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(GROUP_AFFINITY32{}.Group)]byte{}
	_ [6]byte                                       = [unsafe.Offsetof(GROUP_AFFINITY32{}.Reserved)]byte{}
	_ [68 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Sizeof(*new(GROUP_RELATIONSHIP))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Alignof(*new(GROUP_RELATIONSHIP))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(GROUP_RELATIONSHIP{}.MaximumGroupCount)]byte{}
	_ [2]byte                                       = [unsafe.Offsetof(GROUP_RELATIONSHIP{}.ActiveGroupCount)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(GROUP_RELATIONSHIP{}.Reserved)]byte{}
	_ [24]byte                                      = [unsafe.Offsetof(GROUP_RELATIONSHIP{}.GroupInfo)]byte{}
	_ [2]byte                                       = [unsafe.Sizeof(*new(IMAGE_FILE_MACHINE))]byte{}
	_ [2]byte                                       = [unsafe.Alignof(*new(IMAGE_FILE_MACHINE))]byte{}
	_ [4]byte                                       = [unsafe.Sizeof(*new(LOGICAL_PROCESSOR_RELATIONSHIP))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(LOGICAL_PROCESSOR_RELATIONSHIP))]byte{}
	_ [32 + (unsafe.Sizeof(uintptr(0))-4)/4*24]byte = [unsafe.Sizeof(*new(MEMORYSTATUS))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Alignof(*new(MEMORYSTATUS))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(MEMORYSTATUS{}.DwLength)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(MEMORYSTATUS{}.DwMemoryLoad)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(MEMORYSTATUS{}.DwTotalPhys)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(MEMORYSTATUS{}.DwAvailPhys)]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte  = [unsafe.Offsetof(MEMORYSTATUS{}.DwTotalPageFile)]byte{}
	_ [20 + (unsafe.Sizeof(uintptr(0))-4)/4*12]byte = [unsafe.Offsetof(MEMORYSTATUS{}.DwAvailPageFile)]byte{}
	_ [24 + (unsafe.Sizeof(uintptr(0))-4)/4*16]byte = [unsafe.Offsetof(MEMORYSTATUS{}.DwTotalVirtual)]byte{}
	_ [28 + (unsafe.Sizeof(uintptr(0))-4)/4*20]byte = [unsafe.Offsetof(MEMORYSTATUS{}.DwAvailVirtual)]byte{}
	_ [148]byte                                     = [unsafe.Sizeof(*new(OSVERSIONINFOA))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(OSVERSIONINFOA))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(OSVERSIONINFOA{}.DwOSVersionInfoSize)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(OSVERSIONINFOA{}.DwMajorVersion)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(OSVERSIONINFOA{}.DwMinorVersion)]byte{}
	_ [12]byte                                      = [unsafe.Offsetof(OSVERSIONINFOA{}.DwBuildNumber)]byte{}
	_ [16]byte                                      = [unsafe.Offsetof(OSVERSIONINFOA{}.DwPlatformId)]byte{}
	_ [20]byte                                      = [unsafe.Offsetof(OSVERSIONINFOA{}.SzCSDVersion)]byte{}
	_ [156]byte                                     = [unsafe.Sizeof(*new(OSVERSIONINFOEXA))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(OSVERSIONINFOEXA))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXA{}.DwOSVersionInfoSize)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXA{}.DwMajorVersion)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXA{}.DwMinorVersion)]byte{}
	_ [12]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXA{}.DwBuildNumber)]byte{}
	_ [16]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXA{}.DwPlatformId)]byte{}
	_ [20]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXA{}.SzCSDVersion)]byte{}
	_ [148]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXA{}.WServicePackMajor)]byte{}
	_ [150]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXA{}.WServicePackMinor)]byte{}
	_ [152]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXA{}.WSuiteMask)]byte{}
	_ [154]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXA{}.WProductType)]byte{}
	_ [155]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXA{}.WReserved)]byte{}
	_ [284]byte                                     = [unsafe.Sizeof(*new(OSVERSIONINFOEXW))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(OSVERSIONINFOEXW))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXW{}.DwOSVersionInfoSize)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXW{}.DwMajorVersion)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(OSVERSIONINFOEXW{}.DwMinorVersion)]byte{}
	_ [12]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXW{}.DwBuildNumber)]byte{}
	_ [16]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXW{}.DwPlatformId)]byte{}
	_ [20]byte                                      = [unsafe.Offsetof(OSVERSIONINFOEXW{}.SzCSDVersion)]byte{}
	_ [276]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXW{}.WServicePackMajor)]byte{}
	_ [278]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXW{}.WServicePackMinor)]byte{}
	_ [280]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXW{}.WSuiteMask)]byte{}
	_ [282]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXW{}.WProductType)]byte{}
	_ [283]byte                                     = [unsafe.Offsetof(OSVERSIONINFOEXW{}.WReserved)]byte{}
	_ [276]byte                                     = [unsafe.Sizeof(*new(OSVERSIONINFOW))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(OSVERSIONINFOW))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(OSVERSIONINFOW{}.DwOSVersionInfoSize)]byte{}
	_ [4]byte                                       = [unsafe.Offsetof(OSVERSIONINFOW{}.DwMajorVersion)]byte{}
	_ [8]byte                                       = [unsafe.Offsetof(OSVERSIONINFOW{}.DwMinorVersion)]byte{}
	_ [12]byte                                      = [unsafe.Offsetof(OSVERSIONINFOW{}.DwBuildNumber)]byte{}
	_ [16]byte                                      = [unsafe.Offsetof(OSVERSIONINFOW{}.DwPlatformId)]byte{}
	_ [20]byte                                      = [unsafe.Offsetof(OSVERSIONINFOW{}.SzCSDVersion)]byte{}
	_ [4]byte                                       = [unsafe.Sizeof(*new(PROCESSOR_CACHE_TYPE))]byte{}
	_ [4]byte                                       = [unsafe.Alignof(*new(PROCESSOR_CACHE_TYPE))]byte{}
	_ [44 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Sizeof(*new(PROCESSOR_GROUP_INFO))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Alignof(*new(PROCESSOR_GROUP_INFO))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(PROCESSOR_GROUP_INFO{}.MaximumProcessorCount)]byte{}
	_ [1]byte                                       = [unsafe.Offsetof(PROCESSOR_GROUP_INFO{}.ActiveProcessorCount)]byte{}
	_ [2]byte                                       = [unsafe.Offsetof(PROCESSOR_GROUP_INFO{}.Reserved)]byte{}
	_ [40]byte                                      = [unsafe.Offsetof(PROCESSOR_GROUP_INFO{}.ActiveProcessorMask)]byte{}
	_ [36 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Sizeof(*new(PROCESSOR_RELATIONSHIP))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte   = [unsafe.Alignof(*new(PROCESSOR_RELATIONSHIP))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(PROCESSOR_RELATIONSHIP{}.Flags)]byte{}
	_ [1]byte                                       = [unsafe.Offsetof(PROCESSOR_RELATIONSHIP{}.EfficiencyClass)]byte{}
	_ [2]byte                                       = [unsafe.Offsetof(PROCESSOR_RELATIONSHIP{}.Reserved)]byte{}
	_ [22]byte                                      = [unsafe.Offsetof(PROCESSOR_RELATIONSHIP{}.GroupCount)]byte{}
	_ [24]byte                                      = [unsafe.Offsetof(PROCESSOR_RELATIONSHIP{}.GroupMask)]byte{}
	_ [1]byte                                       = [unsafe.Sizeof(*new(SYSTEM_POOL_ZEROING_INFORMATION))]byte{}
	_ [1]byte                                       = [unsafe.Alignof(*new(SYSTEM_POOL_ZEROING_INFORMATION))]byte{}
	_ [0]byte                                       = [unsafe.Offsetof(SYSTEM_POOL_ZEROING_INFORMATION{}.PoolZeroingSupportPresent)]byte{}
)
