// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.20-preview (43b9a07fb89fb1d43edd6a05855fe88a303bf450b267ec0c4aaf00064dc62bdb).
// Documentation: Microsoft.Windows.SDK.Win32Docs 0.1.42-alpha (e83bf398dceb1957d698d24daa8a23f986beedb0109727a0ee99b229a525230b).

// Package winsock provides Winsock errors, address families, protocols, options, and message flags.
package winsock

// Value is the common representation used by this package.
type Value int64

const (
	AF_12844     Value = 25
	AF_APPLETALK Value = 16
	AF_ATM       Value = 22
	AF_BAN       Value = 21
	AF_CCITT     Value = 10
	AF_CHAOS     Value = 5
	AF_CLUSTER   Value = 24
	AF_DATAKIT   Value = 9
	AF_DECnet    Value = 12
	AF_DLI       Value = 13
	AF_ECMA      Value = 8
	AF_FIREFOX   Value = 19
	AF_HYLINK    Value = 15
	AF_HYPERV    Value = 34
	AF_ICLFXBM   Value = 31
	AF_IMPLINK   Value = 3
	// AF_INET: Documentation varies per use. Refer to each: GetAdaptersAddresses , GetIpStatisticsEx , GetTcpStatisticsEx
	// , GetTcpStatisticsEx2 , GetUdpStatisticsEx , GetUdpStatisticsEx2 .
	AF_INET Value = 2
	// AF_INET6: Documentation varies per use. Refer to each: GetAdaptersAddresses , GetIpStatisticsEx , GetTcpStatisticsEx
	// , GetTcpStatisticsEx2 , GetUdpStatisticsEx , GetUdpStatisticsEx2 .
	AF_INET6      Value = 23
	AF_IPX        Value = 6
	AF_IRDA       Value = 26
	AF_ISO        Value = 7
	AF_LAT        Value = 14
	AF_LINK       Value = 33
	AF_MAX        Value = 29
	AF_NETBIOS    Value = 17
	AF_NETDES     Value = 28
	AF_NS         Value = 6
	AF_OSI        Value = 7
	AF_PUP        Value = 4
	AF_SNA        Value = 11
	AF_TCNMESSAGE Value = 30
	AF_TCNPROCESS Value = 29
	AF_UNIX       Value = 1
	AF_UNKNOWN1   Value = 20
	// AF_UNSPEC: Return both IPv4 and IPv6 addresses associated with adapters with IPv4 or IPv6 enabled.
	AF_UNSPEC                     Value = 0
	AF_VOICEVIEW                  Value = 18
	AI_ADDRCONFIG                 Value = 1024
	AI_ALL                        Value = 256
	AI_BYPASS_DNS_CACHE           Value = 64
	AI_CANONNAME                  Value = 2
	AI_DISABLE_IDN_ENCODING       Value = 524288
	AI_DNS_ONLY                   Value = 16
	AI_DNS_RESPONSE_HOSTFILE      Value = 2
	AI_DNS_RESPONSE_SECURE        Value = 1
	AI_DNS_SERVER_TYPE_DOH        Value = 2
	AI_DNS_SERVER_TYPE_DOT        Value = 3
	AI_DNS_SERVER_TYPE_UDP        Value = 1
	AI_DNS_SERVER_UDP_FALLBACK    Value = 1
	AI_EXCLUSIVE_CUSTOM_SERVERS   Value = 2097152
	AI_EXTENDED                   Value = 2147483648
	AI_EXTRA_DNSSEC_REQUIRED      Value = 1
	AI_FILESERVER                 Value = 262144
	AI_FORCE_CLEAR_TEXT           Value = 32
	AI_FQDN                       Value = 131072
	AI_NON_AUTHORITATIVE          Value = 16384
	AI_NUMERICHOST                Value = 4
	AI_NUMERICSERV                Value = 8
	AI_PASSIVE                    Value = 1
	AI_REQUIRE_SECURE             Value = 536870912
	AI_RESOLUTION_HANDLE          Value = 1073741824
	AI_RETURN_PREFERRED_NAMES     Value = 65536
	AI_RETURN_RESPONSE_FLAGS      Value = 268435456
	AI_RETURN_TTL                 Value = 128
	AI_SECURE                     Value = 32768
	AI_SECURE_WITH_FALLBACK       Value = 1048576
	AI_V4MAPPED                   Value = 2048
	IPPROTO_AH                    Value = 51
	IPPROTO_CBT                   Value = 7
	IPPROTO_DSTOPTS               Value = 60
	IPPROTO_EGP                   Value = 8
	IPPROTO_ESP                   Value = 50
	IPPROTO_FRAGMENT              Value = 44
	IPPROTO_GGP                   Value = 3
	IPPROTO_HOPOPTS               Value = 0
	IPPROTO_ICLFXBM               Value = 78
	IPPROTO_ICMP                  Value = 1
	IPPROTO_ICMPV6                Value = 58
	IPPROTO_IDP                   Value = 22
	IPPROTO_IGMP                  Value = 2
	IPPROTO_IGP                   Value = 9
	IPPROTO_IP                    Value = 0
	IPPROTO_IPV4                  Value = 4
	IPPROTO_IPV6                  Value = 41
	IPPROTO_L2TP                  Value = 115
	IPPROTO_MAX                   Value = 256
	IPPROTO_ND                    Value = 77
	IPPROTO_NONE                  Value = 59
	IPPROTO_PGM                   Value = 113
	IPPROTO_PIM                   Value = 103
	IPPROTO_PUP                   Value = 12
	IPPROTO_RAW                   Value = 255
	IPPROTO_RDP                   Value = 27
	IPPROTO_RESERVED_IPSEC        Value = 258
	IPPROTO_RESERVED_IPSECOFFLOAD Value = 259
	IPPROTO_RESERVED_MAX          Value = 261
	IPPROTO_RESERVED_RAW          Value = 257
	IPPROTO_RESERVED_WNV          Value = 260
	// IPPROTO_RM: The following table describes IPPROTO\_RM socket options that apply to sockets created for the IPv4
	// address family (AF\_INET) with the protocol parameter to the socket function specified as reliable multicast
	// (IPPROTO\_RM).
	IPPROTO_RM      Value = 113
	IPPROTO_ROUTING Value = 43
	IPPROTO_SCTP    Value = 132
	IPPROTO_ST      Value = 5
	IPPROTO_TCP     Value = 6
	IPPROTO_UDP     Value = 17
	MSG_BCAST       Value = 1024
	MSG_CTRUNC      Value = 512
	// MSG_DONTROUTE: Specifies that the data should not be subject to routing. A Windows Sockets service provider can
	// choose to ignore this flag.
	MSG_DONTROUTE Value = 4
	MSG_ERRQUEUE  Value = 4096
	MSG_INTERRUPT Value = 16
	MSG_MAXIOVLEN Value = 16
	MSG_MCAST     Value = 2048
	// MSG_OOB: Sends OOB data (stream-style socket such as SOCK_STREAM only).
	MSG_OOB                           Value = 1
	MSG_PARTIAL                       Value = 32768
	MSG_PEEK                          Value = 2
	MSG_PUSH_IMMEDIATE                Value = 32
	MSG_TRUNC                         Value = 256
	MSG_WAITALL                       Value = 8
	NI_DGRAM                          Value = 16
	NI_MAXHOST                        Value = 1025
	NI_MAXSERV                        Value = 32
	NI_NAMEREQD                       Value = 4
	NI_NOFQDN                         Value = 1
	NI_NUMERICHOST                    Value = 2
	NI_NUMERICSERV                    Value = 8
	PF_APPLETALK                      Value = 16
	PF_ATM                            Value = 22
	PF_BAN                            Value = 21
	PF_CCITT                          Value = 10
	PF_CHAOS                          Value = 5
	PF_DATAKIT                        Value = 9
	PF_DECnet                         Value = 12
	PF_DLI                            Value = 13
	PF_ECMA                           Value = 8
	PF_FIREFOX                        Value = 19
	PF_HYLINK                         Value = 15
	PF_IMPLINK                        Value = 3
	PF_IPX                            Value = 6
	PF_IRDA                           Value = 26
	PF_ISO                            Value = 7
	PF_LAT                            Value = 14
	PF_MAX                            Value = 29
	PF_NS                             Value = 6
	PF_OSI                            Value = 7
	PF_PUP                            Value = 4
	PF_SNA                            Value = 11
	PF_UNIX                           Value = 1
	PF_UNKNOWN1                       Value = 20
	PF_VOICEVIEW                      Value = 18
	SOCKET_ERROR                      Value = -1
	SOCK_DGRAM                        Value = 2
	SOCK_NOTIFY_EVENT_ERR             Value = 64
	SOCK_NOTIFY_EVENT_HANGUP          Value = 4
	SOCK_NOTIFY_EVENT_IN              Value = 1
	SOCK_NOTIFY_EVENT_OUT             Value = 2
	SOCK_NOTIFY_EVENT_REMOVE          Value = 128
	SOCK_NOTIFY_OP_DISABLE            Value = 2
	SOCK_NOTIFY_OP_ENABLE             Value = 1
	SOCK_NOTIFY_OP_NONE               Value = 0
	SOCK_NOTIFY_OP_REMOVE             Value = 4
	SOCK_NOTIFY_REGISTER_EVENT_HANGUP Value = 4
	SOCK_NOTIFY_REGISTER_EVENT_IN     Value = 1
	SOCK_NOTIFY_REGISTER_EVENT_NONE   Value = 0
	SOCK_NOTIFY_REGISTER_EVENT_OUT    Value = 2
	SOCK_NOTIFY_TRIGGER_EDGE          Value = 8
	SOCK_NOTIFY_TRIGGER_LEVEL         Value = 4
	SOCK_NOTIFY_TRIGGER_ONESHOT       Value = 1
	SOCK_NOTIFY_TRIGGER_PERSISTENT    Value = 2
	SOCK_RAW                          Value = 3
	SOCK_RDM                          Value = 4
	SOCK_SEQPACKET                    Value = 5
	SOCK_STREAM                       Value = 1
	// SOL_SOCKET: The following tables describe SOL\_SOCKET socket options. See the getsockopt and setsockopt function
	// reference pages for more information on getting and setting socket options.
	SOL_SOCKET    Value = 65535
	SOMAXCONN     Value = 5
	SO_ACCEPTCONN Value = 2
	SO_BROADCAST  Value = 32
	// SO_BSP_STATE: Returns the local address, local port, remote address, remote port, socket type, and protocol used by
	// a socket.
	SO_BSP_STATE      Value = 4105
	SO_COMPARTMENT_ID Value = 12292
	// SO_CONDITIONAL_ACCEPT: Is designed to allow an application to decide whether or not to accept an incoming connection
	// on a listening socket.
	SO_CONDITIONAL_ACCEPT Value = 12290
	SO_CONNDATA           Value = 28672
	SO_CONNDATALEN        Value = 28676
	SO_CONNECT_TIME       Value = 28684
	SO_CONNOPT            Value = 28673
	SO_CONNOPTLEN         Value = 28677
	SO_DEBUG              Value = 1
	SO_DISCDATA           Value = 28674
	SO_DISCDATALEN        Value = 28678
	SO_DISCOPT            Value = 28675
	SO_DISCOPTLEN         Value = 28679
	SO_DONTLINGER         Value = -129
	SO_DONTROUTE          Value = 16
	SO_ERROR              Value = 4103
	// SO_EXCLUSIVEADDRUSE: The SO\_EXCLUSIVEADDRUSE socket option prevents other sockets from being forcibly bound to the
	// same address and port.
	SO_EXCLUSIVEADDRUSE Value = -5
	SO_GROUP_ID         Value = 8193
	SO_GROUP_PRIORITY   Value = 8194
	// SO_KEEPALIVE: Is designed to allow an application to enable keep-alive packets for a socket connection.
	SO_KEEPALIVE    Value = 8
	SO_LINGER       Value = 128
	SO_MAXDG        Value = 28681
	SO_MAXPATHDG    Value = 28682
	SO_MAX_MSG_SIZE Value = 8195
	SO_OOBINLINE    Value = 256
	SO_OPENTYPE     Value = 28680
	SO_ORIGINAL_DST Value = 12303
	SO_PAUSE_ACCEPT Value = 12291
	// SO_PORT_SCALABILITY: Enables local port scalability for a socket.
	SO_PORT_SCALABILITY             Value = 12294
	SO_PROTOCOL_INFO                Value = 8197
	SO_PROTOCOL_INFOA               Value = 8196
	SO_PROTOCOL_INFOW               Value = 8197
	SO_RANDOMIZE_PORT               Value = 12293
	SO_RCVBUF                       Value = 4098
	SO_RCVLOWAT                     Value = 4100
	SO_RCVTIMEO                     Value = 4102
	SO_RECEIVED_HOPLIMIT            Value = 12304
	SO_RECEIVED_PROCESSOR           Value = 12305
	SO_REUSEADDR                    Value = 4
	SO_REUSE_MULTICASTPORT          Value = 12296
	SO_REUSE_UNICASTPORT            Value = 12295
	SO_SNDBUF                       Value = 4097
	SO_SNDLOWAT                     Value = 4099
	SO_SNDTIMEO                     Value = 4101
	SO_SYNCHRONOUS_ALERT            Value = 16
	SO_SYNCHRONOUS_NONALERT         Value = 32
	SO_TIMESTAMP                    Value = 12298
	SO_TIMESTAMP_ID                 Value = 12299
	SO_TYPE                         Value = 4104
	SO_UPDATE_ACCEPT_CONTEXT        Value = 28683
	SO_UPDATE_CONNECT_CONTEXT       Value = 28688
	SO_USELOOPBACK                  Value = 64
	WSABASEERR                      Value = 10000
	WSADESCRIPTION_LEN              Value = 256
	WSAEACCES                       Value = 10013
	WSAEADDRINUSE                   Value = 10048
	WSAEADDRNOTAVAIL                Value = 10049
	WSAEAFNOSUPPORT                 Value = 10047
	WSAEALREADY                     Value = 10037
	WSAEBADF                        Value = 10009
	WSAECANCELLED                   Value = 10103
	WSAECONNABORTED                 Value = 10053
	WSAECONNREFUSED                 Value = 10061
	WSAECONNRESET                   Value = 10054
	WSAEDESTADDRREQ                 Value = 10039
	WSAEDISCON                      Value = 10101
	WSAEDQUOT                       Value = 10069
	WSAEFAULT                       Value = 10014
	WSAEHOSTDOWN                    Value = 10064
	WSAEHOSTUNREACH                 Value = 10065
	WSAEINPROGRESS                  Value = 10036
	WSAEINTR                        Value = 10004
	WSAEINVAL                       Value = 10022
	WSAEINVALIDPROCTABLE            Value = 10104
	WSAEINVALIDPROVIDER             Value = 10105
	WSAEISCONN                      Value = 10056
	WSAELOOP                        Value = 10062
	WSAEMFILE                       Value = 10024
	WSAEMSGSIZE                     Value = 10040
	WSAENAMETOOLONG                 Value = 10063
	WSAENETDOWN                     Value = 10050
	WSAENETRESET                    Value = 10052
	WSAENETUNREACH                  Value = 10051
	WSAENOBUFS                      Value = 10055
	WSAENOMORE                      Value = 10102
	WSAENOPROTOOPT                  Value = 10042
	WSAENOTCONN                     Value = 10057
	WSAENOTEMPTY                    Value = 10066
	WSAENOTSOCK                     Value = 10038
	WSAEOPNOTSUPP                   Value = 10045
	WSAEPFNOSUPPORT                 Value = 10046
	WSAEPROCLIM                     Value = 10067
	WSAEPROTONOSUPPORT              Value = 10043
	WSAEPROTOTYPE                   Value = 10041
	WSAEPROVIDERFAILEDINIT          Value = 10106
	WSAEREFUSED                     Value = 10112
	WSAEREMOTE                      Value = 10071
	WSAESHUTDOWN                    Value = 10058
	WSAESOCKTNOSUPPORT              Value = 10044
	WSAESTALE                       Value = 10070
	WSAETIMEDOUT                    Value = 10060
	WSAETOOMANYREFS                 Value = 10059
	WSAEUSERS                       Value = 10068
	WSAEWOULDBLOCK                  Value = 10035
	WSAHOST_NOT_FOUND               Value = 11001
	WSANOTINITIALISED               Value = 10093
	WSANO_DATA                      Value = 11004
	WSANO_RECOVERY                  Value = 11003
	WSAPROTOCOL_LEN                 Value = 255
	WSASERVICE_NOT_FOUND            Value = 10108
	WSASYSCALLFAILURE               Value = 10107
	WSASYSNOTREADY                  Value = 10091
	WSASYS_STATUS_LEN               Value = 128
	WSATRY_AGAIN                    Value = 11002
	WSATYPE_NOT_FOUND               Value = 10109
	WSAVERNOTSUPPORTED              Value = 10092
	WSA_E_CANCELLED                 Value = 10111
	WSA_E_NO_MORE                   Value = 10110
	WSA_FLAG_ACCESS_SYSTEM_SECURITY Value = 64
	WSA_FLAG_MULTIPOINT_C_LEAF      Value = 4
	WSA_FLAG_MULTIPOINT_C_ROOT      Value = 2
	WSA_FLAG_MULTIPOINT_D_LEAF      Value = 16
	WSA_FLAG_MULTIPOINT_D_ROOT      Value = 8
	WSA_FLAG_NO_HANDLE_INHERIT      Value = 128
	WSA_FLAG_OVERLAPPED             Value = 1
	WSA_FLAG_REGISTERED_IO          Value = 256
	WSA_INFINITE                    Value = 4294967295
	WSA_INVALID_EVENT               Value = 0
	WSA_INVALID_HANDLE              Value = 6
	WSA_INVALID_PARAMETER           Value = 87
	WSA_IO_INCOMPLETE               Value = 996
	WSA_IO_PENDING                  Value = 997
	WSA_IPSEC_NAME_POLICY_ERROR     Value = 11033
	WSA_MAXIMUM_WAIT_EVENTS         Value = 64
	WSA_NOT_ENOUGH_MEMORY           Value = 8
	WSA_OPERATION_ABORTED           Value = 995
	WSA_QOS_ADMISSION_FAILURE       Value = 11010
	WSA_QOS_BAD_OBJECT              Value = 11013
	WSA_QOS_BAD_STYLE               Value = 11012
	WSA_QOS_EFILTERCOUNT            Value = 11021
	WSA_QOS_EFILTERSTYLE            Value = 11019
	WSA_QOS_EFILTERTYPE             Value = 11020
	WSA_QOS_EFLOWCOUNT              Value = 11023
	WSA_QOS_EFLOWDESC               Value = 11026
	WSA_QOS_EFLOWSPEC               Value = 11017
	WSA_QOS_EOBJLENGTH              Value = 11022
	WSA_QOS_EPOLICYOBJ              Value = 11025
	WSA_QOS_EPROVSPECBUF            Value = 11018
	WSA_QOS_EPSFILTERSPEC           Value = 11028
	WSA_QOS_EPSFLOWSPEC             Value = 11027
	WSA_QOS_ESDMODEOBJ              Value = 11029
	WSA_QOS_ESERVICETYPE            Value = 11016
	WSA_QOS_ESHAPERATEOBJ           Value = 11030
	WSA_QOS_EUNKOWNPSOBJ            Value = 11024
	WSA_QOS_GENERIC_ERROR           Value = 11015
	WSA_QOS_NO_RECEIVERS            Value = 11008
	WSA_QOS_NO_SENDERS              Value = 11007
	WSA_QOS_POLICY_FAILURE          Value = 11011
	WSA_QOS_RECEIVERS               Value = 11005
	WSA_QOS_REQUEST_CONFIRMED       Value = 11009
	WSA_QOS_RESERVED_PETYPE         Value = 11031
	WSA_QOS_SENDERS                 Value = 11006
	WSA_QOS_TRAFFIC_CTRL_ERROR      Value = 11014
	WSA_SECURE_HOST_NOT_FOUND       Value = 11032
	WSA_WAIT_EVENT_0                Value = 0
	WSA_WAIT_FAILED                 Value = 4294967295
	WSA_WAIT_IO_COMPLETION          Value = 192
	WSA_WAIT_TIMEOUT                Value = 258
)

// Name returns the canonical symbolic name for value.
func Name(value Value) (string, bool) {
	switch value {
	case Value(-1):
		return "SOCKET_ERROR", true
	case Value(-129):
		return "SO_DONTLINGER", true
	case Value(-5):
		return "SO_EXCLUSIVEADDRUSE", true
	case Value(0):
		return "AF_UNSPEC", true
	case Value(1):
		return "AF_UNIX", true
	case Value(10):
		return "AF_CCITT", true
	case Value(10000):
		return "WSABASEERR", true
	case Value(10004):
		return "WSAEINTR", true
	case Value(10009):
		return "WSAEBADF", true
	case Value(10013):
		return "WSAEACCES", true
	case Value(10014):
		return "WSAEFAULT", true
	case Value(10022):
		return "WSAEINVAL", true
	case Value(10024):
		return "WSAEMFILE", true
	case Value(10035):
		return "WSAEWOULDBLOCK", true
	case Value(10036):
		return "WSAEINPROGRESS", true
	case Value(10037):
		return "WSAEALREADY", true
	case Value(10038):
		return "WSAENOTSOCK", true
	case Value(10039):
		return "WSAEDESTADDRREQ", true
	case Value(10040):
		return "WSAEMSGSIZE", true
	case Value(10041):
		return "WSAEPROTOTYPE", true
	case Value(10042):
		return "WSAENOPROTOOPT", true
	case Value(10043):
		return "WSAEPROTONOSUPPORT", true
	case Value(10044):
		return "WSAESOCKTNOSUPPORT", true
	case Value(10045):
		return "WSAEOPNOTSUPP", true
	case Value(10046):
		return "WSAEPFNOSUPPORT", true
	case Value(10047):
		return "WSAEAFNOSUPPORT", true
	case Value(10048):
		return "WSAEADDRINUSE", true
	case Value(10049):
		return "WSAEADDRNOTAVAIL", true
	case Value(10050):
		return "WSAENETDOWN", true
	case Value(10051):
		return "WSAENETUNREACH", true
	case Value(10052):
		return "WSAENETRESET", true
	case Value(10053):
		return "WSAECONNABORTED", true
	case Value(10054):
		return "WSAECONNRESET", true
	case Value(10055):
		return "WSAENOBUFS", true
	case Value(10056):
		return "WSAEISCONN", true
	case Value(10057):
		return "WSAENOTCONN", true
	case Value(10058):
		return "WSAESHUTDOWN", true
	case Value(10059):
		return "WSAETOOMANYREFS", true
	case Value(10060):
		return "WSAETIMEDOUT", true
	case Value(10061):
		return "WSAECONNREFUSED", true
	case Value(10062):
		return "WSAELOOP", true
	case Value(10063):
		return "WSAENAMETOOLONG", true
	case Value(10064):
		return "WSAEHOSTDOWN", true
	case Value(10065):
		return "WSAEHOSTUNREACH", true
	case Value(10066):
		return "WSAENOTEMPTY", true
	case Value(10067):
		return "WSAEPROCLIM", true
	case Value(10068):
		return "WSAEUSERS", true
	case Value(10069):
		return "WSAEDQUOT", true
	case Value(10070):
		return "WSAESTALE", true
	case Value(10071):
		return "WSAEREMOTE", true
	case Value(10091):
		return "WSASYSNOTREADY", true
	case Value(10092):
		return "WSAVERNOTSUPPORTED", true
	case Value(10093):
		return "WSANOTINITIALISED", true
	case Value(10101):
		return "WSAEDISCON", true
	case Value(10102):
		return "WSAENOMORE", true
	case Value(10103):
		return "WSAECANCELLED", true
	case Value(10104):
		return "WSAEINVALIDPROCTABLE", true
	case Value(10105):
		return "WSAEINVALIDPROVIDER", true
	case Value(10106):
		return "WSAEPROVIDERFAILEDINIT", true
	case Value(10107):
		return "WSASYSCALLFAILURE", true
	case Value(10108):
		return "WSASERVICE_NOT_FOUND", true
	case Value(10109):
		return "WSATYPE_NOT_FOUND", true
	case Value(10110):
		return "WSA_E_NO_MORE", true
	case Value(10111):
		return "WSA_E_CANCELLED", true
	case Value(10112):
		return "WSAEREFUSED", true
	case Value(1024):
		return "AI_ADDRCONFIG", true
	case Value(1025):
		return "NI_MAXHOST", true
	case Value(103):
		return "IPPROTO_PIM", true
	case Value(1048576):
		return "AI_SECURE_WITH_FALLBACK", true
	case Value(1073741824):
		return "AI_RESOLUTION_HANDLE", true
	case Value(11):
		return "AF_SNA", true
	case Value(11001):
		return "WSAHOST_NOT_FOUND", true
	case Value(11002):
		return "WSATRY_AGAIN", true
	case Value(11003):
		return "WSANO_RECOVERY", true
	case Value(11004):
		return "WSANO_DATA", true
	case Value(11005):
		return "WSA_QOS_RECEIVERS", true
	case Value(11006):
		return "WSA_QOS_SENDERS", true
	case Value(11007):
		return "WSA_QOS_NO_SENDERS", true
	case Value(11008):
		return "WSA_QOS_NO_RECEIVERS", true
	case Value(11009):
		return "WSA_QOS_REQUEST_CONFIRMED", true
	case Value(11010):
		return "WSA_QOS_ADMISSION_FAILURE", true
	case Value(11011):
		return "WSA_QOS_POLICY_FAILURE", true
	case Value(11012):
		return "WSA_QOS_BAD_STYLE", true
	case Value(11013):
		return "WSA_QOS_BAD_OBJECT", true
	case Value(11014):
		return "WSA_QOS_TRAFFIC_CTRL_ERROR", true
	case Value(11015):
		return "WSA_QOS_GENERIC_ERROR", true
	case Value(11016):
		return "WSA_QOS_ESERVICETYPE", true
	case Value(11017):
		return "WSA_QOS_EFLOWSPEC", true
	case Value(11018):
		return "WSA_QOS_EPROVSPECBUF", true
	case Value(11019):
		return "WSA_QOS_EFILTERSTYLE", true
	case Value(11020):
		return "WSA_QOS_EFILTERTYPE", true
	case Value(11021):
		return "WSA_QOS_EFILTERCOUNT", true
	case Value(11022):
		return "WSA_QOS_EOBJLENGTH", true
	case Value(11023):
		return "WSA_QOS_EFLOWCOUNT", true
	case Value(11024):
		return "WSA_QOS_EUNKOWNPSOBJ", true
	case Value(11025):
		return "WSA_QOS_EPOLICYOBJ", true
	case Value(11026):
		return "WSA_QOS_EFLOWDESC", true
	case Value(11027):
		return "WSA_QOS_EPSFLOWSPEC", true
	case Value(11028):
		return "WSA_QOS_EPSFILTERSPEC", true
	case Value(11029):
		return "WSA_QOS_ESDMODEOBJ", true
	case Value(11030):
		return "WSA_QOS_ESHAPERATEOBJ", true
	case Value(11031):
		return "WSA_QOS_RESERVED_PETYPE", true
	case Value(11032):
		return "WSA_SECURE_HOST_NOT_FOUND", true
	case Value(11033):
		return "WSA_IPSEC_NAME_POLICY_ERROR", true
	case Value(113):
		return "IPPROTO_PGM", true
	case Value(115):
		return "IPPROTO_L2TP", true
	case Value(12):
		return "AF_DECnet", true
	case Value(12290):
		return "SO_CONDITIONAL_ACCEPT", true
	case Value(12291):
		return "SO_PAUSE_ACCEPT", true
	case Value(12292):
		return "SO_COMPARTMENT_ID", true
	case Value(12293):
		return "SO_RANDOMIZE_PORT", true
	case Value(12294):
		return "SO_PORT_SCALABILITY", true
	case Value(12295):
		return "SO_REUSE_UNICASTPORT", true
	case Value(12296):
		return "SO_REUSE_MULTICASTPORT", true
	case Value(12298):
		return "SO_TIMESTAMP", true
	case Value(12299):
		return "SO_TIMESTAMP_ID", true
	case Value(12303):
		return "SO_ORIGINAL_DST", true
	case Value(12304):
		return "SO_RECEIVED_HOPLIMIT", true
	case Value(12305):
		return "SO_RECEIVED_PROCESSOR", true
	case Value(128):
		return "AI_RETURN_TTL", true
	case Value(13):
		return "AF_DLI", true
	case Value(131072):
		return "AI_FQDN", true
	case Value(132):
		return "IPPROTO_SCTP", true
	case Value(14):
		return "AF_LAT", true
	case Value(15):
		return "AF_HYLINK", true
	case Value(16):
		return "AF_APPLETALK", true
	case Value(16384):
		return "AI_NON_AUTHORITATIVE", true
	case Value(17):
		return "AF_NETBIOS", true
	case Value(18):
		return "AF_VOICEVIEW", true
	case Value(19):
		return "AF_FIREFOX", true
	case Value(192):
		return "WSA_WAIT_IO_COMPLETION", true
	case Value(2):
		return "AF_INET", true
	case Value(20):
		return "AF_UNKNOWN1", true
	case Value(2048):
		return "AI_V4MAPPED", true
	case Value(2097152):
		return "AI_EXCLUSIVE_CUSTOM_SERVERS", true
	case Value(21):
		return "AF_BAN", true
	case Value(2147483648):
		return "AI_EXTENDED", true
	case Value(22):
		return "AF_ATM", true
	case Value(23):
		return "AF_INET6", true
	case Value(24):
		return "AF_CLUSTER", true
	case Value(25):
		return "AF_12844", true
	case Value(255):
		return "IPPROTO_RAW", true
	case Value(256):
		return "AI_ALL", true
	case Value(257):
		return "IPPROTO_RESERVED_RAW", true
	case Value(258):
		return "IPPROTO_RESERVED_IPSEC", true
	case Value(259):
		return "IPPROTO_RESERVED_IPSECOFFLOAD", true
	case Value(26):
		return "AF_IRDA", true
	case Value(260):
		return "IPPROTO_RESERVED_WNV", true
	case Value(261):
		return "IPPROTO_RESERVED_MAX", true
	case Value(262144):
		return "AI_FILESERVER", true
	case Value(268435456):
		return "AI_RETURN_RESPONSE_FLAGS", true
	case Value(27):
		return "IPPROTO_RDP", true
	case Value(28):
		return "AF_NETDES", true
	case Value(28672):
		return "SO_CONNDATA", true
	case Value(28673):
		return "SO_CONNOPT", true
	case Value(28674):
		return "SO_DISCDATA", true
	case Value(28675):
		return "SO_DISCOPT", true
	case Value(28676):
		return "SO_CONNDATALEN", true
	case Value(28677):
		return "SO_CONNOPTLEN", true
	case Value(28678):
		return "SO_DISCDATALEN", true
	case Value(28679):
		return "SO_DISCOPTLEN", true
	case Value(28680):
		return "SO_OPENTYPE", true
	case Value(28681):
		return "SO_MAXDG", true
	case Value(28682):
		return "SO_MAXPATHDG", true
	case Value(28683):
		return "SO_UPDATE_ACCEPT_CONTEXT", true
	case Value(28684):
		return "SO_CONNECT_TIME", true
	case Value(28688):
		return "SO_UPDATE_CONNECT_CONTEXT", true
	case Value(29):
		return "AF_MAX", true
	case Value(3):
		return "AF_IMPLINK", true
	case Value(30):
		return "AF_TCNMESSAGE", true
	case Value(31):
		return "AF_ICLFXBM", true
	case Value(32):
		return "AI_FORCE_CLEAR_TEXT", true
	case Value(32768):
		return "AI_SECURE", true
	case Value(33):
		return "AF_LINK", true
	case Value(34):
		return "AF_HYPERV", true
	case Value(4):
		return "AF_PUP", true
	case Value(4096):
		return "MSG_ERRQUEUE", true
	case Value(4097):
		return "SO_SNDBUF", true
	case Value(4098):
		return "SO_RCVBUF", true
	case Value(4099):
		return "SO_SNDLOWAT", true
	case Value(41):
		return "IPPROTO_IPV6", true
	case Value(4100):
		return "SO_RCVLOWAT", true
	case Value(4101):
		return "SO_SNDTIMEO", true
	case Value(4102):
		return "SO_RCVTIMEO", true
	case Value(4103):
		return "SO_ERROR", true
	case Value(4104):
		return "SO_TYPE", true
	case Value(4105):
		return "SO_BSP_STATE", true
	case Value(4294967295):
		return "WSA_INFINITE", true
	case Value(43):
		return "IPPROTO_ROUTING", true
	case Value(44):
		return "IPPROTO_FRAGMENT", true
	case Value(5):
		return "AF_CHAOS", true
	case Value(50):
		return "IPPROTO_ESP", true
	case Value(51):
		return "IPPROTO_AH", true
	case Value(512):
		return "MSG_CTRUNC", true
	case Value(524288):
		return "AI_DISABLE_IDN_ENCODING", true
	case Value(536870912):
		return "AI_REQUIRE_SECURE", true
	case Value(58):
		return "IPPROTO_ICMPV6", true
	case Value(59):
		return "IPPROTO_NONE", true
	case Value(6):
		return "AF_IPX", true
	case Value(60):
		return "IPPROTO_DSTOPTS", true
	case Value(64):
		return "AI_BYPASS_DNS_CACHE", true
	case Value(65535):
		return "SOL_SOCKET", true
	case Value(65536):
		return "AI_RETURN_PREFERRED_NAMES", true
	case Value(7):
		return "AF_ISO", true
	case Value(77):
		return "IPPROTO_ND", true
	case Value(78):
		return "IPPROTO_ICLFXBM", true
	case Value(8):
		return "AF_ECMA", true
	case Value(8193):
		return "SO_GROUP_ID", true
	case Value(8194):
		return "SO_GROUP_PRIORITY", true
	case Value(8195):
		return "SO_MAX_MSG_SIZE", true
	case Value(8196):
		return "SO_PROTOCOL_INFOA", true
	case Value(8197):
		return "SO_PROTOCOL_INFO", true
	case Value(87):
		return "WSA_INVALID_PARAMETER", true
	case Value(9):
		return "AF_DATAKIT", true
	case Value(995):
		return "WSA_OPERATION_ABORTED", true
	case Value(996):
		return "WSA_IO_INCOMPLETE", true
	case Value(997):
		return "WSA_IO_PENDING", true
	default:
		return "", false
	}
}

// Names returns every symbolic alias for value in lexical order.
func Names(value Value) []string {
	switch value {
	case Value(-1):
		return []string{"SOCKET_ERROR"}
	case Value(-129):
		return []string{"SO_DONTLINGER"}
	case Value(-5):
		return []string{"SO_EXCLUSIVEADDRUSE"}
	case Value(0):
		return []string{"AF_UNSPEC", "IPPROTO_HOPOPTS", "IPPROTO_IP", "SOCK_NOTIFY_OP_NONE", "SOCK_NOTIFY_REGISTER_EVENT_NONE", "WSA_INVALID_EVENT", "WSA_WAIT_EVENT_0"}
	case Value(1):
		return []string{"AF_UNIX", "AI_DNS_RESPONSE_SECURE", "AI_DNS_SERVER_TYPE_UDP", "AI_DNS_SERVER_UDP_FALLBACK", "AI_EXTRA_DNSSEC_REQUIRED", "AI_PASSIVE", "IPPROTO_ICMP", "MSG_OOB", "NI_NOFQDN", "PF_UNIX", "SOCK_NOTIFY_EVENT_IN", "SOCK_NOTIFY_OP_ENABLE", "SOCK_NOTIFY_REGISTER_EVENT_IN", "SOCK_NOTIFY_TRIGGER_ONESHOT", "SOCK_STREAM", "SO_DEBUG", "WSA_FLAG_OVERLAPPED"}
	case Value(10):
		return []string{"AF_CCITT", "PF_CCITT"}
	case Value(10000):
		return []string{"WSABASEERR"}
	case Value(10004):
		return []string{"WSAEINTR"}
	case Value(10009):
		return []string{"WSAEBADF"}
	case Value(10013):
		return []string{"WSAEACCES"}
	case Value(10014):
		return []string{"WSAEFAULT"}
	case Value(10022):
		return []string{"WSAEINVAL"}
	case Value(10024):
		return []string{"WSAEMFILE"}
	case Value(10035):
		return []string{"WSAEWOULDBLOCK"}
	case Value(10036):
		return []string{"WSAEINPROGRESS"}
	case Value(10037):
		return []string{"WSAEALREADY"}
	case Value(10038):
		return []string{"WSAENOTSOCK"}
	case Value(10039):
		return []string{"WSAEDESTADDRREQ"}
	case Value(10040):
		return []string{"WSAEMSGSIZE"}
	case Value(10041):
		return []string{"WSAEPROTOTYPE"}
	case Value(10042):
		return []string{"WSAENOPROTOOPT"}
	case Value(10043):
		return []string{"WSAEPROTONOSUPPORT"}
	case Value(10044):
		return []string{"WSAESOCKTNOSUPPORT"}
	case Value(10045):
		return []string{"WSAEOPNOTSUPP"}
	case Value(10046):
		return []string{"WSAEPFNOSUPPORT"}
	case Value(10047):
		return []string{"WSAEAFNOSUPPORT"}
	case Value(10048):
		return []string{"WSAEADDRINUSE"}
	case Value(10049):
		return []string{"WSAEADDRNOTAVAIL"}
	case Value(10050):
		return []string{"WSAENETDOWN"}
	case Value(10051):
		return []string{"WSAENETUNREACH"}
	case Value(10052):
		return []string{"WSAENETRESET"}
	case Value(10053):
		return []string{"WSAECONNABORTED"}
	case Value(10054):
		return []string{"WSAECONNRESET"}
	case Value(10055):
		return []string{"WSAENOBUFS"}
	case Value(10056):
		return []string{"WSAEISCONN"}
	case Value(10057):
		return []string{"WSAENOTCONN"}
	case Value(10058):
		return []string{"WSAESHUTDOWN"}
	case Value(10059):
		return []string{"WSAETOOMANYREFS"}
	case Value(10060):
		return []string{"WSAETIMEDOUT"}
	case Value(10061):
		return []string{"WSAECONNREFUSED"}
	case Value(10062):
		return []string{"WSAELOOP"}
	case Value(10063):
		return []string{"WSAENAMETOOLONG"}
	case Value(10064):
		return []string{"WSAEHOSTDOWN"}
	case Value(10065):
		return []string{"WSAEHOSTUNREACH"}
	case Value(10066):
		return []string{"WSAENOTEMPTY"}
	case Value(10067):
		return []string{"WSAEPROCLIM"}
	case Value(10068):
		return []string{"WSAEUSERS"}
	case Value(10069):
		return []string{"WSAEDQUOT"}
	case Value(10070):
		return []string{"WSAESTALE"}
	case Value(10071):
		return []string{"WSAEREMOTE"}
	case Value(10091):
		return []string{"WSASYSNOTREADY"}
	case Value(10092):
		return []string{"WSAVERNOTSUPPORTED"}
	case Value(10093):
		return []string{"WSANOTINITIALISED"}
	case Value(10101):
		return []string{"WSAEDISCON"}
	case Value(10102):
		return []string{"WSAENOMORE"}
	case Value(10103):
		return []string{"WSAECANCELLED"}
	case Value(10104):
		return []string{"WSAEINVALIDPROCTABLE"}
	case Value(10105):
		return []string{"WSAEINVALIDPROVIDER"}
	case Value(10106):
		return []string{"WSAEPROVIDERFAILEDINIT"}
	case Value(10107):
		return []string{"WSASYSCALLFAILURE"}
	case Value(10108):
		return []string{"WSASERVICE_NOT_FOUND"}
	case Value(10109):
		return []string{"WSATYPE_NOT_FOUND"}
	case Value(10110):
		return []string{"WSA_E_NO_MORE"}
	case Value(10111):
		return []string{"WSA_E_CANCELLED"}
	case Value(10112):
		return []string{"WSAEREFUSED"}
	case Value(1024):
		return []string{"AI_ADDRCONFIG", "MSG_BCAST"}
	case Value(1025):
		return []string{"NI_MAXHOST"}
	case Value(103):
		return []string{"IPPROTO_PIM"}
	case Value(1048576):
		return []string{"AI_SECURE_WITH_FALLBACK"}
	case Value(1073741824):
		return []string{"AI_RESOLUTION_HANDLE"}
	case Value(11):
		return []string{"AF_SNA", "PF_SNA"}
	case Value(11001):
		return []string{"WSAHOST_NOT_FOUND"}
	case Value(11002):
		return []string{"WSATRY_AGAIN"}
	case Value(11003):
		return []string{"WSANO_RECOVERY"}
	case Value(11004):
		return []string{"WSANO_DATA"}
	case Value(11005):
		return []string{"WSA_QOS_RECEIVERS"}
	case Value(11006):
		return []string{"WSA_QOS_SENDERS"}
	case Value(11007):
		return []string{"WSA_QOS_NO_SENDERS"}
	case Value(11008):
		return []string{"WSA_QOS_NO_RECEIVERS"}
	case Value(11009):
		return []string{"WSA_QOS_REQUEST_CONFIRMED"}
	case Value(11010):
		return []string{"WSA_QOS_ADMISSION_FAILURE"}
	case Value(11011):
		return []string{"WSA_QOS_POLICY_FAILURE"}
	case Value(11012):
		return []string{"WSA_QOS_BAD_STYLE"}
	case Value(11013):
		return []string{"WSA_QOS_BAD_OBJECT"}
	case Value(11014):
		return []string{"WSA_QOS_TRAFFIC_CTRL_ERROR"}
	case Value(11015):
		return []string{"WSA_QOS_GENERIC_ERROR"}
	case Value(11016):
		return []string{"WSA_QOS_ESERVICETYPE"}
	case Value(11017):
		return []string{"WSA_QOS_EFLOWSPEC"}
	case Value(11018):
		return []string{"WSA_QOS_EPROVSPECBUF"}
	case Value(11019):
		return []string{"WSA_QOS_EFILTERSTYLE"}
	case Value(11020):
		return []string{"WSA_QOS_EFILTERTYPE"}
	case Value(11021):
		return []string{"WSA_QOS_EFILTERCOUNT"}
	case Value(11022):
		return []string{"WSA_QOS_EOBJLENGTH"}
	case Value(11023):
		return []string{"WSA_QOS_EFLOWCOUNT"}
	case Value(11024):
		return []string{"WSA_QOS_EUNKOWNPSOBJ"}
	case Value(11025):
		return []string{"WSA_QOS_EPOLICYOBJ"}
	case Value(11026):
		return []string{"WSA_QOS_EFLOWDESC"}
	case Value(11027):
		return []string{"WSA_QOS_EPSFLOWSPEC"}
	case Value(11028):
		return []string{"WSA_QOS_EPSFILTERSPEC"}
	case Value(11029):
		return []string{"WSA_QOS_ESDMODEOBJ"}
	case Value(11030):
		return []string{"WSA_QOS_ESHAPERATEOBJ"}
	case Value(11031):
		return []string{"WSA_QOS_RESERVED_PETYPE"}
	case Value(11032):
		return []string{"WSA_SECURE_HOST_NOT_FOUND"}
	case Value(11033):
		return []string{"WSA_IPSEC_NAME_POLICY_ERROR"}
	case Value(113):
		return []string{"IPPROTO_PGM", "IPPROTO_RM"}
	case Value(115):
		return []string{"IPPROTO_L2TP"}
	case Value(12):
		return []string{"AF_DECnet", "IPPROTO_PUP", "PF_DECnet"}
	case Value(12290):
		return []string{"SO_CONDITIONAL_ACCEPT"}
	case Value(12291):
		return []string{"SO_PAUSE_ACCEPT"}
	case Value(12292):
		return []string{"SO_COMPARTMENT_ID"}
	case Value(12293):
		return []string{"SO_RANDOMIZE_PORT"}
	case Value(12294):
		return []string{"SO_PORT_SCALABILITY"}
	case Value(12295):
		return []string{"SO_REUSE_UNICASTPORT"}
	case Value(12296):
		return []string{"SO_REUSE_MULTICASTPORT"}
	case Value(12298):
		return []string{"SO_TIMESTAMP"}
	case Value(12299):
		return []string{"SO_TIMESTAMP_ID"}
	case Value(12303):
		return []string{"SO_ORIGINAL_DST"}
	case Value(12304):
		return []string{"SO_RECEIVED_HOPLIMIT"}
	case Value(12305):
		return []string{"SO_RECEIVED_PROCESSOR"}
	case Value(128):
		return []string{"AI_RETURN_TTL", "SOCK_NOTIFY_EVENT_REMOVE", "SO_LINGER", "WSASYS_STATUS_LEN", "WSA_FLAG_NO_HANDLE_INHERIT"}
	case Value(13):
		return []string{"AF_DLI", "PF_DLI"}
	case Value(131072):
		return []string{"AI_FQDN"}
	case Value(132):
		return []string{"IPPROTO_SCTP"}
	case Value(14):
		return []string{"AF_LAT", "PF_LAT"}
	case Value(15):
		return []string{"AF_HYLINK", "PF_HYLINK"}
	case Value(16):
		return []string{"AF_APPLETALK", "AI_DNS_ONLY", "MSG_INTERRUPT", "MSG_MAXIOVLEN", "NI_DGRAM", "PF_APPLETALK", "SO_DONTROUTE", "SO_SYNCHRONOUS_ALERT", "WSA_FLAG_MULTIPOINT_D_LEAF"}
	case Value(16384):
		return []string{"AI_NON_AUTHORITATIVE"}
	case Value(17):
		return []string{"AF_NETBIOS", "IPPROTO_UDP"}
	case Value(18):
		return []string{"AF_VOICEVIEW", "PF_VOICEVIEW"}
	case Value(19):
		return []string{"AF_FIREFOX", "PF_FIREFOX"}
	case Value(192):
		return []string{"WSA_WAIT_IO_COMPLETION"}
	case Value(2):
		return []string{"AF_INET", "AI_CANONNAME", "AI_DNS_RESPONSE_HOSTFILE", "AI_DNS_SERVER_TYPE_DOH", "IPPROTO_IGMP", "MSG_PEEK", "NI_NUMERICHOST", "SOCK_DGRAM", "SOCK_NOTIFY_EVENT_OUT", "SOCK_NOTIFY_OP_DISABLE", "SOCK_NOTIFY_REGISTER_EVENT_OUT", "SOCK_NOTIFY_TRIGGER_PERSISTENT", "SO_ACCEPTCONN", "WSA_FLAG_MULTIPOINT_C_ROOT"}
	case Value(20):
		return []string{"AF_UNKNOWN1", "PF_UNKNOWN1"}
	case Value(2048):
		return []string{"AI_V4MAPPED", "MSG_MCAST"}
	case Value(2097152):
		return []string{"AI_EXCLUSIVE_CUSTOM_SERVERS"}
	case Value(21):
		return []string{"AF_BAN", "PF_BAN"}
	case Value(2147483648):
		return []string{"AI_EXTENDED"}
	case Value(22):
		return []string{"AF_ATM", "IPPROTO_IDP", "PF_ATM"}
	case Value(23):
		return []string{"AF_INET6"}
	case Value(24):
		return []string{"AF_CLUSTER"}
	case Value(25):
		return []string{"AF_12844"}
	case Value(255):
		return []string{"IPPROTO_RAW", "WSAPROTOCOL_LEN"}
	case Value(256):
		return []string{"AI_ALL", "IPPROTO_MAX", "MSG_TRUNC", "SO_OOBINLINE", "WSADESCRIPTION_LEN", "WSA_FLAG_REGISTERED_IO"}
	case Value(257):
		return []string{"IPPROTO_RESERVED_RAW"}
	case Value(258):
		return []string{"IPPROTO_RESERVED_IPSEC", "WSA_WAIT_TIMEOUT"}
	case Value(259):
		return []string{"IPPROTO_RESERVED_IPSECOFFLOAD"}
	case Value(26):
		return []string{"AF_IRDA", "PF_IRDA"}
	case Value(260):
		return []string{"IPPROTO_RESERVED_WNV"}
	case Value(261):
		return []string{"IPPROTO_RESERVED_MAX"}
	case Value(262144):
		return []string{"AI_FILESERVER"}
	case Value(268435456):
		return []string{"AI_RETURN_RESPONSE_FLAGS"}
	case Value(27):
		return []string{"IPPROTO_RDP"}
	case Value(28):
		return []string{"AF_NETDES"}
	case Value(28672):
		return []string{"SO_CONNDATA"}
	case Value(28673):
		return []string{"SO_CONNOPT"}
	case Value(28674):
		return []string{"SO_DISCDATA"}
	case Value(28675):
		return []string{"SO_DISCOPT"}
	case Value(28676):
		return []string{"SO_CONNDATALEN"}
	case Value(28677):
		return []string{"SO_CONNOPTLEN"}
	case Value(28678):
		return []string{"SO_DISCDATALEN"}
	case Value(28679):
		return []string{"SO_DISCOPTLEN"}
	case Value(28680):
		return []string{"SO_OPENTYPE"}
	case Value(28681):
		return []string{"SO_MAXDG"}
	case Value(28682):
		return []string{"SO_MAXPATHDG"}
	case Value(28683):
		return []string{"SO_UPDATE_ACCEPT_CONTEXT"}
	case Value(28684):
		return []string{"SO_CONNECT_TIME"}
	case Value(28688):
		return []string{"SO_UPDATE_CONNECT_CONTEXT"}
	case Value(29):
		return []string{"AF_MAX", "AF_TCNPROCESS", "PF_MAX"}
	case Value(3):
		return []string{"AF_IMPLINK", "AI_DNS_SERVER_TYPE_DOT", "IPPROTO_GGP", "PF_IMPLINK", "SOCK_RAW"}
	case Value(30):
		return []string{"AF_TCNMESSAGE"}
	case Value(31):
		return []string{"AF_ICLFXBM"}
	case Value(32):
		return []string{"AI_FORCE_CLEAR_TEXT", "MSG_PUSH_IMMEDIATE", "NI_MAXSERV", "SO_BROADCAST", "SO_SYNCHRONOUS_NONALERT"}
	case Value(32768):
		return []string{"AI_SECURE", "MSG_PARTIAL"}
	case Value(33):
		return []string{"AF_LINK"}
	case Value(34):
		return []string{"AF_HYPERV"}
	case Value(4):
		return []string{"AF_PUP", "AI_NUMERICHOST", "IPPROTO_IPV4", "MSG_DONTROUTE", "NI_NAMEREQD", "PF_PUP", "SOCK_NOTIFY_EVENT_HANGUP", "SOCK_NOTIFY_OP_REMOVE", "SOCK_NOTIFY_REGISTER_EVENT_HANGUP", "SOCK_NOTIFY_TRIGGER_LEVEL", "SOCK_RDM", "SO_REUSEADDR", "WSA_FLAG_MULTIPOINT_C_LEAF"}
	case Value(4096):
		return []string{"MSG_ERRQUEUE"}
	case Value(4097):
		return []string{"SO_SNDBUF"}
	case Value(4098):
		return []string{"SO_RCVBUF"}
	case Value(4099):
		return []string{"SO_SNDLOWAT"}
	case Value(41):
		return []string{"IPPROTO_IPV6"}
	case Value(4100):
		return []string{"SO_RCVLOWAT"}
	case Value(4101):
		return []string{"SO_SNDTIMEO"}
	case Value(4102):
		return []string{"SO_RCVTIMEO"}
	case Value(4103):
		return []string{"SO_ERROR"}
	case Value(4104):
		return []string{"SO_TYPE"}
	case Value(4105):
		return []string{"SO_BSP_STATE"}
	case Value(4294967295):
		return []string{"WSA_INFINITE", "WSA_WAIT_FAILED"}
	case Value(43):
		return []string{"IPPROTO_ROUTING"}
	case Value(44):
		return []string{"IPPROTO_FRAGMENT"}
	case Value(5):
		return []string{"AF_CHAOS", "IPPROTO_ST", "PF_CHAOS", "SOCK_SEQPACKET", "SOMAXCONN"}
	case Value(50):
		return []string{"IPPROTO_ESP"}
	case Value(51):
		return []string{"IPPROTO_AH"}
	case Value(512):
		return []string{"MSG_CTRUNC"}
	case Value(524288):
		return []string{"AI_DISABLE_IDN_ENCODING"}
	case Value(536870912):
		return []string{"AI_REQUIRE_SECURE"}
	case Value(58):
		return []string{"IPPROTO_ICMPV6"}
	case Value(59):
		return []string{"IPPROTO_NONE"}
	case Value(6):
		return []string{"AF_IPX", "AF_NS", "IPPROTO_TCP", "PF_IPX", "PF_NS", "WSA_INVALID_HANDLE"}
	case Value(60):
		return []string{"IPPROTO_DSTOPTS"}
	case Value(64):
		return []string{"AI_BYPASS_DNS_CACHE", "SOCK_NOTIFY_EVENT_ERR", "SO_USELOOPBACK", "WSA_FLAG_ACCESS_SYSTEM_SECURITY", "WSA_MAXIMUM_WAIT_EVENTS"}
	case Value(65535):
		return []string{"SOL_SOCKET"}
	case Value(65536):
		return []string{"AI_RETURN_PREFERRED_NAMES"}
	case Value(7):
		return []string{"AF_ISO", "AF_OSI", "IPPROTO_CBT", "PF_ISO", "PF_OSI"}
	case Value(77):
		return []string{"IPPROTO_ND"}
	case Value(78):
		return []string{"IPPROTO_ICLFXBM"}
	case Value(8):
		return []string{"AF_ECMA", "AI_NUMERICSERV", "IPPROTO_EGP", "MSG_WAITALL", "NI_NUMERICSERV", "PF_ECMA", "SOCK_NOTIFY_TRIGGER_EDGE", "SO_KEEPALIVE", "WSA_FLAG_MULTIPOINT_D_ROOT", "WSA_NOT_ENOUGH_MEMORY"}
	case Value(8193):
		return []string{"SO_GROUP_ID"}
	case Value(8194):
		return []string{"SO_GROUP_PRIORITY"}
	case Value(8195):
		return []string{"SO_MAX_MSG_SIZE"}
	case Value(8196):
		return []string{"SO_PROTOCOL_INFOA"}
	case Value(8197):
		return []string{"SO_PROTOCOL_INFO", "SO_PROTOCOL_INFOW"}
	case Value(87):
		return []string{"WSA_INVALID_PARAMETER"}
	case Value(9):
		return []string{"AF_DATAKIT", "IPPROTO_IGP", "PF_DATAKIT"}
	case Value(995):
		return []string{"WSA_OPERATION_ABORTED"}
	case Value(996):
		return []string{"WSA_IO_INCOMPLETE"}
	case Value(997):
		return []string{"WSA_IO_PENDING"}
	default:
		return nil
	}
}

// Parse returns the numeric value associated with an exact symbolic name.
func Parse(name string) (Value, bool) {
	switch name {
	case "AF_12844":
		return AF_12844, true
	case "AF_APPLETALK":
		return AF_APPLETALK, true
	case "AF_ATM":
		return AF_ATM, true
	case "AF_BAN":
		return AF_BAN, true
	case "AF_CCITT":
		return AF_CCITT, true
	case "AF_CHAOS":
		return AF_CHAOS, true
	case "AF_CLUSTER":
		return AF_CLUSTER, true
	case "AF_DATAKIT":
		return AF_DATAKIT, true
	case "AF_DECnet":
		return AF_DECnet, true
	case "AF_DLI":
		return AF_DLI, true
	case "AF_ECMA":
		return AF_ECMA, true
	case "AF_FIREFOX":
		return AF_FIREFOX, true
	case "AF_HYLINK":
		return AF_HYLINK, true
	case "AF_HYPERV":
		return AF_HYPERV, true
	case "AF_ICLFXBM":
		return AF_ICLFXBM, true
	case "AF_IMPLINK":
		return AF_IMPLINK, true
	case "AF_INET":
		return AF_INET, true
	case "AF_INET6":
		return AF_INET6, true
	case "AF_IPX":
		return AF_IPX, true
	case "AF_IRDA":
		return AF_IRDA, true
	case "AF_ISO":
		return AF_ISO, true
	case "AF_LAT":
		return AF_LAT, true
	case "AF_LINK":
		return AF_LINK, true
	case "AF_MAX":
		return AF_MAX, true
	case "AF_NETBIOS":
		return AF_NETBIOS, true
	case "AF_NETDES":
		return AF_NETDES, true
	case "AF_NS":
		return AF_NS, true
	case "AF_OSI":
		return AF_OSI, true
	case "AF_PUP":
		return AF_PUP, true
	case "AF_SNA":
		return AF_SNA, true
	case "AF_TCNMESSAGE":
		return AF_TCNMESSAGE, true
	case "AF_TCNPROCESS":
		return AF_TCNPROCESS, true
	case "AF_UNIX":
		return AF_UNIX, true
	case "AF_UNKNOWN1":
		return AF_UNKNOWN1, true
	case "AF_UNSPEC":
		return AF_UNSPEC, true
	case "AF_VOICEVIEW":
		return AF_VOICEVIEW, true
	case "AI_ADDRCONFIG":
		return AI_ADDRCONFIG, true
	case "AI_ALL":
		return AI_ALL, true
	case "AI_BYPASS_DNS_CACHE":
		return AI_BYPASS_DNS_CACHE, true
	case "AI_CANONNAME":
		return AI_CANONNAME, true
	case "AI_DISABLE_IDN_ENCODING":
		return AI_DISABLE_IDN_ENCODING, true
	case "AI_DNS_ONLY":
		return AI_DNS_ONLY, true
	case "AI_DNS_RESPONSE_HOSTFILE":
		return AI_DNS_RESPONSE_HOSTFILE, true
	case "AI_DNS_RESPONSE_SECURE":
		return AI_DNS_RESPONSE_SECURE, true
	case "AI_DNS_SERVER_TYPE_DOH":
		return AI_DNS_SERVER_TYPE_DOH, true
	case "AI_DNS_SERVER_TYPE_DOT":
		return AI_DNS_SERVER_TYPE_DOT, true
	case "AI_DNS_SERVER_TYPE_UDP":
		return AI_DNS_SERVER_TYPE_UDP, true
	case "AI_DNS_SERVER_UDP_FALLBACK":
		return AI_DNS_SERVER_UDP_FALLBACK, true
	case "AI_EXCLUSIVE_CUSTOM_SERVERS":
		return AI_EXCLUSIVE_CUSTOM_SERVERS, true
	case "AI_EXTENDED":
		return AI_EXTENDED, true
	case "AI_EXTRA_DNSSEC_REQUIRED":
		return AI_EXTRA_DNSSEC_REQUIRED, true
	case "AI_FILESERVER":
		return AI_FILESERVER, true
	case "AI_FORCE_CLEAR_TEXT":
		return AI_FORCE_CLEAR_TEXT, true
	case "AI_FQDN":
		return AI_FQDN, true
	case "AI_NON_AUTHORITATIVE":
		return AI_NON_AUTHORITATIVE, true
	case "AI_NUMERICHOST":
		return AI_NUMERICHOST, true
	case "AI_NUMERICSERV":
		return AI_NUMERICSERV, true
	case "AI_PASSIVE":
		return AI_PASSIVE, true
	case "AI_REQUIRE_SECURE":
		return AI_REQUIRE_SECURE, true
	case "AI_RESOLUTION_HANDLE":
		return AI_RESOLUTION_HANDLE, true
	case "AI_RETURN_PREFERRED_NAMES":
		return AI_RETURN_PREFERRED_NAMES, true
	case "AI_RETURN_RESPONSE_FLAGS":
		return AI_RETURN_RESPONSE_FLAGS, true
	case "AI_RETURN_TTL":
		return AI_RETURN_TTL, true
	case "AI_SECURE":
		return AI_SECURE, true
	case "AI_SECURE_WITH_FALLBACK":
		return AI_SECURE_WITH_FALLBACK, true
	case "AI_V4MAPPED":
		return AI_V4MAPPED, true
	case "IPPROTO_AH":
		return IPPROTO_AH, true
	case "IPPROTO_CBT":
		return IPPROTO_CBT, true
	case "IPPROTO_DSTOPTS":
		return IPPROTO_DSTOPTS, true
	case "IPPROTO_EGP":
		return IPPROTO_EGP, true
	case "IPPROTO_ESP":
		return IPPROTO_ESP, true
	case "IPPROTO_FRAGMENT":
		return IPPROTO_FRAGMENT, true
	case "IPPROTO_GGP":
		return IPPROTO_GGP, true
	case "IPPROTO_HOPOPTS":
		return IPPROTO_HOPOPTS, true
	case "IPPROTO_ICLFXBM":
		return IPPROTO_ICLFXBM, true
	case "IPPROTO_ICMP":
		return IPPROTO_ICMP, true
	case "IPPROTO_ICMPV6":
		return IPPROTO_ICMPV6, true
	case "IPPROTO_IDP":
		return IPPROTO_IDP, true
	case "IPPROTO_IGMP":
		return IPPROTO_IGMP, true
	case "IPPROTO_IGP":
		return IPPROTO_IGP, true
	case "IPPROTO_IP":
		return IPPROTO_IP, true
	case "IPPROTO_IPV4":
		return IPPROTO_IPV4, true
	case "IPPROTO_IPV6":
		return IPPROTO_IPV6, true
	case "IPPROTO_L2TP":
		return IPPROTO_L2TP, true
	case "IPPROTO_MAX":
		return IPPROTO_MAX, true
	case "IPPROTO_ND":
		return IPPROTO_ND, true
	case "IPPROTO_NONE":
		return IPPROTO_NONE, true
	case "IPPROTO_PGM":
		return IPPROTO_PGM, true
	case "IPPROTO_PIM":
		return IPPROTO_PIM, true
	case "IPPROTO_PUP":
		return IPPROTO_PUP, true
	case "IPPROTO_RAW":
		return IPPROTO_RAW, true
	case "IPPROTO_RDP":
		return IPPROTO_RDP, true
	case "IPPROTO_RESERVED_IPSEC":
		return IPPROTO_RESERVED_IPSEC, true
	case "IPPROTO_RESERVED_IPSECOFFLOAD":
		return IPPROTO_RESERVED_IPSECOFFLOAD, true
	case "IPPROTO_RESERVED_MAX":
		return IPPROTO_RESERVED_MAX, true
	case "IPPROTO_RESERVED_RAW":
		return IPPROTO_RESERVED_RAW, true
	case "IPPROTO_RESERVED_WNV":
		return IPPROTO_RESERVED_WNV, true
	case "IPPROTO_RM":
		return IPPROTO_RM, true
	case "IPPROTO_ROUTING":
		return IPPROTO_ROUTING, true
	case "IPPROTO_SCTP":
		return IPPROTO_SCTP, true
	case "IPPROTO_ST":
		return IPPROTO_ST, true
	case "IPPROTO_TCP":
		return IPPROTO_TCP, true
	case "IPPROTO_UDP":
		return IPPROTO_UDP, true
	case "MSG_BCAST":
		return MSG_BCAST, true
	case "MSG_CTRUNC":
		return MSG_CTRUNC, true
	case "MSG_DONTROUTE":
		return MSG_DONTROUTE, true
	case "MSG_ERRQUEUE":
		return MSG_ERRQUEUE, true
	case "MSG_INTERRUPT":
		return MSG_INTERRUPT, true
	case "MSG_MAXIOVLEN":
		return MSG_MAXIOVLEN, true
	case "MSG_MCAST":
		return MSG_MCAST, true
	case "MSG_OOB":
		return MSG_OOB, true
	case "MSG_PARTIAL":
		return MSG_PARTIAL, true
	case "MSG_PEEK":
		return MSG_PEEK, true
	case "MSG_PUSH_IMMEDIATE":
		return MSG_PUSH_IMMEDIATE, true
	case "MSG_TRUNC":
		return MSG_TRUNC, true
	case "MSG_WAITALL":
		return MSG_WAITALL, true
	case "NI_DGRAM":
		return NI_DGRAM, true
	case "NI_MAXHOST":
		return NI_MAXHOST, true
	case "NI_MAXSERV":
		return NI_MAXSERV, true
	case "NI_NAMEREQD":
		return NI_NAMEREQD, true
	case "NI_NOFQDN":
		return NI_NOFQDN, true
	case "NI_NUMERICHOST":
		return NI_NUMERICHOST, true
	case "NI_NUMERICSERV":
		return NI_NUMERICSERV, true
	case "PF_APPLETALK":
		return PF_APPLETALK, true
	case "PF_ATM":
		return PF_ATM, true
	case "PF_BAN":
		return PF_BAN, true
	case "PF_CCITT":
		return PF_CCITT, true
	case "PF_CHAOS":
		return PF_CHAOS, true
	case "PF_DATAKIT":
		return PF_DATAKIT, true
	case "PF_DECnet":
		return PF_DECnet, true
	case "PF_DLI":
		return PF_DLI, true
	case "PF_ECMA":
		return PF_ECMA, true
	case "PF_FIREFOX":
		return PF_FIREFOX, true
	case "PF_HYLINK":
		return PF_HYLINK, true
	case "PF_IMPLINK":
		return PF_IMPLINK, true
	case "PF_IPX":
		return PF_IPX, true
	case "PF_IRDA":
		return PF_IRDA, true
	case "PF_ISO":
		return PF_ISO, true
	case "PF_LAT":
		return PF_LAT, true
	case "PF_MAX":
		return PF_MAX, true
	case "PF_NS":
		return PF_NS, true
	case "PF_OSI":
		return PF_OSI, true
	case "PF_PUP":
		return PF_PUP, true
	case "PF_SNA":
		return PF_SNA, true
	case "PF_UNIX":
		return PF_UNIX, true
	case "PF_UNKNOWN1":
		return PF_UNKNOWN1, true
	case "PF_VOICEVIEW":
		return PF_VOICEVIEW, true
	case "SOCKET_ERROR":
		return SOCKET_ERROR, true
	case "SOCK_DGRAM":
		return SOCK_DGRAM, true
	case "SOCK_NOTIFY_EVENT_ERR":
		return SOCK_NOTIFY_EVENT_ERR, true
	case "SOCK_NOTIFY_EVENT_HANGUP":
		return SOCK_NOTIFY_EVENT_HANGUP, true
	case "SOCK_NOTIFY_EVENT_IN":
		return SOCK_NOTIFY_EVENT_IN, true
	case "SOCK_NOTIFY_EVENT_OUT":
		return SOCK_NOTIFY_EVENT_OUT, true
	case "SOCK_NOTIFY_EVENT_REMOVE":
		return SOCK_NOTIFY_EVENT_REMOVE, true
	case "SOCK_NOTIFY_OP_DISABLE":
		return SOCK_NOTIFY_OP_DISABLE, true
	case "SOCK_NOTIFY_OP_ENABLE":
		return SOCK_NOTIFY_OP_ENABLE, true
	case "SOCK_NOTIFY_OP_NONE":
		return SOCK_NOTIFY_OP_NONE, true
	case "SOCK_NOTIFY_OP_REMOVE":
		return SOCK_NOTIFY_OP_REMOVE, true
	case "SOCK_NOTIFY_REGISTER_EVENT_HANGUP":
		return SOCK_NOTIFY_REGISTER_EVENT_HANGUP, true
	case "SOCK_NOTIFY_REGISTER_EVENT_IN":
		return SOCK_NOTIFY_REGISTER_EVENT_IN, true
	case "SOCK_NOTIFY_REGISTER_EVENT_NONE":
		return SOCK_NOTIFY_REGISTER_EVENT_NONE, true
	case "SOCK_NOTIFY_REGISTER_EVENT_OUT":
		return SOCK_NOTIFY_REGISTER_EVENT_OUT, true
	case "SOCK_NOTIFY_TRIGGER_EDGE":
		return SOCK_NOTIFY_TRIGGER_EDGE, true
	case "SOCK_NOTIFY_TRIGGER_LEVEL":
		return SOCK_NOTIFY_TRIGGER_LEVEL, true
	case "SOCK_NOTIFY_TRIGGER_ONESHOT":
		return SOCK_NOTIFY_TRIGGER_ONESHOT, true
	case "SOCK_NOTIFY_TRIGGER_PERSISTENT":
		return SOCK_NOTIFY_TRIGGER_PERSISTENT, true
	case "SOCK_RAW":
		return SOCK_RAW, true
	case "SOCK_RDM":
		return SOCK_RDM, true
	case "SOCK_SEQPACKET":
		return SOCK_SEQPACKET, true
	case "SOCK_STREAM":
		return SOCK_STREAM, true
	case "SOL_SOCKET":
		return SOL_SOCKET, true
	case "SOMAXCONN":
		return SOMAXCONN, true
	case "SO_ACCEPTCONN":
		return SO_ACCEPTCONN, true
	case "SO_BROADCAST":
		return SO_BROADCAST, true
	case "SO_BSP_STATE":
		return SO_BSP_STATE, true
	case "SO_COMPARTMENT_ID":
		return SO_COMPARTMENT_ID, true
	case "SO_CONDITIONAL_ACCEPT":
		return SO_CONDITIONAL_ACCEPT, true
	case "SO_CONNDATA":
		return SO_CONNDATA, true
	case "SO_CONNDATALEN":
		return SO_CONNDATALEN, true
	case "SO_CONNECT_TIME":
		return SO_CONNECT_TIME, true
	case "SO_CONNOPT":
		return SO_CONNOPT, true
	case "SO_CONNOPTLEN":
		return SO_CONNOPTLEN, true
	case "SO_DEBUG":
		return SO_DEBUG, true
	case "SO_DISCDATA":
		return SO_DISCDATA, true
	case "SO_DISCDATALEN":
		return SO_DISCDATALEN, true
	case "SO_DISCOPT":
		return SO_DISCOPT, true
	case "SO_DISCOPTLEN":
		return SO_DISCOPTLEN, true
	case "SO_DONTLINGER":
		return SO_DONTLINGER, true
	case "SO_DONTROUTE":
		return SO_DONTROUTE, true
	case "SO_ERROR":
		return SO_ERROR, true
	case "SO_EXCLUSIVEADDRUSE":
		return SO_EXCLUSIVEADDRUSE, true
	case "SO_GROUP_ID":
		return SO_GROUP_ID, true
	case "SO_GROUP_PRIORITY":
		return SO_GROUP_PRIORITY, true
	case "SO_KEEPALIVE":
		return SO_KEEPALIVE, true
	case "SO_LINGER":
		return SO_LINGER, true
	case "SO_MAXDG":
		return SO_MAXDG, true
	case "SO_MAXPATHDG":
		return SO_MAXPATHDG, true
	case "SO_MAX_MSG_SIZE":
		return SO_MAX_MSG_SIZE, true
	case "SO_OOBINLINE":
		return SO_OOBINLINE, true
	case "SO_OPENTYPE":
		return SO_OPENTYPE, true
	case "SO_ORIGINAL_DST":
		return SO_ORIGINAL_DST, true
	case "SO_PAUSE_ACCEPT":
		return SO_PAUSE_ACCEPT, true
	case "SO_PORT_SCALABILITY":
		return SO_PORT_SCALABILITY, true
	case "SO_PROTOCOL_INFO":
		return SO_PROTOCOL_INFO, true
	case "SO_PROTOCOL_INFOA":
		return SO_PROTOCOL_INFOA, true
	case "SO_PROTOCOL_INFOW":
		return SO_PROTOCOL_INFOW, true
	case "SO_RANDOMIZE_PORT":
		return SO_RANDOMIZE_PORT, true
	case "SO_RCVBUF":
		return SO_RCVBUF, true
	case "SO_RCVLOWAT":
		return SO_RCVLOWAT, true
	case "SO_RCVTIMEO":
		return SO_RCVTIMEO, true
	case "SO_RECEIVED_HOPLIMIT":
		return SO_RECEIVED_HOPLIMIT, true
	case "SO_RECEIVED_PROCESSOR":
		return SO_RECEIVED_PROCESSOR, true
	case "SO_REUSEADDR":
		return SO_REUSEADDR, true
	case "SO_REUSE_MULTICASTPORT":
		return SO_REUSE_MULTICASTPORT, true
	case "SO_REUSE_UNICASTPORT":
		return SO_REUSE_UNICASTPORT, true
	case "SO_SNDBUF":
		return SO_SNDBUF, true
	case "SO_SNDLOWAT":
		return SO_SNDLOWAT, true
	case "SO_SNDTIMEO":
		return SO_SNDTIMEO, true
	case "SO_SYNCHRONOUS_ALERT":
		return SO_SYNCHRONOUS_ALERT, true
	case "SO_SYNCHRONOUS_NONALERT":
		return SO_SYNCHRONOUS_NONALERT, true
	case "SO_TIMESTAMP":
		return SO_TIMESTAMP, true
	case "SO_TIMESTAMP_ID":
		return SO_TIMESTAMP_ID, true
	case "SO_TYPE":
		return SO_TYPE, true
	case "SO_UPDATE_ACCEPT_CONTEXT":
		return SO_UPDATE_ACCEPT_CONTEXT, true
	case "SO_UPDATE_CONNECT_CONTEXT":
		return SO_UPDATE_CONNECT_CONTEXT, true
	case "SO_USELOOPBACK":
		return SO_USELOOPBACK, true
	case "WSABASEERR":
		return WSABASEERR, true
	case "WSADESCRIPTION_LEN":
		return WSADESCRIPTION_LEN, true
	case "WSAEACCES":
		return WSAEACCES, true
	case "WSAEADDRINUSE":
		return WSAEADDRINUSE, true
	case "WSAEADDRNOTAVAIL":
		return WSAEADDRNOTAVAIL, true
	case "WSAEAFNOSUPPORT":
		return WSAEAFNOSUPPORT, true
	case "WSAEALREADY":
		return WSAEALREADY, true
	case "WSAEBADF":
		return WSAEBADF, true
	case "WSAECANCELLED":
		return WSAECANCELLED, true
	case "WSAECONNABORTED":
		return WSAECONNABORTED, true
	case "WSAECONNREFUSED":
		return WSAECONNREFUSED, true
	case "WSAECONNRESET":
		return WSAECONNRESET, true
	case "WSAEDESTADDRREQ":
		return WSAEDESTADDRREQ, true
	case "WSAEDISCON":
		return WSAEDISCON, true
	case "WSAEDQUOT":
		return WSAEDQUOT, true
	case "WSAEFAULT":
		return WSAEFAULT, true
	case "WSAEHOSTDOWN":
		return WSAEHOSTDOWN, true
	case "WSAEHOSTUNREACH":
		return WSAEHOSTUNREACH, true
	case "WSAEINPROGRESS":
		return WSAEINPROGRESS, true
	case "WSAEINTR":
		return WSAEINTR, true
	case "WSAEINVAL":
		return WSAEINVAL, true
	case "WSAEINVALIDPROCTABLE":
		return WSAEINVALIDPROCTABLE, true
	case "WSAEINVALIDPROVIDER":
		return WSAEINVALIDPROVIDER, true
	case "WSAEISCONN":
		return WSAEISCONN, true
	case "WSAELOOP":
		return WSAELOOP, true
	case "WSAEMFILE":
		return WSAEMFILE, true
	case "WSAEMSGSIZE":
		return WSAEMSGSIZE, true
	case "WSAENAMETOOLONG":
		return WSAENAMETOOLONG, true
	case "WSAENETDOWN":
		return WSAENETDOWN, true
	case "WSAENETRESET":
		return WSAENETRESET, true
	case "WSAENETUNREACH":
		return WSAENETUNREACH, true
	case "WSAENOBUFS":
		return WSAENOBUFS, true
	case "WSAENOMORE":
		return WSAENOMORE, true
	case "WSAENOPROTOOPT":
		return WSAENOPROTOOPT, true
	case "WSAENOTCONN":
		return WSAENOTCONN, true
	case "WSAENOTEMPTY":
		return WSAENOTEMPTY, true
	case "WSAENOTSOCK":
		return WSAENOTSOCK, true
	case "WSAEOPNOTSUPP":
		return WSAEOPNOTSUPP, true
	case "WSAEPFNOSUPPORT":
		return WSAEPFNOSUPPORT, true
	case "WSAEPROCLIM":
		return WSAEPROCLIM, true
	case "WSAEPROTONOSUPPORT":
		return WSAEPROTONOSUPPORT, true
	case "WSAEPROTOTYPE":
		return WSAEPROTOTYPE, true
	case "WSAEPROVIDERFAILEDINIT":
		return WSAEPROVIDERFAILEDINIT, true
	case "WSAEREFUSED":
		return WSAEREFUSED, true
	case "WSAEREMOTE":
		return WSAEREMOTE, true
	case "WSAESHUTDOWN":
		return WSAESHUTDOWN, true
	case "WSAESOCKTNOSUPPORT":
		return WSAESOCKTNOSUPPORT, true
	case "WSAESTALE":
		return WSAESTALE, true
	case "WSAETIMEDOUT":
		return WSAETIMEDOUT, true
	case "WSAETOOMANYREFS":
		return WSAETOOMANYREFS, true
	case "WSAEUSERS":
		return WSAEUSERS, true
	case "WSAEWOULDBLOCK":
		return WSAEWOULDBLOCK, true
	case "WSAHOST_NOT_FOUND":
		return WSAHOST_NOT_FOUND, true
	case "WSANOTINITIALISED":
		return WSANOTINITIALISED, true
	case "WSANO_DATA":
		return WSANO_DATA, true
	case "WSANO_RECOVERY":
		return WSANO_RECOVERY, true
	case "WSAPROTOCOL_LEN":
		return WSAPROTOCOL_LEN, true
	case "WSASERVICE_NOT_FOUND":
		return WSASERVICE_NOT_FOUND, true
	case "WSASYSCALLFAILURE":
		return WSASYSCALLFAILURE, true
	case "WSASYSNOTREADY":
		return WSASYSNOTREADY, true
	case "WSASYS_STATUS_LEN":
		return WSASYS_STATUS_LEN, true
	case "WSATRY_AGAIN":
		return WSATRY_AGAIN, true
	case "WSATYPE_NOT_FOUND":
		return WSATYPE_NOT_FOUND, true
	case "WSAVERNOTSUPPORTED":
		return WSAVERNOTSUPPORTED, true
	case "WSA_E_CANCELLED":
		return WSA_E_CANCELLED, true
	case "WSA_E_NO_MORE":
		return WSA_E_NO_MORE, true
	case "WSA_FLAG_ACCESS_SYSTEM_SECURITY":
		return WSA_FLAG_ACCESS_SYSTEM_SECURITY, true
	case "WSA_FLAG_MULTIPOINT_C_LEAF":
		return WSA_FLAG_MULTIPOINT_C_LEAF, true
	case "WSA_FLAG_MULTIPOINT_C_ROOT":
		return WSA_FLAG_MULTIPOINT_C_ROOT, true
	case "WSA_FLAG_MULTIPOINT_D_LEAF":
		return WSA_FLAG_MULTIPOINT_D_LEAF, true
	case "WSA_FLAG_MULTIPOINT_D_ROOT":
		return WSA_FLAG_MULTIPOINT_D_ROOT, true
	case "WSA_FLAG_NO_HANDLE_INHERIT":
		return WSA_FLAG_NO_HANDLE_INHERIT, true
	case "WSA_FLAG_OVERLAPPED":
		return WSA_FLAG_OVERLAPPED, true
	case "WSA_FLAG_REGISTERED_IO":
		return WSA_FLAG_REGISTERED_IO, true
	case "WSA_INFINITE":
		return WSA_INFINITE, true
	case "WSA_INVALID_EVENT":
		return WSA_INVALID_EVENT, true
	case "WSA_INVALID_HANDLE":
		return WSA_INVALID_HANDLE, true
	case "WSA_INVALID_PARAMETER":
		return WSA_INVALID_PARAMETER, true
	case "WSA_IO_INCOMPLETE":
		return WSA_IO_INCOMPLETE, true
	case "WSA_IO_PENDING":
		return WSA_IO_PENDING, true
	case "WSA_IPSEC_NAME_POLICY_ERROR":
		return WSA_IPSEC_NAME_POLICY_ERROR, true
	case "WSA_MAXIMUM_WAIT_EVENTS":
		return WSA_MAXIMUM_WAIT_EVENTS, true
	case "WSA_NOT_ENOUGH_MEMORY":
		return WSA_NOT_ENOUGH_MEMORY, true
	case "WSA_OPERATION_ABORTED":
		return WSA_OPERATION_ABORTED, true
	case "WSA_QOS_ADMISSION_FAILURE":
		return WSA_QOS_ADMISSION_FAILURE, true
	case "WSA_QOS_BAD_OBJECT":
		return WSA_QOS_BAD_OBJECT, true
	case "WSA_QOS_BAD_STYLE":
		return WSA_QOS_BAD_STYLE, true
	case "WSA_QOS_EFILTERCOUNT":
		return WSA_QOS_EFILTERCOUNT, true
	case "WSA_QOS_EFILTERSTYLE":
		return WSA_QOS_EFILTERSTYLE, true
	case "WSA_QOS_EFILTERTYPE":
		return WSA_QOS_EFILTERTYPE, true
	case "WSA_QOS_EFLOWCOUNT":
		return WSA_QOS_EFLOWCOUNT, true
	case "WSA_QOS_EFLOWDESC":
		return WSA_QOS_EFLOWDESC, true
	case "WSA_QOS_EFLOWSPEC":
		return WSA_QOS_EFLOWSPEC, true
	case "WSA_QOS_EOBJLENGTH":
		return WSA_QOS_EOBJLENGTH, true
	case "WSA_QOS_EPOLICYOBJ":
		return WSA_QOS_EPOLICYOBJ, true
	case "WSA_QOS_EPROVSPECBUF":
		return WSA_QOS_EPROVSPECBUF, true
	case "WSA_QOS_EPSFILTERSPEC":
		return WSA_QOS_EPSFILTERSPEC, true
	case "WSA_QOS_EPSFLOWSPEC":
		return WSA_QOS_EPSFLOWSPEC, true
	case "WSA_QOS_ESDMODEOBJ":
		return WSA_QOS_ESDMODEOBJ, true
	case "WSA_QOS_ESERVICETYPE":
		return WSA_QOS_ESERVICETYPE, true
	case "WSA_QOS_ESHAPERATEOBJ":
		return WSA_QOS_ESHAPERATEOBJ, true
	case "WSA_QOS_EUNKOWNPSOBJ":
		return WSA_QOS_EUNKOWNPSOBJ, true
	case "WSA_QOS_GENERIC_ERROR":
		return WSA_QOS_GENERIC_ERROR, true
	case "WSA_QOS_NO_RECEIVERS":
		return WSA_QOS_NO_RECEIVERS, true
	case "WSA_QOS_NO_SENDERS":
		return WSA_QOS_NO_SENDERS, true
	case "WSA_QOS_POLICY_FAILURE":
		return WSA_QOS_POLICY_FAILURE, true
	case "WSA_QOS_RECEIVERS":
		return WSA_QOS_RECEIVERS, true
	case "WSA_QOS_REQUEST_CONFIRMED":
		return WSA_QOS_REQUEST_CONFIRMED, true
	case "WSA_QOS_RESERVED_PETYPE":
		return WSA_QOS_RESERVED_PETYPE, true
	case "WSA_QOS_SENDERS":
		return WSA_QOS_SENDERS, true
	case "WSA_QOS_TRAFFIC_CTRL_ERROR":
		return WSA_QOS_TRAFFIC_CTRL_ERROR, true
	case "WSA_SECURE_HOST_NOT_FOUND":
		return WSA_SECURE_HOST_NOT_FOUND, true
	case "WSA_WAIT_EVENT_0":
		return WSA_WAIT_EVENT_0, true
	case "WSA_WAIT_FAILED":
		return WSA_WAIT_FAILED, true
	case "WSA_WAIT_IO_COMPLETION":
		return WSA_WAIT_IO_COMPLETION, true
	case "WSA_WAIT_TIMEOUT":
		return WSA_WAIT_TIMEOUT, true
	default:
		return Value(0), false
	}
}
