// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.20-preview (43b9a07fb89fb1d43edd6a05855fe88a303bf450b267ec0c4aaf00064dc62bdb).

// Package syncinit provides pointer-sized representations of static Win32 synchronization initializers.
package syncinit

const (
	CONDITION_VARIABLE_INIT uintptr = 0
	INIT_ONCE_STATIC_INIT   uintptr = 0
	SRWLOCK_INIT            uintptr = 0
)
