// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

// Package syncinit provides pointer-sized representations of static Win32 synchronization initializers.
package syncinit

const (
	CONDITION_VARIABLE_INIT uintptr = 0
	INIT_ONCE_STATIC_INIT   uintptr = 0
	SRWLOCK_INIT            uintptr = 0
)
