// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package service

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
)

// ENUM_SERVICE_TYPE projects Windows.Win32.System.Services.ENUM_SERVICE_TYPE.
type ENUM_SERVICE_TYPE uint32

// PSC_NOTIFICATION_REGISTRATION projects Windows.Win32.System.Services.PSC_NOTIFICATION_REGISTRATION.
type PSC_NOTIFICATION_REGISTRATION int

// SC_ACTION projects Windows.Win32.System.Services.SC_ACTION.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-sc_action.
type SC_ACTION struct {
	Type  SC_ACTION_TYPE
	Delay uint32
}

// SC_ACTION_TYPE projects Windows.Win32.System.Services.SC_ACTION_TYPE.
type SC_ACTION_TYPE int32

// SC_HANDLE projects Windows.Win32.System.Services.SC_HANDLE.
type SC_HANDLE uintptr

// SERVICE_DELAYED_AUTO_START_INFO projects Windows.Win32.System.Services.SERVICE_DELAYED_AUTO_START_INFO.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_delayed_auto_start_info.
type SERVICE_DELAYED_AUTO_START_INFO struct {
	FDelayedAutostart foundation.BOOL
}

// SERVICE_ERROR projects Windows.Win32.System.Services.SERVICE_ERROR.
type SERVICE_ERROR uint32

// SERVICE_FAILURE_ACTIONS_FLAG projects Windows.Win32.System.Services.SERVICE_FAILURE_ACTIONS_FLAG.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_failure_actions_flag.
type SERVICE_FAILURE_ACTIONS_FLAG struct {
	FFailureActionsOnNonCrashFailures foundation.BOOL
}

// SERVICE_LAUNCH_PROTECTED_INFO projects Windows.Win32.System.Services.SERVICE_LAUNCH_PROTECTED_INFO.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_launch_protected_info.
type SERVICE_LAUNCH_PROTECTED_INFO struct {
	DwLaunchProtected uint32
}

// SERVICE_PREFERRED_NODE_INFO projects Windows.Win32.System.Services.SERVICE_PREFERRED_NODE_INFO.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_preferred_node_info.
type SERVICE_PREFERRED_NODE_INFO struct {
	UsPreferredNode uint16
	FDelete         foundation.BOOLEAN
}

// SERVICE_PRESHUTDOWN_INFO projects Windows.Win32.System.Services.SERVICE_PRESHUTDOWN_INFO.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_preshutdown_info.
type SERVICE_PRESHUTDOWN_INFO struct {
	DwPreshutdownTimeout uint32
}

// SERVICE_RUNS_IN_PROCESS projects Windows.Win32.System.Services.SERVICE_RUNS_IN_PROCESS.
type SERVICE_RUNS_IN_PROCESS uint32

// SERVICE_SID_INFO projects Windows.Win32.System.Services.SERVICE_SID_INFO.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_sid_info.
type SERVICE_SID_INFO struct {
	DwServiceSidType uint32
}

// SERVICE_START_REASON projects Windows.Win32.System.Services.SERVICE_START_REASON.
type SERVICE_START_REASON struct {
	DwReason uint32
}

// SERVICE_START_TYPE projects Windows.Win32.System.Services.SERVICE_START_TYPE.
type SERVICE_START_TYPE uint32

// SERVICE_STATUS projects Windows.Win32.System.Services.SERVICE_STATUS.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_status.
type SERVICE_STATUS struct {
	DwServiceType             ENUM_SERVICE_TYPE
	DwCurrentState            SERVICE_STATUS_CURRENT_STATE
	DwControlsAccepted        uint32
	DwWin32ExitCode           uint32
	DwServiceSpecificExitCode uint32
	DwCheckPoint              uint32
	DwWaitHint                uint32
}

// SERVICE_STATUS_CURRENT_STATE projects Windows.Win32.System.Services.SERVICE_STATUS_CURRENT_STATE.
type SERVICE_STATUS_CURRENT_STATE uint32

// SERVICE_STATUS_HANDLE projects Windows.Win32.System.Services.SERVICE_STATUS_HANDLE.
type SERVICE_STATUS_HANDLE uintptr

// SERVICE_STATUS_PROCESS projects Windows.Win32.System.Services.SERVICE_STATUS_PROCESS.
// See https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_status_process.
type SERVICE_STATUS_PROCESS struct {
	DwServiceType             ENUM_SERVICE_TYPE
	DwCurrentState            SERVICE_STATUS_CURRENT_STATE
	DwControlsAccepted        uint32
	DwWin32ExitCode           uint32
	DwServiceSpecificExitCode uint32
	DwCheckPoint              uint32
	DwWaitHint                uint32
	DwProcessId               uint32
	DwServiceFlags            SERVICE_RUNS_IN_PROCESS
}

// SERVICE_TRIGGER_ACTION projects Windows.Win32.System.Services.SERVICE_TRIGGER_ACTION.
type SERVICE_TRIGGER_ACTION uint32

// SERVICE_TRIGGER_CUSTOM_STATE_ID projects Windows.Win32.System.Services.SERVICE_TRIGGER_CUSTOM_STATE_ID.
type SERVICE_TRIGGER_CUSTOM_STATE_ID struct {
	Data [2]uint32
}

// SERVICE_TRIGGER_SPECIFIC_DATA_ITEM_DATA_TYPE projects Windows.Win32.System.Services.SERVICE_TRIGGER_SPECIFIC_DATA_ITEM_DATA_TYPE.
type SERVICE_TRIGGER_SPECIFIC_DATA_ITEM_DATA_TYPE uint32

// SERVICE_TRIGGER_TYPE projects Windows.Win32.System.Services.SERVICE_TRIGGER_TYPE.
type SERVICE_TRIGGER_TYPE uint32

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [4]byte                                     = [unsafe.Sizeof(*new(ENUM_SERVICE_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(ENUM_SERVICE_TYPE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(PSC_NOTIFICATION_REGISTRATION))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Alignof(*new(PSC_NOTIFICATION_REGISTRATION))]byte{}
	_ [8]byte                                     = [unsafe.Sizeof(*new(SC_ACTION))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SC_ACTION))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SC_ACTION{}.Type)]byte{}
	_ [4]byte                                     = [unsafe.Offsetof(SC_ACTION{}.Delay)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SC_ACTION_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SC_ACTION_TYPE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(SC_HANDLE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Alignof(*new(SC_HANDLE))]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_DELAYED_AUTO_START_INFO))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_DELAYED_AUTO_START_INFO))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_DELAYED_AUTO_START_INFO{}.FDelayedAutostart)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_ERROR))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_ERROR))]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_FAILURE_ACTIONS_FLAG))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_FAILURE_ACTIONS_FLAG))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_FAILURE_ACTIONS_FLAG{}.FFailureActionsOnNonCrashFailures)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_LAUNCH_PROTECTED_INFO))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_LAUNCH_PROTECTED_INFO))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_LAUNCH_PROTECTED_INFO{}.DwLaunchProtected)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_PREFERRED_NODE_INFO))]byte{}
	_ [2]byte                                     = [unsafe.Alignof(*new(SERVICE_PREFERRED_NODE_INFO))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_PREFERRED_NODE_INFO{}.UsPreferredNode)]byte{}
	_ [2]byte                                     = [unsafe.Offsetof(SERVICE_PREFERRED_NODE_INFO{}.FDelete)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_PRESHUTDOWN_INFO))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_PRESHUTDOWN_INFO))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_PRESHUTDOWN_INFO{}.DwPreshutdownTimeout)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_RUNS_IN_PROCESS))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_RUNS_IN_PROCESS))]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_SID_INFO))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_SID_INFO))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_SID_INFO{}.DwServiceSidType)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_START_REASON))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_START_REASON))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_START_REASON{}.DwReason)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_START_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_START_TYPE))]byte{}
	_ [28]byte                                    = [unsafe.Sizeof(*new(SERVICE_STATUS))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_STATUS))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_STATUS{}.DwServiceType)]byte{}
	_ [4]byte                                     = [unsafe.Offsetof(SERVICE_STATUS{}.DwCurrentState)]byte{}
	_ [8]byte                                     = [unsafe.Offsetof(SERVICE_STATUS{}.DwControlsAccepted)]byte{}
	_ [12]byte                                    = [unsafe.Offsetof(SERVICE_STATUS{}.DwWin32ExitCode)]byte{}
	_ [16]byte                                    = [unsafe.Offsetof(SERVICE_STATUS{}.DwServiceSpecificExitCode)]byte{}
	_ [20]byte                                    = [unsafe.Offsetof(SERVICE_STATUS{}.DwCheckPoint)]byte{}
	_ [24]byte                                    = [unsafe.Offsetof(SERVICE_STATUS{}.DwWaitHint)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_STATUS_CURRENT_STATE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_STATUS_CURRENT_STATE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(SERVICE_STATUS_HANDLE))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Alignof(*new(SERVICE_STATUS_HANDLE))]byte{}
	_ [36]byte                                    = [unsafe.Sizeof(*new(SERVICE_STATUS_PROCESS))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_STATUS_PROCESS))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwServiceType)]byte{}
	_ [4]byte                                     = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwCurrentState)]byte{}
	_ [8]byte                                     = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwControlsAccepted)]byte{}
	_ [12]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwWin32ExitCode)]byte{}
	_ [16]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwServiceSpecificExitCode)]byte{}
	_ [20]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwCheckPoint)]byte{}
	_ [24]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwWaitHint)]byte{}
	_ [28]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwProcessId)]byte{}
	_ [32]byte                                    = [unsafe.Offsetof(SERVICE_STATUS_PROCESS{}.DwServiceFlags)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_TRIGGER_ACTION))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_TRIGGER_ACTION))]byte{}
	_ [8]byte                                     = [unsafe.Sizeof(*new(SERVICE_TRIGGER_CUSTOM_STATE_ID))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_TRIGGER_CUSTOM_STATE_ID))]byte{}
	_ [0]byte                                     = [unsafe.Offsetof(SERVICE_TRIGGER_CUSTOM_STATE_ID{}.Data)]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_TRIGGER_SPECIFIC_DATA_ITEM_DATA_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_TRIGGER_SPECIFIC_DATA_ITEM_DATA_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Sizeof(*new(SERVICE_TRIGGER_TYPE))]byte{}
	_ [4]byte                                     = [unsafe.Alignof(*new(SERVICE_TRIGGER_TYPE))]byte{}
)
