// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package richedit

import (
	"unsafe"

	"github.com/depthbomb/win32defs/controls"
	"github.com/depthbomb/win32defs/foundation"
	"github.com/depthbomb/win32defs/gdi"
	"github.com/depthbomb/win32defs/internal/nativebuffer"
)

// BIDIOPTIONS projects Windows.Win32.UI.Controls.RichEdit.BIDIOPTIONS.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-bidioptions.
type BIDIOPTIONS struct {
	CbSize   uint32
	WMask    uint16
	WEffects uint16
}

// CFE_EFFECTS projects Windows.Win32.UI.Controls.RichEdit.CFE_EFFECTS.
type CFE_EFFECTS uint32

// CFM_MASK projects Windows.Win32.UI.Controls.RichEdit.CFM_MASK.
type CFM_MASK uint32

// CHARFORMATA projects Windows.Win32.UI.Controls.RichEdit.CHARFORMATA.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-charformata.
type CHARFORMATA struct {
	CbSize          uint32
	DwMask          CFM_MASK
	DwEffects       CFE_EFFECTS
	YHeight         int32
	YOffset         int32
	CrTextColor     foundation.COLORREF
	BCharSet        gdi.FONT_CHARSET
	BPitchAndFamily uint8
	SzFaceName      [32]foundation.CHAR
}

// CHARFORMATW projects Windows.Win32.UI.Controls.RichEdit.CHARFORMATW.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-charformatw.
type CHARFORMATW struct {
	CbSize          uint32
	DwMask          CFM_MASK
	DwEffects       CFE_EFFECTS
	YHeight         int32
	YOffset         int32
	CrTextColor     foundation.COLORREF
	BCharSet        gdi.FONT_CHARSET
	BPitchAndFamily uint8
	SzFaceName      [32]uint16
}

// CHARRANGE projects Windows.Win32.UI.Controls.RichEdit.CHARRANGE.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-charrange.
type CHARRANGE struct {
	CpMin int32
	CpMax int32
}

// COMPCOLOR projects Windows.Win32.UI.Controls.RichEdit.COMPCOLOR.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-compcolor.
type COMPCOLOR struct {
	CrText       foundation.COLORREF
	CrBackground foundation.COLORREF
	DwEffects    uint32
}

// GETTEXTLENGTHEX projects Windows.Win32.UI.Controls.RichEdit.GETTEXTLENGTHEX.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-gettextlengthex.
type GETTEXTLENGTHEX struct {
	Flags    GETTEXTLENGTHEX_FLAGS
	Codepage uint32
}

// GETTEXTLENGTHEX_FLAGS projects Windows.Win32.UI.Controls.RichEdit.GETTEXTLENGTHEX_FLAGS.
type GETTEXTLENGTHEX_FLAGS uint32

// GROUPTYPINGCHANGE is a view of native Windows.Win32.UI.Controls.RichEdit.GROUPTYPINGCHANGE storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
type GROUPTYPINGCHANGE struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	GROUPTYPINGCHANGESize               = 16 + (unsafe.Sizeof(uintptr(0))-4)/4*12
	GROUPTYPINGCHANGEAlignment          = 4
	GROUPTYPINGCHANGENmhdrOffset        = 0
	GROUPTYPINGCHANGEFGroupTypingOffset = 12 + (unsafe.Sizeof(uintptr(0))-4)/4*12
)

// NewGROUPTYPINGCHANGE allocates zeroed, aligned native storage.
func NewGROUPTYPINGCHANGE() GROUPTYPINGCHANGE {
	return GROUPTYPINGCHANGE{data: nativebuffer.New(int(GROUPTYPINGCHANGESize), uintptr(GROUPTYPINGCHANGEAlignment))}
}

// ViewGROUPTYPINGCHANGE shares data without copying. It panics if data is shorter than GROUPTYPINGCHANGESize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewGROUPTYPINGCHANGE(data []byte) GROUPTYPINGCHANGE {
	return GROUPTYPINGCHANGE{data: nativebuffer.View(data, int(GROUPTYPINGCHANGESize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b GROUPTYPINGCHANGE) Bytes() []byte {
	return b.data[:GROUPTYPINGCHANGESize:GROUPTYPINGCHANGESize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b GROUPTYPINGCHANGE) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(GROUPTYPINGCHANGEAlignment))
}

// GetNmhdr returns a copy of the native field value.
func (b GROUPTYPINGCHANGE) GetNmhdr() controls.NMHDR {
	offset := uintptr(GROUPTYPINGCHANGENmhdrOffset)

	return nativebuffer.Read[controls.NMHDR](b.Bytes()[offset : offset+(12+(unsafe.Sizeof(uintptr(0))-4)/4*12)])
}

// SetNmhdr copies value into the native field.
func (b GROUPTYPINGCHANGE) SetNmhdr(value controls.NMHDR) {
	offset := uintptr(GROUPTYPINGCHANGENmhdrOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(12+(unsafe.Sizeof(uintptr(0))-4)/4*12)], value)
}

// GetFGroupTyping returns a copy of the native field value.
func (b GROUPTYPINGCHANGE) GetFGroupTyping() foundation.BOOL {
	offset := uintptr(GROUPTYPINGCHANGEFGroupTypingOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFGroupTyping copies value into the native field.
func (b GROUPTYPINGCHANGE) SetFGroupTyping(value foundation.BOOL) {
	offset := uintptr(GROUPTYPINGCHANGEFGroupTypingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// HYPHRESULT projects Windows.Win32.UI.Controls.RichEdit.HYPHRESULT.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-hyphresult.
type HYPHRESULT struct {
	Khyph   KHYPH
	IchHyph int32
	ChHyph  uint16
}

// IMECOMPTEXT projects Windows.Win32.UI.Controls.RichEdit.IMECOMPTEXT.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-imecomptext.
type IMECOMPTEXT struct {
	Cb    int32
	Flags IMECOMPTEXT_FLAGS
}

// IMECOMPTEXT_FLAGS projects Windows.Win32.UI.Controls.RichEdit.IMECOMPTEXT_FLAGS.
type IMECOMPTEXT_FLAGS uint32

// KHYPH projects Windows.Win32.UI.Controls.RichEdit.KHYPH.
// See https://learn.microsoft.com/windows/win32/api/richedit/ne-richedit-khyph.
type KHYPH int32

// PARAFORMAT_MASK projects Windows.Win32.UI.Controls.RichEdit.PARAFORMAT_MASK.
type PARAFORMAT_MASK uint32

// PARAFORMAT_NUMBERING projects Windows.Win32.UI.Controls.RichEdit.PARAFORMAT_NUMBERING.
type PARAFORMAT_NUMBERING uint16

// SETTEXTEX projects Windows.Win32.UI.Controls.RichEdit.SETTEXTEX.
// See https://learn.microsoft.com/windows/win32/api/richedit/ns-richedit-settextex.
type SETTEXTEX struct {
	Flags    uint32
	Codepage uint32
}

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [8]byte  = [unsafe.Sizeof(*new(BIDIOPTIONS))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(BIDIOPTIONS))]byte{}
	_ [0]byte  = [unsafe.Offsetof(BIDIOPTIONS{}.CbSize)]byte{}
	_ [4]byte  = [unsafe.Offsetof(BIDIOPTIONS{}.WMask)]byte{}
	_ [6]byte  = [unsafe.Offsetof(BIDIOPTIONS{}.WEffects)]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(CFE_EFFECTS))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(CFE_EFFECTS))]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(CFM_MASK))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(CFM_MASK))]byte{}
	_ [60]byte = [unsafe.Sizeof(*new(CHARFORMATA))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(CHARFORMATA))]byte{}
	_ [0]byte  = [unsafe.Offsetof(CHARFORMATA{}.CbSize)]byte{}
	_ [4]byte  = [unsafe.Offsetof(CHARFORMATA{}.DwMask)]byte{}
	_ [8]byte  = [unsafe.Offsetof(CHARFORMATA{}.DwEffects)]byte{}
	_ [12]byte = [unsafe.Offsetof(CHARFORMATA{}.YHeight)]byte{}
	_ [16]byte = [unsafe.Offsetof(CHARFORMATA{}.YOffset)]byte{}
	_ [20]byte = [unsafe.Offsetof(CHARFORMATA{}.CrTextColor)]byte{}
	_ [24]byte = [unsafe.Offsetof(CHARFORMATA{}.BCharSet)]byte{}
	_ [25]byte = [unsafe.Offsetof(CHARFORMATA{}.BPitchAndFamily)]byte{}
	_ [26]byte = [unsafe.Offsetof(CHARFORMATA{}.SzFaceName)]byte{}
	_ [92]byte = [unsafe.Sizeof(*new(CHARFORMATW))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(CHARFORMATW))]byte{}
	_ [0]byte  = [unsafe.Offsetof(CHARFORMATW{}.CbSize)]byte{}
	_ [4]byte  = [unsafe.Offsetof(CHARFORMATW{}.DwMask)]byte{}
	_ [8]byte  = [unsafe.Offsetof(CHARFORMATW{}.DwEffects)]byte{}
	_ [12]byte = [unsafe.Offsetof(CHARFORMATW{}.YHeight)]byte{}
	_ [16]byte = [unsafe.Offsetof(CHARFORMATW{}.YOffset)]byte{}
	_ [20]byte = [unsafe.Offsetof(CHARFORMATW{}.CrTextColor)]byte{}
	_ [24]byte = [unsafe.Offsetof(CHARFORMATW{}.BCharSet)]byte{}
	_ [25]byte = [unsafe.Offsetof(CHARFORMATW{}.BPitchAndFamily)]byte{}
	_ [26]byte = [unsafe.Offsetof(CHARFORMATW{}.SzFaceName)]byte{}
	_ [8]byte  = [unsafe.Sizeof(*new(CHARRANGE))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(CHARRANGE))]byte{}
	_ [0]byte  = [unsafe.Offsetof(CHARRANGE{}.CpMin)]byte{}
	_ [4]byte  = [unsafe.Offsetof(CHARRANGE{}.CpMax)]byte{}
	_ [12]byte = [unsafe.Sizeof(*new(COMPCOLOR))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(COMPCOLOR))]byte{}
	_ [0]byte  = [unsafe.Offsetof(COMPCOLOR{}.CrText)]byte{}
	_ [4]byte  = [unsafe.Offsetof(COMPCOLOR{}.CrBackground)]byte{}
	_ [8]byte  = [unsafe.Offsetof(COMPCOLOR{}.DwEffects)]byte{}
	_ [8]byte  = [unsafe.Sizeof(*new(GETTEXTLENGTHEX))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(GETTEXTLENGTHEX))]byte{}
	_ [0]byte  = [unsafe.Offsetof(GETTEXTLENGTHEX{}.Flags)]byte{}
	_ [4]byte  = [unsafe.Offsetof(GETTEXTLENGTHEX{}.Codepage)]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(GETTEXTLENGTHEX_FLAGS))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(GETTEXTLENGTHEX_FLAGS))]byte{}
	_ [12]byte = [unsafe.Sizeof(*new(HYPHRESULT))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(HYPHRESULT))]byte{}
	_ [0]byte  = [unsafe.Offsetof(HYPHRESULT{}.Khyph)]byte{}
	_ [4]byte  = [unsafe.Offsetof(HYPHRESULT{}.IchHyph)]byte{}
	_ [8]byte  = [unsafe.Offsetof(HYPHRESULT{}.ChHyph)]byte{}
	_ [8]byte  = [unsafe.Sizeof(*new(IMECOMPTEXT))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(IMECOMPTEXT))]byte{}
	_ [0]byte  = [unsafe.Offsetof(IMECOMPTEXT{}.Cb)]byte{}
	_ [4]byte  = [unsafe.Offsetof(IMECOMPTEXT{}.Flags)]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(IMECOMPTEXT_FLAGS))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(IMECOMPTEXT_FLAGS))]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(KHYPH))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(KHYPH))]byte{}
	_ [4]byte  = [unsafe.Sizeof(*new(PARAFORMAT_MASK))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(PARAFORMAT_MASK))]byte{}
	_ [2]byte  = [unsafe.Sizeof(*new(PARAFORMAT_NUMBERING))]byte{}
	_ [2]byte  = [unsafe.Alignof(*new(PARAFORMAT_NUMBERING))]byte{}
	_ [8]byte  = [unsafe.Sizeof(*new(SETTEXTEX))]byte{}
	_ [4]byte  = [unsafe.Alignof(*new(SETTEXTEX))]byte{}
	_ [0]byte  = [unsafe.Offsetof(SETTEXTEX{}.Flags)]byte{}
	_ [4]byte  = [unsafe.Offsetof(SETTEXTEX{}.Codepage)]byte{}
)
