// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).
// Documentation: Microsoft.Windows.SDK.Win32Docs 0.1.42-alpha (e83bf398dceb1957d698d24daa8a23f986beedb0109727a0ee99b229a525230b).

// Package access provides common Win32 access masks and standard rights.
package access

// Mask is the common representation used by this package.
type Mask uint32

const (
	ACCESS_SYSTEM_SECURITY             Mask   = 0x01000000
	DELETE                             Mask   = 0x00010000
	GENERIC_ALL                        Mask   = 0x10000000
	GENERIC_CHAIN_CERTTRUST_FUNCTION   string = "GenericChainCertificateTrust"
	GENERIC_CHAIN_FINALPOLICY_FUNCTION string = "GenericChainFinalProv"
	// GENERIC_ENTITY: Used when requesting a list of all entities.
	GENERIC_ENTITY           Mask = 0x00000000
	GENERIC_EXECUTE          Mask = 0x20000000
	GENERIC_READ             Mask = 0x80000000
	GENERIC_WRITE            Mask = 0x40000000
	MAXIMUM_ALLOWED          Mask = 0x02000000
	READ_CONTROL             Mask = 0x00020000
	SPECIFIC_RIGHTS_ALL      Mask = 0x0000FFFF
	STANDARD_RIGHTS_ALL      Mask = 0x001F0000
	STANDARD_RIGHTS_EXECUTE  Mask = 0x00020000
	STANDARD_RIGHTS_READ     Mask = 0x00020000
	STANDARD_RIGHTS_REQUIRED Mask = 0x000F0000
	STANDARD_RIGHTS_WRITE    Mask = 0x00020000
	SYNCHRONIZE              Mask = 0x00100000
	WRITE_DAC                Mask = 0x00040000
	WRITE_OWNER              Mask = 0x00080000
)

// Name returns the canonical symbolic name for value.
func Name(value Mask) (string, bool) {
	switch value {
	case Mask(0x00000000):
		return "GENERIC_ENTITY", true
	case Mask(0x0000FFFF):
		return "SPECIFIC_RIGHTS_ALL", true
	case Mask(0x00010000):
		return "DELETE", true
	case Mask(0x00020000):
		return "READ_CONTROL", true
	case Mask(0x00040000):
		return "WRITE_DAC", true
	case Mask(0x00080000):
		return "WRITE_OWNER", true
	case Mask(0x000F0000):
		return "STANDARD_RIGHTS_REQUIRED", true
	case Mask(0x00100000):
		return "SYNCHRONIZE", true
	case Mask(0x001F0000):
		return "STANDARD_RIGHTS_ALL", true
	case Mask(0x01000000):
		return "ACCESS_SYSTEM_SECURITY", true
	case Mask(0x02000000):
		return "MAXIMUM_ALLOWED", true
	case Mask(0x10000000):
		return "GENERIC_ALL", true
	case Mask(0x20000000):
		return "GENERIC_EXECUTE", true
	case Mask(0x40000000):
		return "GENERIC_WRITE", true
	case Mask(0x80000000):
		return "GENERIC_READ", true
	default:
		return "", false
	}
}

// Names returns every symbolic alias for value in lexical order.
func Names(value Mask) []string {
	switch value {
	case Mask(0x00000000):
		return []string{"GENERIC_ENTITY"}
	case Mask(0x0000FFFF):
		return []string{"SPECIFIC_RIGHTS_ALL"}
	case Mask(0x00010000):
		return []string{"DELETE"}
	case Mask(0x00020000):
		return []string{"READ_CONTROL", "STANDARD_RIGHTS_EXECUTE", "STANDARD_RIGHTS_READ", "STANDARD_RIGHTS_WRITE"}
	case Mask(0x00040000):
		return []string{"WRITE_DAC"}
	case Mask(0x00080000):
		return []string{"WRITE_OWNER"}
	case Mask(0x000F0000):
		return []string{"STANDARD_RIGHTS_REQUIRED"}
	case Mask(0x00100000):
		return []string{"SYNCHRONIZE"}
	case Mask(0x001F0000):
		return []string{"STANDARD_RIGHTS_ALL"}
	case Mask(0x01000000):
		return []string{"ACCESS_SYSTEM_SECURITY"}
	case Mask(0x02000000):
		return []string{"MAXIMUM_ALLOWED"}
	case Mask(0x10000000):
		return []string{"GENERIC_ALL"}
	case Mask(0x20000000):
		return []string{"GENERIC_EXECUTE"}
	case Mask(0x40000000):
		return []string{"GENERIC_WRITE"}
	case Mask(0x80000000):
		return []string{"GENERIC_READ"}
	default:
		return nil
	}
}

// Parse returns the numeric value associated with an exact symbolic name.
func Parse(name string) (Mask, bool) {
	switch name {
	case "ACCESS_SYSTEM_SECURITY":
		return ACCESS_SYSTEM_SECURITY, true
	case "DELETE":
		return DELETE, true
	case "GENERIC_ALL":
		return GENERIC_ALL, true
	case "GENERIC_ENTITY":
		return GENERIC_ENTITY, true
	case "GENERIC_EXECUTE":
		return GENERIC_EXECUTE, true
	case "GENERIC_READ":
		return GENERIC_READ, true
	case "GENERIC_WRITE":
		return GENERIC_WRITE, true
	case "MAXIMUM_ALLOWED":
		return MAXIMUM_ALLOWED, true
	case "READ_CONTROL":
		return READ_CONTROL, true
	case "SPECIFIC_RIGHTS_ALL":
		return SPECIFIC_RIGHTS_ALL, true
	case "STANDARD_RIGHTS_ALL":
		return STANDARD_RIGHTS_ALL, true
	case "STANDARD_RIGHTS_EXECUTE":
		return STANDARD_RIGHTS_EXECUTE, true
	case "STANDARD_RIGHTS_READ":
		return STANDARD_RIGHTS_READ, true
	case "STANDARD_RIGHTS_REQUIRED":
		return STANDARD_RIGHTS_REQUIRED, true
	case "STANDARD_RIGHTS_WRITE":
		return STANDARD_RIGHTS_WRITE, true
	case "SYNCHRONIZE":
		return SYNCHRONIZE, true
	case "WRITE_DAC":
		return WRITE_DAC, true
	case "WRITE_OWNER":
		return WRITE_OWNER, true
	default:
		return Mask(0), false
	}
}
