// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package console

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
	"github.com/depthbomb/win32defs/internal/nativebuffer"
)

// ALLOC_CONSOLE_MODE projects Windows.Win32.System.Console.ALLOC_CONSOLE_MODE.
type ALLOC_CONSOLE_MODE int32

// ALLOC_CONSOLE_OPTIONS projects Windows.Win32.System.Console.ALLOC_CONSOLE_OPTIONS.
type ALLOC_CONSOLE_OPTIONS struct {
	Mode          ALLOC_CONSOLE_MODE
	UseShowWindow foundation.BOOL
	ShowWindow    uint16
}

// APPKEY projects Windows.Win32.System.Console.APPKEY.
type APPKEY struct {
	Modifier uint16
	ScanCode uint16
}

// CONSOLEENDTASK projects Windows.Win32.System.Console.CONSOLEENDTASK.
type CONSOLEENDTASK struct {
	ProcessId        foundation.HANDLE
	Hwnd             foundation.HWND
	ConsoleEventCode uint32
	ConsoleFlags     uint32
}

// CONSOLESETFOREGROUND projects Windows.Win32.System.Console.CONSOLESETFOREGROUND.
type CONSOLESETFOREGROUND struct {
	HProcess    foundation.HANDLE
	BForeground foundation.BOOL
}

// CONSOLEWINDOWOWNER projects Windows.Win32.System.Console.CONSOLEWINDOWOWNER.
type CONSOLEWINDOWOWNER struct {
	Hwnd      foundation.HWND
	ProcessId uint32
	ThreadId  uint32
}

// CONSOLE_CARET_INFO projects Windows.Win32.System.Console.CONSOLE_CARET_INFO.
type CONSOLE_CARET_INFO struct {
	Hwnd foundation.HWND
	Rc   foundation.RECT
}

// CONSOLE_CHARACTER_ATTRIBUTES projects Windows.Win32.System.Console.CONSOLE_CHARACTER_ATTRIBUTES.
type CONSOLE_CHARACTER_ATTRIBUTES uint16

// CONSOLE_CURSOR_INFO projects Windows.Win32.System.Console.CONSOLE_CURSOR_INFO.
// See https://learn.microsoft.com/windows/console/console-cursor-info-str.
type CONSOLE_CURSOR_INFO struct {
	DwSize   uint32
	BVisible foundation.BOOL
}

// CONSOLE_FONT_INFO projects Windows.Win32.System.Console.CONSOLE_FONT_INFO.
// See https://learn.microsoft.com/windows/console/console-font-info-str.
type CONSOLE_FONT_INFO struct {
	NFont      uint32
	DwFontSize COORD
}

// CONSOLE_FONT_INFOEX projects Windows.Win32.System.Console.CONSOLE_FONT_INFOEX.
// See https://learn.microsoft.com/windows/console/console-font-infoex.
type CONSOLE_FONT_INFOEX struct {
	CbSize     uint32
	NFont      uint32
	DwFontSize COORD
	FontFamily uint32
	FontWeight uint32
	FaceName   [32]uint16
}

// CONSOLE_HISTORY_INFO projects Windows.Win32.System.Console.CONSOLE_HISTORY_INFO.
// See https://learn.microsoft.com/windows/console/console-history-info.
type CONSOLE_HISTORY_INFO struct {
	CbSize                 uint32
	HistoryBufferSize      uint32
	NumberOfHistoryBuffers uint32
	DwFlags                uint32
}

// CONSOLE_PROCESS_INFO projects Windows.Win32.System.Console.CONSOLE_PROCESS_INFO.
type CONSOLE_PROCESS_INFO struct {
	DwProcessID uint32
	DwFlags     uint32
}

// CONSOLE_READCONSOLE_CONTROL projects Windows.Win32.System.Console.CONSOLE_READCONSOLE_CONTROL.
// See https://learn.microsoft.com/windows/console/console-readconsole-control.
type CONSOLE_READCONSOLE_CONTROL struct {
	NLength           uint32
	NInitialChars     uint32
	DwCtrlWakeupMask  uint32
	DwControlKeyState uint32
}

// CONSOLE_SCREEN_BUFFER_INFO projects Windows.Win32.System.Console.CONSOLE_SCREEN_BUFFER_INFO.
// See https://learn.microsoft.com/windows/console/console-screen-buffer-info-str.
type CONSOLE_SCREEN_BUFFER_INFO struct {
	DwSize              COORD
	DwCursorPosition    COORD
	WAttributes         CONSOLE_CHARACTER_ATTRIBUTES
	SrWindow            SMALL_RECT
	DwMaximumWindowSize COORD
}

// CONSOLE_SCREEN_BUFFER_INFOEX projects Windows.Win32.System.Console.CONSOLE_SCREEN_BUFFER_INFOEX.
// See https://learn.microsoft.com/windows/console/console-screen-buffer-infoex.
type CONSOLE_SCREEN_BUFFER_INFOEX struct {
	CbSize               uint32
	DwSize               COORD
	DwCursorPosition     COORD
	WAttributes          CONSOLE_CHARACTER_ATTRIBUTES
	SrWindow             SMALL_RECT
	DwMaximumWindowSize  COORD
	WPopupAttributes     uint16
	BFullscreenSupported foundation.BOOL
	ColorTable           [16]foundation.COLORREF
}

// CONSOLE_SELECTION_INFO projects Windows.Win32.System.Console.CONSOLE_SELECTION_INFO.
// See https://learn.microsoft.com/windows/console/console-selection-info-str.
type CONSOLE_SELECTION_INFO struct {
	DwFlags           uint32
	DwSelectionAnchor COORD
	SrSelection       SMALL_RECT
}

// COORD projects Windows.Win32.System.Console.COORD.
// See https://learn.microsoft.com/windows/console/coord-str.
type COORD struct {
	X int16
	Y int16
}

// ExtKeyDef projects Windows.Win32.System.Console.ExtKeyDef.
type ExtKeyDef struct {
	Keys [3]ExtKeySubst
}

// ExtKeyDefBuf is a view of native Windows.Win32.System.Console.ExtKeyDefBuf storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
type ExtKeyDefBuf struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	ExtKeyDefBufSize             = 476
	ExtKeyDefBufAlignment        = 2
	ExtKeyDefBufDwVersionOffset  = 0
	ExtKeyDefBufDwCheckSumOffset = 4
	ExtKeyDefBufTableOffset      = 8
)

// NewExtKeyDefBuf allocates zeroed, aligned native storage.
func NewExtKeyDefBuf() ExtKeyDefBuf {
	return ExtKeyDefBuf{data: nativebuffer.New(int(ExtKeyDefBufSize), uintptr(ExtKeyDefBufAlignment))}
}

// ViewExtKeyDefBuf shares data without copying. It panics if data is shorter than ExtKeyDefBufSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewExtKeyDefBuf(data []byte) ExtKeyDefBuf {
	return ExtKeyDefBuf{data: nativebuffer.View(data, int(ExtKeyDefBufSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b ExtKeyDefBuf) Bytes() []byte {
	return b.data[:ExtKeyDefBufSize:ExtKeyDefBufSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b ExtKeyDefBuf) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(ExtKeyDefBufAlignment))
}

// GetDwVersion returns a copy of the native field value.
func (b ExtKeyDefBuf) GetDwVersion() uint32 {
	offset := uintptr(ExtKeyDefBufDwVersionOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwVersion copies value into the native field.
func (b ExtKeyDefBuf) SetDwVersion(value uint32) {
	offset := uintptr(ExtKeyDefBufDwVersionOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetDwCheckSum returns a copy of the native field value.
func (b ExtKeyDefBuf) GetDwCheckSum() uint32 {
	offset := uintptr(ExtKeyDefBufDwCheckSumOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwCheckSum copies value into the native field.
func (b ExtKeyDefBuf) SetDwCheckSum(value uint32) {
	offset := uintptr(ExtKeyDefBufDwCheckSumOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetTable returns a copy of the native field value.
func (b ExtKeyDefBuf) GetTable(index0 int) ExtKeyDef {
	if index0 < 0 || index0 >= 26 {
		panic("native array index out of range")
	}
	offset := uintptr(ExtKeyDefBufTableOffset + uintptr(index0)*(18))

	return nativebuffer.Read[ExtKeyDef](b.Bytes()[offset : offset+(18)])
}

// SetTable copies value into the native field.
func (b ExtKeyDefBuf) SetTable(index0 int, value ExtKeyDef) {
	if index0 < 0 || index0 >= 26 {
		panic("native array index out of range")
	}
	offset := uintptr(ExtKeyDefBufTableOffset + uintptr(index0)*(18))
	nativebuffer.Write(b.Bytes()[offset:offset+(18)], value)
}

// ExtKeySubst projects Windows.Win32.System.Console.ExtKeySubst.
type ExtKeySubst struct {
	WMod         uint16
	WVirKey      uint16
	WUnicodeChar uint16
}

// FOCUS_EVENT_RECORD projects Windows.Win32.System.Console.FOCUS_EVENT_RECORD.
// See https://learn.microsoft.com/windows/console/focus-event-record-str.
type FOCUS_EVENT_RECORD struct {
	BSetFocus foundation.BOOL
}

// HPCON projects Windows.Win32.System.Console.HPCON.
type HPCON int

// MENU_EVENT_RECORD projects Windows.Win32.System.Console.MENU_EVENT_RECORD.
// See https://learn.microsoft.com/windows/console/menu-event-record-str.
type MENU_EVENT_RECORD struct {
	DwCommandId uint32
}

// MOUSE_EVENT_RECORD projects Windows.Win32.System.Console.MOUSE_EVENT_RECORD.
// See https://learn.microsoft.com/windows/console/mouse-event-record-str.
type MOUSE_EVENT_RECORD struct {
	DwMousePosition   COORD
	DwButtonState     uint32
	DwControlKeyState uint32
	DwEventFlags      uint32
}

// SMALL_RECT projects Windows.Win32.System.Console.SMALL_RECT.
// See https://learn.microsoft.com/windows/console/small-rect-str.
type SMALL_RECT struct {
	Left   int16
	Top    int16
	Right  int16
	Bottom int16
}

// WINDOW_BUFFER_SIZE_RECORD projects Windows.Win32.System.Console.WINDOW_BUFFER_SIZE_RECORD.
// See https://learn.microsoft.com/windows/console/window-buffer-size-record-str.
type WINDOW_BUFFER_SIZE_RECORD struct {
	DwSize COORD
}

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [4]byte                                      = [unsafe.Sizeof(*new(ALLOC_CONSOLE_MODE))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(ALLOC_CONSOLE_MODE))]byte{}
	_ [12]byte                                     = [unsafe.Sizeof(*new(ALLOC_CONSOLE_OPTIONS))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(ALLOC_CONSOLE_OPTIONS))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(ALLOC_CONSOLE_OPTIONS{}.Mode)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(ALLOC_CONSOLE_OPTIONS{}.UseShowWindow)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(ALLOC_CONSOLE_OPTIONS{}.ShowWindow)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(APPKEY))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(APPKEY))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(APPKEY{}.Modifier)]byte{}
	_ [2]byte                                      = [unsafe.Offsetof(APPKEY{}.ScanCode)]byte{}
	_ [16 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte = [unsafe.Sizeof(*new(CONSOLEENDTASK))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(CONSOLEENDTASK))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLEENDTASK{}.ProcessId)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(CONSOLEENDTASK{}.Hwnd)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte  = [unsafe.Offsetof(CONSOLEENDTASK{}.ConsoleEventCode)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte = [unsafe.Offsetof(CONSOLEENDTASK{}.ConsoleFlags)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*8]byte  = [unsafe.Sizeof(*new(CONSOLESETFOREGROUND))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(CONSOLESETFOREGROUND))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLESETFOREGROUND{}.HProcess)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(CONSOLESETFOREGROUND{}.BForeground)]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(CONSOLEWINDOWOWNER))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(CONSOLEWINDOWOWNER))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLEWINDOWOWNER{}.Hwnd)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(CONSOLEWINDOWOWNER{}.ProcessId)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(CONSOLEWINDOWOWNER{}.ThreadId)]byte{}
	_ [20 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(CONSOLE_CARET_INFO))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(CONSOLE_CARET_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_CARET_INFO{}.Hwnd)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(CONSOLE_CARET_INFO{}.Rc)]byte{}
	_ [2]byte                                      = [unsafe.Sizeof(*new(CONSOLE_CHARACTER_ATTRIBUTES))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(CONSOLE_CHARACTER_ATTRIBUTES))]byte{}
	_ [8]byte                                      = [unsafe.Sizeof(*new(CONSOLE_CURSOR_INFO))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_CURSOR_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_CURSOR_INFO{}.DwSize)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_CURSOR_INFO{}.BVisible)]byte{}
	_ [8]byte                                      = [unsafe.Sizeof(*new(CONSOLE_FONT_INFO))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_FONT_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_FONT_INFO{}.NFont)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_FONT_INFO{}.DwFontSize)]byte{}
	_ [84]byte                                     = [unsafe.Sizeof(*new(CONSOLE_FONT_INFOEX))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_FONT_INFOEX))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.CbSize)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.NFont)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.DwFontSize)]byte{}
	_ [12]byte                                     = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.FontFamily)]byte{}
	_ [16]byte                                     = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.FontWeight)]byte{}
	_ [20]byte                                     = [unsafe.Offsetof(CONSOLE_FONT_INFOEX{}.FaceName)]byte{}
	_ [16]byte                                     = [unsafe.Sizeof(*new(CONSOLE_HISTORY_INFO))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_HISTORY_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_HISTORY_INFO{}.CbSize)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_HISTORY_INFO{}.HistoryBufferSize)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_HISTORY_INFO{}.NumberOfHistoryBuffers)]byte{}
	_ [12]byte                                     = [unsafe.Offsetof(CONSOLE_HISTORY_INFO{}.DwFlags)]byte{}
	_ [8]byte                                      = [unsafe.Sizeof(*new(CONSOLE_PROCESS_INFO))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_PROCESS_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_PROCESS_INFO{}.DwProcessID)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_PROCESS_INFO{}.DwFlags)]byte{}
	_ [16]byte                                     = [unsafe.Sizeof(*new(CONSOLE_READCONSOLE_CONTROL))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_READCONSOLE_CONTROL))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_READCONSOLE_CONTROL{}.NLength)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_READCONSOLE_CONTROL{}.NInitialChars)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_READCONSOLE_CONTROL{}.DwCtrlWakeupMask)]byte{}
	_ [12]byte                                     = [unsafe.Offsetof(CONSOLE_READCONSOLE_CONTROL{}.DwControlKeyState)]byte{}
	_ [22]byte                                     = [unsafe.Sizeof(*new(CONSOLE_SCREEN_BUFFER_INFO))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(CONSOLE_SCREEN_BUFFER_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFO{}.DwSize)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFO{}.DwCursorPosition)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFO{}.WAttributes)]byte{}
	_ [10]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFO{}.SrWindow)]byte{}
	_ [18]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFO{}.DwMaximumWindowSize)]byte{}
	_ [96]byte                                     = [unsafe.Sizeof(*new(CONSOLE_SCREEN_BUFFER_INFOEX))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_SCREEN_BUFFER_INFOEX))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.CbSize)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.DwSize)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.DwCursorPosition)]byte{}
	_ [12]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.WAttributes)]byte{}
	_ [14]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.SrWindow)]byte{}
	_ [22]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.DwMaximumWindowSize)]byte{}
	_ [26]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.WPopupAttributes)]byte{}
	_ [28]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.BFullscreenSupported)]byte{}
	_ [32]byte                                     = [unsafe.Offsetof(CONSOLE_SCREEN_BUFFER_INFOEX{}.ColorTable)]byte{}
	_ [16]byte                                     = [unsafe.Sizeof(*new(CONSOLE_SELECTION_INFO))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(CONSOLE_SELECTION_INFO))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(CONSOLE_SELECTION_INFO{}.DwFlags)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(CONSOLE_SELECTION_INFO{}.DwSelectionAnchor)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(CONSOLE_SELECTION_INFO{}.SrSelection)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(COORD))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(COORD))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(COORD{}.X)]byte{}
	_ [2]byte                                      = [unsafe.Offsetof(COORD{}.Y)]byte{}
	_ [18]byte                                     = [unsafe.Sizeof(*new(ExtKeyDef))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(ExtKeyDef))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(ExtKeyDef{}.Keys)]byte{}
	_ [6]byte                                      = [unsafe.Sizeof(*new(ExtKeySubst))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(ExtKeySubst))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(ExtKeySubst{}.WMod)]byte{}
	_ [2]byte                                      = [unsafe.Offsetof(ExtKeySubst{}.WVirKey)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(ExtKeySubst{}.WUnicodeChar)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(FOCUS_EVENT_RECORD))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(FOCUS_EVENT_RECORD))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(FOCUS_EVENT_RECORD{}.BSetFocus)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Sizeof(*new(HPCON))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(HPCON))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(MENU_EVENT_RECORD))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(MENU_EVENT_RECORD))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(MENU_EVENT_RECORD{}.DwCommandId)]byte{}
	_ [16]byte                                     = [unsafe.Sizeof(*new(MOUSE_EVENT_RECORD))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(MOUSE_EVENT_RECORD))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(MOUSE_EVENT_RECORD{}.DwMousePosition)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(MOUSE_EVENT_RECORD{}.DwButtonState)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(MOUSE_EVENT_RECORD{}.DwControlKeyState)]byte{}
	_ [12]byte                                     = [unsafe.Offsetof(MOUSE_EVENT_RECORD{}.DwEventFlags)]byte{}
	_ [8]byte                                      = [unsafe.Sizeof(*new(SMALL_RECT))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(SMALL_RECT))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(SMALL_RECT{}.Left)]byte{}
	_ [2]byte                                      = [unsafe.Offsetof(SMALL_RECT{}.Top)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(SMALL_RECT{}.Right)]byte{}
	_ [6]byte                                      = [unsafe.Offsetof(SMALL_RECT{}.Bottom)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(WINDOW_BUFFER_SIZE_RECORD))]byte{}
	_ [2]byte                                      = [unsafe.Alignof(*new(WINDOW_BUFFER_SIZE_RECORD))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(WINDOW_BUFFER_SIZE_RECORD{}.DwSize)]byte{}
)
