// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package dwm

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
	"github.com/depthbomb/win32defs/gdi"
	"github.com/depthbomb/win32defs/internal/nativebuffer"
)

// DWM_BLURBEHIND is a view of native Windows.Win32.Graphics.Dwm.DWM_BLURBEHIND storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ns-dwmapi-dwm_blurbehind.
type DWM_BLURBEHIND struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	DWM_BLURBEHINDSize                         = 16 + (unsafe.Sizeof(uintptr(0))-4)/4*4
	DWM_BLURBEHINDAlignment                    = 1
	DWM_BLURBEHINDDwFlagsOffset                = 0
	DWM_BLURBEHINDFEnableOffset                = 4
	DWM_BLURBEHINDHRgnBlurOffset               = 8
	DWM_BLURBEHINDFTransitionOnMaximizedOffset = 12 + (unsafe.Sizeof(uintptr(0))-4)/4*4
)

// NewDWM_BLURBEHIND allocates zeroed, aligned native storage.
func NewDWM_BLURBEHIND() DWM_BLURBEHIND {
	return DWM_BLURBEHIND{data: nativebuffer.New(int(DWM_BLURBEHINDSize), uintptr(DWM_BLURBEHINDAlignment))}
}

// ViewDWM_BLURBEHIND shares data without copying. It panics if data is shorter than DWM_BLURBEHINDSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewDWM_BLURBEHIND(data []byte) DWM_BLURBEHIND {
	return DWM_BLURBEHIND{data: nativebuffer.View(data, int(DWM_BLURBEHINDSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b DWM_BLURBEHIND) Bytes() []byte {
	return b.data[:DWM_BLURBEHINDSize:DWM_BLURBEHINDSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b DWM_BLURBEHIND) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(DWM_BLURBEHINDAlignment))
}

// GetDwFlags returns a copy of the native field value.
func (b DWM_BLURBEHIND) GetDwFlags() uint32 {
	offset := uintptr(DWM_BLURBEHINDDwFlagsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwFlags copies value into the native field.
func (b DWM_BLURBEHIND) SetDwFlags(value uint32) {
	offset := uintptr(DWM_BLURBEHINDDwFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetFEnable returns a copy of the native field value.
func (b DWM_BLURBEHIND) GetFEnable() foundation.BOOL {
	offset := uintptr(DWM_BLURBEHINDFEnableOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFEnable copies value into the native field.
func (b DWM_BLURBEHIND) SetFEnable(value foundation.BOOL) {
	offset := uintptr(DWM_BLURBEHINDFEnableOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetHRgnBlur returns a copy of the native field value.
func (b DWM_BLURBEHIND) GetHRgnBlur() gdi.HRGN {
	offset := uintptr(DWM_BLURBEHINDHRgnBlurOffset)

	return nativebuffer.Read[gdi.HRGN](b.Bytes()[offset : offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)])
}

// SetHRgnBlur copies value into the native field.
func (b DWM_BLURBEHIND) SetHRgnBlur(value gdi.HRGN) {
	offset := uintptr(DWM_BLURBEHINDHRgnBlurOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4+(unsafe.Sizeof(uintptr(0))-4)/4*4)], value)
}

// GetFTransitionOnMaximized returns a copy of the native field value.
func (b DWM_BLURBEHIND) GetFTransitionOnMaximized() foundation.BOOL {
	offset := uintptr(DWM_BLURBEHINDFTransitionOnMaximizedOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFTransitionOnMaximized copies value into the native field.
func (b DWM_BLURBEHIND) SetFTransitionOnMaximized(value foundation.BOOL) {
	offset := uintptr(DWM_BLURBEHINDFTransitionOnMaximizedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// DWM_PRESENT_PARAMETERS is a view of native Windows.Win32.Graphics.Dwm.DWM_PRESENT_PARAMETERS storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ns-dwmapi-dwm_present_parameters.
type DWM_PRESENT_PARAMETERS struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	DWM_PRESENT_PARAMETERSSize                     = 40
	DWM_PRESENT_PARAMETERSAlignment                = 1
	DWM_PRESENT_PARAMETERSCbSizeOffset             = 0
	DWM_PRESENT_PARAMETERSFQueueOffset             = 4
	DWM_PRESENT_PARAMETERSCRefreshStartOffset      = 8
	DWM_PRESENT_PARAMETERSCBufferOffset            = 16
	DWM_PRESENT_PARAMETERSFUseSourceRateOffset     = 20
	DWM_PRESENT_PARAMETERSRateSourceOffset         = 24
	DWM_PRESENT_PARAMETERSCRefreshesPerFrameOffset = 32
	DWM_PRESENT_PARAMETERSESamplingOffset          = 36
)

// NewDWM_PRESENT_PARAMETERS allocates zeroed, aligned native storage.
func NewDWM_PRESENT_PARAMETERS() DWM_PRESENT_PARAMETERS {
	return DWM_PRESENT_PARAMETERS{data: nativebuffer.New(int(DWM_PRESENT_PARAMETERSSize), uintptr(DWM_PRESENT_PARAMETERSAlignment))}
}

// ViewDWM_PRESENT_PARAMETERS shares data without copying. It panics if data is shorter than DWM_PRESENT_PARAMETERSSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewDWM_PRESENT_PARAMETERS(data []byte) DWM_PRESENT_PARAMETERS {
	return DWM_PRESENT_PARAMETERS{data: nativebuffer.View(data, int(DWM_PRESENT_PARAMETERSSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b DWM_PRESENT_PARAMETERS) Bytes() []byte {
	return b.data[:DWM_PRESENT_PARAMETERSSize:DWM_PRESENT_PARAMETERSSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b DWM_PRESENT_PARAMETERS) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(DWM_PRESENT_PARAMETERSAlignment))
}

// GetCbSize returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetCbSize() uint32 {
	offset := uintptr(DWM_PRESENT_PARAMETERSCbSizeOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCbSize copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetCbSize(value uint32) {
	offset := uintptr(DWM_PRESENT_PARAMETERSCbSizeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetFQueue returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetFQueue() foundation.BOOL {
	offset := uintptr(DWM_PRESENT_PARAMETERSFQueueOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFQueue copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetFQueue(value foundation.BOOL) {
	offset := uintptr(DWM_PRESENT_PARAMETERSFQueueOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCRefreshStart returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetCRefreshStart() uint64 {
	offset := uintptr(DWM_PRESENT_PARAMETERSCRefreshStartOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshStart copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetCRefreshStart(value uint64) {
	offset := uintptr(DWM_PRESENT_PARAMETERSCRefreshStartOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCBuffer returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetCBuffer() uint32 {
	offset := uintptr(DWM_PRESENT_PARAMETERSCBufferOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCBuffer copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetCBuffer(value uint32) {
	offset := uintptr(DWM_PRESENT_PARAMETERSCBufferOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetFUseSourceRate returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetFUseSourceRate() foundation.BOOL {
	offset := uintptr(DWM_PRESENT_PARAMETERSFUseSourceRateOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFUseSourceRate copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetFUseSourceRate(value foundation.BOOL) {
	offset := uintptr(DWM_PRESENT_PARAMETERSFUseSourceRateOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetRateSource returns a view sharing this buffer's storage.
func (b DWM_PRESENT_PARAMETERS) GetRateSource() UNSIGNED_RATIO {
	offset := uintptr(DWM_PRESENT_PARAMETERSRateSourceOffset)

	return ViewUNSIGNED_RATIO(b.Bytes()[offset : offset+(8)])
}

// SetRateSource copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetRateSource(value UNSIGNED_RATIO) {
	offset := uintptr(DWM_PRESENT_PARAMETERSRateSourceOffset)
	copy(b.Bytes()[offset:offset+(8)], value.Bytes())
}

// GetCRefreshesPerFrame returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetCRefreshesPerFrame() uint32 {
	offset := uintptr(DWM_PRESENT_PARAMETERSCRefreshesPerFrameOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCRefreshesPerFrame copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetCRefreshesPerFrame(value uint32) {
	offset := uintptr(DWM_PRESENT_PARAMETERSCRefreshesPerFrameOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetESampling returns a copy of the native field value.
func (b DWM_PRESENT_PARAMETERS) GetESampling() DWM_SOURCE_FRAME_SAMPLING {
	offset := uintptr(DWM_PRESENT_PARAMETERSESamplingOffset)

	return nativebuffer.Read[DWM_SOURCE_FRAME_SAMPLING](b.Bytes()[offset : offset+(4)])
}

// SetESampling copies value into the native field.
func (b DWM_PRESENT_PARAMETERS) SetESampling(value DWM_SOURCE_FRAME_SAMPLING) {
	offset := uintptr(DWM_PRESENT_PARAMETERSESamplingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// DWM_SOURCE_FRAME_SAMPLING projects Windows.Win32.Graphics.Dwm.DWM_SOURCE_FRAME_SAMPLING.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwm_source_frame_sampling.
type DWM_SOURCE_FRAME_SAMPLING int32

// DWM_THUMBNAIL_PROPERTIES is a view of native Windows.Win32.Graphics.Dwm.DWM_THUMBNAIL_PROPERTIES storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ns-dwmapi-dwm_thumbnail_properties.
type DWM_THUMBNAIL_PROPERTIES struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	DWM_THUMBNAIL_PROPERTIESSize                        = 45
	DWM_THUMBNAIL_PROPERTIESAlignment                   = 1
	DWM_THUMBNAIL_PROPERTIESDwFlagsOffset               = 0
	DWM_THUMBNAIL_PROPERTIESRcDestinationOffset         = 4
	DWM_THUMBNAIL_PROPERTIESRcSourceOffset              = 20
	DWM_THUMBNAIL_PROPERTIESOpacityOffset               = 36
	DWM_THUMBNAIL_PROPERTIESFVisibleOffset              = 37
	DWM_THUMBNAIL_PROPERTIESFSourceClientAreaOnlyOffset = 41
)

// NewDWM_THUMBNAIL_PROPERTIES allocates zeroed, aligned native storage.
func NewDWM_THUMBNAIL_PROPERTIES() DWM_THUMBNAIL_PROPERTIES {
	return DWM_THUMBNAIL_PROPERTIES{data: nativebuffer.New(int(DWM_THUMBNAIL_PROPERTIESSize), uintptr(DWM_THUMBNAIL_PROPERTIESAlignment))}
}

// ViewDWM_THUMBNAIL_PROPERTIES shares data without copying. It panics if data is shorter than DWM_THUMBNAIL_PROPERTIESSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewDWM_THUMBNAIL_PROPERTIES(data []byte) DWM_THUMBNAIL_PROPERTIES {
	return DWM_THUMBNAIL_PROPERTIES{data: nativebuffer.View(data, int(DWM_THUMBNAIL_PROPERTIESSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b DWM_THUMBNAIL_PROPERTIES) Bytes() []byte {
	return b.data[:DWM_THUMBNAIL_PROPERTIESSize:DWM_THUMBNAIL_PROPERTIESSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b DWM_THUMBNAIL_PROPERTIES) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(DWM_THUMBNAIL_PROPERTIESAlignment))
}

// GetDwFlags returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetDwFlags() uint32 {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESDwFlagsOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetDwFlags copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetDwFlags(value uint32) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESDwFlagsOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetRcDestination returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetRcDestination() foundation.RECT {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESRcDestinationOffset)

	return nativebuffer.Read[foundation.RECT](b.Bytes()[offset : offset+(16)])
}

// SetRcDestination copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetRcDestination(value foundation.RECT) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESRcDestinationOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(16)], value)
}

// GetRcSource returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetRcSource() foundation.RECT {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESRcSourceOffset)

	return nativebuffer.Read[foundation.RECT](b.Bytes()[offset : offset+(16)])
}

// SetRcSource copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetRcSource(value foundation.RECT) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESRcSourceOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(16)], value)
}

// GetOpacity returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetOpacity() uint8 {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESOpacityOffset)

	return nativebuffer.Read[uint8](b.Bytes()[offset : offset+(1)])
}

// SetOpacity copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetOpacity(value uint8) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESOpacityOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(1)], value)
}

// GetFVisible returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetFVisible() foundation.BOOL {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESFVisibleOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFVisible copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetFVisible(value foundation.BOOL) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESFVisibleOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetFSourceClientAreaOnly returns a copy of the native field value.
func (b DWM_THUMBNAIL_PROPERTIES) GetFSourceClientAreaOnly() foundation.BOOL {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESFSourceClientAreaOnlyOffset)

	return nativebuffer.Read[foundation.BOOL](b.Bytes()[offset : offset+(4)])
}

// SetFSourceClientAreaOnly copies value into the native field.
func (b DWM_THUMBNAIL_PROPERTIES) SetFSourceClientAreaOnly(value foundation.BOOL) {
	offset := uintptr(DWM_THUMBNAIL_PROPERTIESFSourceClientAreaOnlyOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// DWM_TIMING_INFO is a view of native Windows.Win32.Graphics.Dwm.DWM_TIMING_INFO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ns-dwmapi-dwm_timing_info.
type DWM_TIMING_INFO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	DWM_TIMING_INFOSize                         = 292
	DWM_TIMING_INFOAlignment                    = 1
	DWM_TIMING_INFOCbSizeOffset                 = 0
	DWM_TIMING_INFORateRefreshOffset            = 4
	DWM_TIMING_INFOQpcRefreshPeriodOffset       = 12
	DWM_TIMING_INFORateComposeOffset            = 20
	DWM_TIMING_INFOQpcVBlankOffset              = 28
	DWM_TIMING_INFOCRefreshOffset               = 36
	DWM_TIMING_INFOCDXRefreshOffset             = 44
	DWM_TIMING_INFOQpcComposeOffset             = 48
	DWM_TIMING_INFOCFrameOffset                 = 56
	DWM_TIMING_INFOCDXPresentOffset             = 64
	DWM_TIMING_INFOCRefreshFrameOffset          = 68
	DWM_TIMING_INFOCFrameSubmittedOffset        = 76
	DWM_TIMING_INFOCDXPresentSubmittedOffset    = 84
	DWM_TIMING_INFOCFrameConfirmedOffset        = 88
	DWM_TIMING_INFOCDXPresentConfirmedOffset    = 96
	DWM_TIMING_INFOCRefreshConfirmedOffset      = 100
	DWM_TIMING_INFOCDXRefreshConfirmedOffset    = 108
	DWM_TIMING_INFOCFramesLateOffset            = 112
	DWM_TIMING_INFOCFramesOutstandingOffset     = 120
	DWM_TIMING_INFOCFrameDisplayedOffset        = 124
	DWM_TIMING_INFOQpcFrameDisplayedOffset      = 132
	DWM_TIMING_INFOCRefreshFrameDisplayedOffset = 140
	DWM_TIMING_INFOCFrameCompleteOffset         = 148
	DWM_TIMING_INFOQpcFrameCompleteOffset       = 156
	DWM_TIMING_INFOCFramePendingOffset          = 164
	DWM_TIMING_INFOQpcFramePendingOffset        = 172
	DWM_TIMING_INFOCFramesDisplayedOffset       = 180
	DWM_TIMING_INFOCFramesCompleteOffset        = 188
	DWM_TIMING_INFOCFramesPendingOffset         = 196
	DWM_TIMING_INFOCFramesAvailableOffset       = 204
	DWM_TIMING_INFOCFramesDroppedOffset         = 212
	DWM_TIMING_INFOCFramesMissedOffset          = 220
	DWM_TIMING_INFOCRefreshNextDisplayedOffset  = 228
	DWM_TIMING_INFOCRefreshNextPresentedOffset  = 236
	DWM_TIMING_INFOCRefreshesDisplayedOffset    = 244
	DWM_TIMING_INFOCRefreshesPresentedOffset    = 252
	DWM_TIMING_INFOCRefreshStartedOffset        = 260
	DWM_TIMING_INFOCPixelsReceivedOffset        = 268
	DWM_TIMING_INFOCPixelsDrawnOffset           = 276
	DWM_TIMING_INFOCBuffersEmptyOffset          = 284
)

// NewDWM_TIMING_INFO allocates zeroed, aligned native storage.
func NewDWM_TIMING_INFO() DWM_TIMING_INFO {
	return DWM_TIMING_INFO{data: nativebuffer.New(int(DWM_TIMING_INFOSize), uintptr(DWM_TIMING_INFOAlignment))}
}

// ViewDWM_TIMING_INFO shares data without copying. It panics if data is shorter than DWM_TIMING_INFOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewDWM_TIMING_INFO(data []byte) DWM_TIMING_INFO {
	return DWM_TIMING_INFO{data: nativebuffer.View(data, int(DWM_TIMING_INFOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b DWM_TIMING_INFO) Bytes() []byte {
	return b.data[:DWM_TIMING_INFOSize:DWM_TIMING_INFOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b DWM_TIMING_INFO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(DWM_TIMING_INFOAlignment))
}

// GetCbSize returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCbSize() uint32 {
	offset := uintptr(DWM_TIMING_INFOCbSizeOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCbSize copies value into the native field.
func (b DWM_TIMING_INFO) SetCbSize(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCbSizeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetRateRefresh returns a view sharing this buffer's storage.
func (b DWM_TIMING_INFO) GetRateRefresh() UNSIGNED_RATIO {
	offset := uintptr(DWM_TIMING_INFORateRefreshOffset)

	return ViewUNSIGNED_RATIO(b.Bytes()[offset : offset+(8)])
}

// SetRateRefresh copies value into the native field.
func (b DWM_TIMING_INFO) SetRateRefresh(value UNSIGNED_RATIO) {
	offset := uintptr(DWM_TIMING_INFORateRefreshOffset)
	copy(b.Bytes()[offset:offset+(8)], value.Bytes())
}

// GetQpcRefreshPeriod returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcRefreshPeriod() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcRefreshPeriodOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcRefreshPeriod copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcRefreshPeriod(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcRefreshPeriodOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetRateCompose returns a view sharing this buffer's storage.
func (b DWM_TIMING_INFO) GetRateCompose() UNSIGNED_RATIO {
	offset := uintptr(DWM_TIMING_INFORateComposeOffset)

	return ViewUNSIGNED_RATIO(b.Bytes()[offset : offset+(8)])
}

// SetRateCompose copies value into the native field.
func (b DWM_TIMING_INFO) SetRateCompose(value UNSIGNED_RATIO) {
	offset := uintptr(DWM_TIMING_INFORateComposeOffset)
	copy(b.Bytes()[offset:offset+(8)], value.Bytes())
}

// GetQpcVBlank returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcVBlank() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcVBlankOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcVBlank copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcVBlank(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcVBlankOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefresh returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefresh() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefresh copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefresh(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCDXRefresh returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCDXRefresh() uint32 {
	offset := uintptr(DWM_TIMING_INFOCDXRefreshOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCDXRefresh copies value into the native field.
func (b DWM_TIMING_INFO) SetCDXRefresh(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCDXRefreshOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetQpcCompose returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcCompose() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcComposeOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcCompose copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcCompose(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcComposeOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFrame returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFrame() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFrameOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFrame copies value into the native field.
func (b DWM_TIMING_INFO) SetCFrame(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFrameOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCDXPresent returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCDXPresent() uint32 {
	offset := uintptr(DWM_TIMING_INFOCDXPresentOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCDXPresent copies value into the native field.
func (b DWM_TIMING_INFO) SetCDXPresent(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCDXPresentOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCRefreshFrame returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshFrame() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshFrameOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshFrame copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshFrame(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshFrameOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFrameSubmitted returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFrameSubmitted() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFrameSubmittedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFrameSubmitted copies value into the native field.
func (b DWM_TIMING_INFO) SetCFrameSubmitted(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFrameSubmittedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCDXPresentSubmitted returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCDXPresentSubmitted() uint32 {
	offset := uintptr(DWM_TIMING_INFOCDXPresentSubmittedOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCDXPresentSubmitted copies value into the native field.
func (b DWM_TIMING_INFO) SetCDXPresentSubmitted(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCDXPresentSubmittedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCFrameConfirmed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFrameConfirmed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFrameConfirmedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFrameConfirmed copies value into the native field.
func (b DWM_TIMING_INFO) SetCFrameConfirmed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFrameConfirmedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCDXPresentConfirmed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCDXPresentConfirmed() uint32 {
	offset := uintptr(DWM_TIMING_INFOCDXPresentConfirmedOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCDXPresentConfirmed copies value into the native field.
func (b DWM_TIMING_INFO) SetCDXPresentConfirmed(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCDXPresentConfirmedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCRefreshConfirmed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshConfirmed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshConfirmedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshConfirmed copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshConfirmed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshConfirmedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCDXRefreshConfirmed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCDXRefreshConfirmed() uint32 {
	offset := uintptr(DWM_TIMING_INFOCDXRefreshConfirmedOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCDXRefreshConfirmed copies value into the native field.
func (b DWM_TIMING_INFO) SetCDXRefreshConfirmed(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCDXRefreshConfirmedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCFramesLate returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesLate() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesLateOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesLate copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesLate(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesLateOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesOutstanding returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesOutstanding() uint32 {
	offset := uintptr(DWM_TIMING_INFOCFramesOutstandingOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetCFramesOutstanding copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesOutstanding(value uint32) {
	offset := uintptr(DWM_TIMING_INFOCFramesOutstandingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetCFrameDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFrameDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFrameDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFrameDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetCFrameDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFrameDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetQpcFrameDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcFrameDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcFrameDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcFrameDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcFrameDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcFrameDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshFrameDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshFrameDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshFrameDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshFrameDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshFrameDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshFrameDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFrameComplete returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFrameComplete() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFrameCompleteOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFrameComplete copies value into the native field.
func (b DWM_TIMING_INFO) SetCFrameComplete(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFrameCompleteOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetQpcFrameComplete returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcFrameComplete() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcFrameCompleteOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcFrameComplete copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcFrameComplete(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcFrameCompleteOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramePending returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramePending() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramePendingOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramePending copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramePending(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramePendingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetQpcFramePending returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetQpcFramePending() uint64 {
	offset := uintptr(DWM_TIMING_INFOQpcFramePendingOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetQpcFramePending copies value into the native field.
func (b DWM_TIMING_INFO) SetQpcFramePending(value uint64) {
	offset := uintptr(DWM_TIMING_INFOQpcFramePendingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesComplete returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesComplete() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesCompleteOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesComplete copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesComplete(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesCompleteOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesPending returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesPending() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesPendingOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesPending copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesPending(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesPendingOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesAvailable returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesAvailable() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesAvailableOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesAvailable copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesAvailable(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesAvailableOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesDropped returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesDropped() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesDroppedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesDropped copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesDropped(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesDroppedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCFramesMissed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCFramesMissed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCFramesMissedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCFramesMissed copies value into the native field.
func (b DWM_TIMING_INFO) SetCFramesMissed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCFramesMissedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshNextDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshNextDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshNextDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshNextDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshNextDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshNextDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshNextPresented returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshNextPresented() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshNextPresentedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshNextPresented copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshNextPresented(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshNextPresentedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshesDisplayed returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshesDisplayed() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshesDisplayedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshesDisplayed copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshesDisplayed(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshesDisplayedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshesPresented returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshesPresented() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshesPresentedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshesPresented copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshesPresented(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshesPresentedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCRefreshStarted returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCRefreshStarted() uint64 {
	offset := uintptr(DWM_TIMING_INFOCRefreshStartedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCRefreshStarted copies value into the native field.
func (b DWM_TIMING_INFO) SetCRefreshStarted(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCRefreshStartedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCPixelsReceived returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCPixelsReceived() uint64 {
	offset := uintptr(DWM_TIMING_INFOCPixelsReceivedOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCPixelsReceived copies value into the native field.
func (b DWM_TIMING_INFO) SetCPixelsReceived(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCPixelsReceivedOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCPixelsDrawn returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCPixelsDrawn() uint64 {
	offset := uintptr(DWM_TIMING_INFOCPixelsDrawnOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCPixelsDrawn copies value into the native field.
func (b DWM_TIMING_INFO) SetCPixelsDrawn(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCPixelsDrawnOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetCBuffersEmpty returns a copy of the native field value.
func (b DWM_TIMING_INFO) GetCBuffersEmpty() uint64 {
	offset := uintptr(DWM_TIMING_INFOCBuffersEmptyOffset)

	return nativebuffer.Read[uint64](b.Bytes()[offset : offset+(8)])
}

// SetCBuffersEmpty copies value into the native field.
func (b DWM_TIMING_INFO) SetCBuffersEmpty(value uint64) {
	offset := uintptr(DWM_TIMING_INFOCBuffersEmptyOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// MilMatrix3x2D is a view of native Windows.Win32.Graphics.Dwm.MilMatrix3x2D storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/mileffects/ns-mileffects-milmatrix3x2d.
type MilMatrix3x2D struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	MilMatrix3x2DSize       = 48
	MilMatrix3x2DAlignment  = 1
	MilMatrix3x2DS_11Offset = 0
	MilMatrix3x2DS_12Offset = 8
	MilMatrix3x2DS_21Offset = 16
	MilMatrix3x2DS_22Offset = 24
	MilMatrix3x2DDXOffset   = 32
	MilMatrix3x2DDYOffset   = 40
)

// NewMilMatrix3x2D allocates zeroed, aligned native storage.
func NewMilMatrix3x2D() MilMatrix3x2D {
	return MilMatrix3x2D{data: nativebuffer.New(int(MilMatrix3x2DSize), uintptr(MilMatrix3x2DAlignment))}
}

// ViewMilMatrix3x2D shares data without copying. It panics if data is shorter than MilMatrix3x2DSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewMilMatrix3x2D(data []byte) MilMatrix3x2D {
	return MilMatrix3x2D{data: nativebuffer.View(data, int(MilMatrix3x2DSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b MilMatrix3x2D) Bytes() []byte {
	return b.data[:MilMatrix3x2DSize:MilMatrix3x2DSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b MilMatrix3x2D) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(MilMatrix3x2DAlignment))
}

// GetS_11 returns a copy of the native field value.
func (b MilMatrix3x2D) GetS_11() float64 {
	offset := uintptr(MilMatrix3x2DS_11Offset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetS_11 copies value into the native field.
func (b MilMatrix3x2D) SetS_11(value float64) {
	offset := uintptr(MilMatrix3x2DS_11Offset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetS_12 returns a copy of the native field value.
func (b MilMatrix3x2D) GetS_12() float64 {
	offset := uintptr(MilMatrix3x2DS_12Offset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetS_12 copies value into the native field.
func (b MilMatrix3x2D) SetS_12(value float64) {
	offset := uintptr(MilMatrix3x2DS_12Offset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetS_21 returns a copy of the native field value.
func (b MilMatrix3x2D) GetS_21() float64 {
	offset := uintptr(MilMatrix3x2DS_21Offset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetS_21 copies value into the native field.
func (b MilMatrix3x2D) SetS_21(value float64) {
	offset := uintptr(MilMatrix3x2DS_21Offset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetS_22 returns a copy of the native field value.
func (b MilMatrix3x2D) GetS_22() float64 {
	offset := uintptr(MilMatrix3x2DS_22Offset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetS_22 copies value into the native field.
func (b MilMatrix3x2D) SetS_22(value float64) {
	offset := uintptr(MilMatrix3x2DS_22Offset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetDX returns a copy of the native field value.
func (b MilMatrix3x2D) GetDX() float64 {
	offset := uintptr(MilMatrix3x2DDXOffset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetDX copies value into the native field.
func (b MilMatrix3x2D) SetDX(value float64) {
	offset := uintptr(MilMatrix3x2DDXOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// GetDY returns a copy of the native field value.
func (b MilMatrix3x2D) GetDY() float64 {
	offset := uintptr(MilMatrix3x2DDYOffset)

	return nativebuffer.Read[float64](b.Bytes()[offset : offset+(8)])
}

// SetDY copies value into the native field.
func (b MilMatrix3x2D) SetDY(value float64) {
	offset := uintptr(MilMatrix3x2DDYOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(8)], value)
}

// UNSIGNED_RATIO is a view of native Windows.Win32.Graphics.Dwm.UNSIGNED_RATIO storage.
// Its Go representation is not the native layout. Use New or View to initialize it,
// and Pointer when passing it to Windows. Copies share storage; the zero value is invalid.
// See https://learn.microsoft.com/windows/win32/api/dwmapi/ns-dwmapi-unsigned_ratio.
type UNSIGNED_RATIO struct{ data []byte }

// Native size, alignment, and field offsets for the current pointer width.
const (
	UNSIGNED_RATIOSize                = 8
	UNSIGNED_RATIOAlignment           = 1
	UNSIGNED_RATIOUiNumeratorOffset   = 0
	UNSIGNED_RATIOUiDenominatorOffset = 4
)

// NewUNSIGNED_RATIO allocates zeroed, aligned native storage.
func NewUNSIGNED_RATIO() UNSIGNED_RATIO {
	return UNSIGNED_RATIO{data: nativebuffer.New(int(UNSIGNED_RATIOSize), uintptr(UNSIGNED_RATIOAlignment))}
}

// ViewUNSIGNED_RATIO shares data without copying. It panics if data is shorter than UNSIGNED_RATIOSize.
// Unaligned views support field access, but Pointer requires native alignment.
func ViewUNSIGNED_RATIO(data []byte) UNSIGNED_RATIO {
	return UNSIGNED_RATIO{data: nativebuffer.View(data, int(UNSIGNED_RATIOSize))}
}

// Bytes returns the shared native storage, including padding and the initial flexible-array extent.
func (b UNSIGNED_RATIO) Bytes() []byte {
	return b.data[:UNSIGNED_RATIOSize:UNSIGNED_RATIOSize]
}

// Pointer returns the native address. It panics for an invalid or unaligned view.
// Keep the view alive while Windows uses it.
func (b UNSIGNED_RATIO) Pointer() unsafe.Pointer {
	return nativebuffer.Pointer(b.Bytes(), uintptr(UNSIGNED_RATIOAlignment))
}

// GetUiNumerator returns a copy of the native field value.
func (b UNSIGNED_RATIO) GetUiNumerator() uint32 {
	offset := uintptr(UNSIGNED_RATIOUiNumeratorOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetUiNumerator copies value into the native field.
func (b UNSIGNED_RATIO) SetUiNumerator(value uint32) {
	offset := uintptr(UNSIGNED_RATIOUiNumeratorOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// GetUiDenominator returns a copy of the native field value.
func (b UNSIGNED_RATIO) GetUiDenominator() uint32 {
	offset := uintptr(UNSIGNED_RATIOUiDenominatorOffset)

	return nativebuffer.Read[uint32](b.Bytes()[offset : offset+(4)])
}

// SetUiDenominator copies value into the native field.
func (b UNSIGNED_RATIO) SetUiDenominator(value uint32) {
	offset := uintptr(UNSIGNED_RATIOUiDenominatorOffset)
	nativebuffer.Write(b.Bytes()[offset:offset+(4)], value)
}

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [4]byte = [unsafe.Sizeof(*new(DWM_SOURCE_FRAME_SAMPLING))]byte{}
	_ [4]byte = [unsafe.Alignof(*new(DWM_SOURCE_FRAME_SAMPLING))]byte{}
)
