// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.25-preview (65783efbef7950839ae287fa933610eb939fcddaef80024dea8465f37a9449ad).
// Documentation: Microsoft.Windows.SDK.Win32Docs 0.1.42-alpha (e83bf398dceb1957d698d24daa8a23f986beedb0109727a0ee99b229a525230b).

// Package jobobject provides job object limits, controls, information classes, and rate-control flags.
package jobobject

// Value is the common representation used by this package.
type Value uint32

const (
	JOBOBJECT_IO_ATTRIBUTION_CONTROL_DISABLE     Value = 0x00000002
	JOBOBJECT_IO_ATTRIBUTION_CONTROL_ENABLE      Value = 0x00000001
	JOBOBJECT_IO_ATTRIBUTION_CONTROL_VALID_FLAGS Value = 0x00000003
	JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS           Value = 0x000000FF
	// JOB_OBJECT_CPU_RATE_CONTROL_ENABLE: This flag enables the job's CPU rate to be controlled based on weight or hard
	// cap. You must set this value if you also set JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED ,
	// JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP , or JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE .
	JOB_OBJECT_CPU_RATE_CONTROL_ENABLE Value = 0x00000001
	// JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP: The job's CPU rate is a hard limit. After the job reaches its CPU cycle limit
	// for the current scheduling interval, no threads associated with the job will run until the next interval. If you set
	// JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP , you cannot also set JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE .
	JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP     Value = 0x00000004
	JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE Value = 0x00000010
	// JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY: Sends messages when the CPU rate for the job exceeds the rate limits for the job
	// during the tolerance interval.
	JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY      Value = 0x00000008
	JOB_OBJECT_CPU_RATE_CONTROL_VALID_FLAGS Value = 0x0000003F
	// JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED: The job's CPU rate is calculated based on its relative weight to the
	// weight of other jobs. If this flag is set, the Weight member contains more information. If this flag is clear, the
	// CpuRate member contains more information. If you set JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED , you cannot also set
	// JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE .
	JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED Value = 0x00000002
	JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS    Value = 0x00007FFF
	// JOB_OBJECT_IO_RATE_CONTROL_ENABLE: Turns on control of the I/O rate for the job when this structure is passed to the
	// SetIoRateControlInformationJobObject function. Indicates that control of the I/O rate for the job is turned on when
	// this structure is used with the QueryIoRateControlInformationJobObject function.
	JOB_OBJECT_IO_RATE_CONTROL_ENABLE                        Value = 0x00000001
	JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ALL         Value = 0x00000004
	JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ON_SOFT_CAP Value = 0x00000008
	JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME             Value = 0x00000002
	JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS                   Value = 0x0000000F
	// JOB_OBJECT_LIMIT_ACTIVE_PROCESS: Establishes a maximum number of simultaneously active processes associated with the
	// job. The ActiveProcessLimit member contains additional information.
	JOB_OBJECT_LIMIT_ACTIVE_PROCESS Value = 0x00000008
	// JOB_OBJECT_LIMIT_AFFINITY: Causes all processes associated with the job to use the same processor affinity. The
	// Affinity member contains additional information. If the job is nested, the specified processor affinity must be a
	// subset of the effective affinity of the parent job. If the specified affinity a superset of the affinity of the
	// parent job, it is ignored and the affinity of the parent job is used.
	JOB_OBJECT_LIMIT_AFFINITY Value = 0x00000010
	// JOB_OBJECT_LIMIT_BREAKAWAY_OK: If any process associated with the job creates a child process using the
	// CREATE_BREAKAWAY_FROM_JOB flag while this limit is in effect, the child process is not associated with the job. This
	// limit requires use of a JOBOBJECT_EXTENDED_LIMIT_INFORMATION structure. Its BasicLimitInformation member is a
	// JOBOBJECT_BASIC_LIMIT_INFORMATION structure.
	JOB_OBJECT_LIMIT_BREAKAWAY_OK Value = 0x00000800
	// JOB_OBJECT_LIMIT_CPU_RATE_CONTROL: Documentation varies per use. Refer to each:
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_CPU_RATE_CONTROL Value = 0x00040000
	// JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION: Forces a call to the SetErrorMode function with the
	// SEM_NOGPFAULTERRORBOX flag for each process associated with the job. If an exception occurs and the system calls the
	// UnhandledExceptionFilter function, the debugger will be given a chance to act. If there is no debugger, the
	// functions returns EXCEPTION_EXECUTE_HANDLER . Normally, this will cause termination of the process with the
	// exception code as the exit status. This limit requires use of a JOBOBJECT_EXTENDED_LIMIT_INFORMATION structure. Its
	// BasicLimitInformation member is a JOBOBJECT_BASIC_LIMIT_INFORMATION structure.
	JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION Value = 0x00000400
	// JOB_OBJECT_LIMIT_IO_RATE_CONTROL: Documentation varies per use. Refer to each:
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_IO_RATE_CONTROL Value = 0x00080000
	// JOB_OBJECT_LIMIT_JOB_MEMORY: Documentation varies per use. Refer to each: JOBOBJECT_BASIC_LIMIT_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION , JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION .
	JOB_OBJECT_LIMIT_JOB_MEMORY Value = 0x00000200
	// JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH: Documentation varies per use. Refer to each:
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH Value = 0x00000200
	// JOB_OBJECT_LIMIT_JOB_MEMORY_LOW: Documentation varies per use. Refer to each:
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_JOB_MEMORY_LOW Value = 0x00008000
	// JOB_OBJECT_LIMIT_JOB_READ_BYTES: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION
	// , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_JOB_READ_BYTES Value = 0x00010000
	// JOB_OBJECT_LIMIT_JOB_TIME: Documentation varies per use. Refer to each: JOBOBJECT_BASIC_LIMIT_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION , JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_JOB_TIME Value = 0x00000004
	// JOB_OBJECT_LIMIT_JOB_WRITE_BYTES: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION
	// , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_JOB_WRITE_BYTES Value = 0x00020000
	// JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE: Causes all processes associated with the job to terminate when the last handle
	// to the job is closed. This limit requires use of a JOBOBJECT_EXTENDED_LIMIT_INFORMATION structure. Its
	// BasicLimitInformation member is a JOBOBJECT_BASIC_LIMIT_INFORMATION structure.
	JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE Value = 0x00002000
	// JOB_OBJECT_LIMIT_NET_RATE_CONTROL: Documentation varies per use. Refer to each:
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_NET_RATE_CONTROL Value = 0x00100000
	// JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME: Preserves any job time limits you previously set. As long as this flag is set,
	// you can establish a per-job time limit once, then alter other limits in subsequent calls. This flag cannot be used
	// with JOB_OBJECT_LIMIT_JOB_TIME .
	JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME Value = 0x00000040
	// JOB_OBJECT_LIMIT_PRIORITY_CLASS: Causes all processes associated with the job to use the same priority class. For
	// more information, see Scheduling Priorities . The PriorityClass member contains additional information. If the job
	// is nested, the effective priority class is the lowest priority class in the job chain.
	JOB_OBJECT_LIMIT_PRIORITY_CLASS Value = 0x00000020
	// JOB_OBJECT_LIMIT_PROCESS_MEMORY: Causes all processes associated with the job to limit their committed memory. When
	// a process attempts to commit memory that would exceed the per-process limit, it fails. If the job object is
	// associated with a completion port, a JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT message is sent to the completion port. If
	// the job is nested, the effective memory limit is the most restrictive memory limit in the job chain. This limit
	// requires use of a JOBOBJECT_EXTENDED_LIMIT_INFORMATION structure. Its BasicLimitInformation member is a
	// JOBOBJECT_BASIC_LIMIT_INFORMATION structure.
	JOB_OBJECT_LIMIT_PROCESS_MEMORY Value = 0x00000100
	// JOB_OBJECT_LIMIT_PROCESS_TIME: Establishes a user-mode execution time limit for each currently active process and
	// for all future processes associated with the job. The PerProcessUserTimeLimit member contains additional
	// information.
	JOB_OBJECT_LIMIT_PROCESS_TIME Value = 0x00000002
	// JOB_OBJECT_LIMIT_RATE_CONTROL: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	JOB_OBJECT_LIMIT_RATE_CONTROL Value = 0x00040000
	// JOB_OBJECT_LIMIT_SCHEDULING_CLASS: Causes all processes in the job to use the same scheduling class. The
	// SchedulingClass member contains additional information. If the job is nested, the effective scheduling class is the
	// lowest scheduling class in the job chain.
	JOB_OBJECT_LIMIT_SCHEDULING_CLASS Value = 0x00000080
	// JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK: Allows any process associated with the job to create child processes that are
	// not associated with the job. If the job is nested and its immediate job object allows breakaway, the child process
	// breaks away from the immediate job object and from each job in the parent job chain, moving up the hierarchy until
	// it reaches a job that does not permit breakaway. If the immediate job object does not allow breakaway, the child
	// process does not break away even if jobs in its parent job chain allow it. This limit requires use of a
	// JOBOBJECT_EXTENDED_LIMIT_INFORMATION structure. Its BasicLimitInformation member is a
	// JOBOBJECT_BASIC_LIMIT_INFORMATION structure.
	JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK Value = 0x00001000
	// JOB_OBJECT_LIMIT_SUBSET_AFFINITY: Allows processes to use a subset of the processor affinity for all processes
	// associated with the job. This value must be combined with JOB_OBJECT_LIMIT_AFFINITY . Windows Server 2008, Windows
	// Vista, Windows Server 2003 and Windows XP: This flag is supported starting with Windows 7 and Windows Server 2008
	// R2.
	JOB_OBJECT_LIMIT_SUBSET_AFFINITY Value = 0x00004000
	JOB_OBJECT_LIMIT_VALID_FLAGS     Value = 0x0007FFFF
	// JOB_OBJECT_LIMIT_WORKINGSET: Causes all processes associated with the job to use the same minimum and maximum
	// working set sizes. The MinimumWorkingSetSize and MaximumWorkingSetSize members contain additional information. If
	// the job is nested, the effective working set size is the smallest working set size in the job chain.
	JOB_OBJECT_LIMIT_WORKINGSET Value = 0x00000001
	// JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG: Sets the DSCP field in the packet header to the value of the DscpTag member of
	// the JOBOBJECT_NET_RATE_CONTROL_INFORMATION structure. For information about DSCP, see Differentiated Services .
	JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG Value = 0x00000004
	// JOB_OBJECT_NET_RATE_CONTROL_ENABLE: Turns on the control of the network traffic. You must set this value if you also
	// set either JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH or JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG .
	JOB_OBJECT_NET_RATE_CONTROL_ENABLE        Value = 0x00000001
	JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH Value = 0x00000002
	// JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS: The combination of all of the valid flags for the
	// JOB_OBJECT_NET_RATE_CONTROL_FLAGS enumeration.
	JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS   Value = 0x00000007
	JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS Value = 0x001F8204
	// JOB_OBJECT_POST_AT_END_OF_JOB: Posts a completion packet to the completion port using the PostQueuedCompletionStatus
	// function. After the completion packet is posted, the system clears the end-of-job time limit, and processes in the
	// job can continue their execution. If no completion port is associated with the job when the time limit has been
	// exceeded, the action taken is the same as for JOB_OBJECT_TERMINATE_AT_END_OF_JOB.
	JOB_OBJECT_POST_AT_END_OF_JOB Value = 0x00000001
	// JOB_OBJECT_SECURITY_FILTER_TOKENS: Applies a filter to the token when a process impersonates a client. Requires at
	// least one of the following members to be set: SidsToDisable , PrivilegesToDelete , or RestrictedSids .
	JOB_OBJECT_SECURITY_FILTER_TOKENS Value = 0x00000008
	// JOB_OBJECT_SECURITY_NO_ADMIN: Prevents any process in the job from using a token that specifies the local
	// administrators group.
	JOB_OBJECT_SECURITY_NO_ADMIN Value = 0x00000001
	// JOB_OBJECT_SECURITY_ONLY_TOKEN: Forces processes in the job to run under a specific token. Requires a token handle
	// in the JobToken member.
	JOB_OBJECT_SECURITY_ONLY_TOKEN Value = 0x00000004
	// JOB_OBJECT_SECURITY_RESTRICTED_TOKEN: Prevents any process in the job from using a token that was not created with
	// the CreateRestrictedToken function.
	JOB_OBJECT_SECURITY_RESTRICTED_TOKEN Value = 0x00000002
	JOB_OBJECT_SECURITY_VALID_FLAGS      Value = 0x0000000F
	// JOB_OBJECT_TERMINATE_AT_END_OF_JOB: Terminates all processes and sets the exit status to ERROR_NOT_ENOUGH_QUOTA. The
	// processes cannot prevent or delay their own termination. The job object is set to the signaled state and remains
	// signaled until this limit is reset. No additional processes can be assigned to the job until the limit is reset.
	// This is the default termination action.
	JOB_OBJECT_TERMINATE_AT_END_OF_JOB Value = 0x00000000
	// JOB_OBJECT_UILIMIT_DESKTOP: Prevents processes associated with the job from creating desktops and switching desktops
	// using the CreateDesktop and SwitchDesktop functions.
	JOB_OBJECT_UILIMIT_DESKTOP Value = 0x00000040
	// JOB_OBJECT_UILIMIT_DISPLAYSETTINGS: Prevents processes associated with the job from calling the
	// ChangeDisplaySettings function.
	JOB_OBJECT_UILIMIT_DISPLAYSETTINGS Value = 0x00000010
	// JOB_OBJECT_UILIMIT_EXITWINDOWS: Prevents processes associated with the job from calling the ExitWindows or
	// ExitWindowsEx function.
	JOB_OBJECT_UILIMIT_EXITWINDOWS Value = 0x00000080
	// JOB_OBJECT_UILIMIT_GLOBALATOMS: Prevents processes associated with the job from accessing global atoms. When this
	// flag is used, each job has its own atom table.
	JOB_OBJECT_UILIMIT_GLOBALATOMS Value = 0x00000020
	// JOB_OBJECT_UILIMIT_HANDLES: Prevents processes associated with the job from using USER handles owned by processes
	// not associated with the same job.
	JOB_OBJECT_UILIMIT_HANDLES Value = 0x00000001
	JOB_OBJECT_UILIMIT_NONE    Value = 0x00000000
	// JOB_OBJECT_UILIMIT_READCLIPBOARD: Prevents processes associated with the job from reading data from the clipboard.
	JOB_OBJECT_UILIMIT_READCLIPBOARD Value = 0x00000002
	// JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS: Prevents processes associated with the job from changing system parameters by
	// using the SystemParametersInfo function.
	JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS Value = 0x00000008
	// JOB_OBJECT_UILIMIT_WRITECLIPBOARD: Prevents processes associated with the job from writing data to the clipboard.
	JOB_OBJECT_UILIMIT_WRITECLIPBOARD Value = 0x00000004
	// JobObjectAssociateCompletionPortInformation: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_ASSOCIATE_COMPLETION_PORT structure.
	JobObjectAssociateCompletionPortInformation Value = 0x00000007
	// JobObjectBasicAccountingInformation: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_BASIC_ACCOUNTING_INFORMATION structure.
	JobObjectBasicAccountingInformation Value = 0x00000001
	// JobObjectBasicAndIoAccountingInformation: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION structure.
	JobObjectBasicAndIoAccountingInformation Value = 0x00000008
	// JobObjectBasicLimitInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectBasicLimitInformation Value = 0x00000002
	// JobObjectBasicProcessIdList: The lpJobObjectInfo parameter is a pointer to a JOBOBJECT_BASIC_PROCESS_ID_LIST
	// structure.
	JobObjectBasicProcessIdList Value = 0x00000003
	// JobObjectBasicUIRestrictions: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectBasicUIRestrictions Value = 0x00000004
	JobObjectCompletionCounter   Value = 0x00000011
	JobObjectCompletionFilter    Value = 0x00000010
	// JobObjectCpuRateControlInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectCpuRateControlInformation Value = 0x0000000F
	JobObjectCreateSilo                Value = 0x00000023
	// JobObjectEndOfJobTimeInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectEndOfJobTimeInformation Value = 0x00000006
	// JobObjectExtendedLimitInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectExtendedLimitInformation Value = 0x00000009
	// JobObjectGroupInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectGroupInformation Value = 0x0000000B
	// JobObjectGroupInformationEx: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectGroupInformationEx Value = 0x0000000E
	JobObjectJobSetInformation  Value = 0x0000000A
	// JobObjectLimitViolationInformation: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION structure. Windows 7, Windows Server 2008 R2, Windows Server 2008, Windows
	// Vista, Windows Server 2003 and Windows XP: This flag is not supported.
	JobObjectLimitViolationInformation Value = 0x0000000D
	// JobObjectLimitViolationInformation2: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 structure. Windows 8.1, Windows Server 2012 R2, Windows 8, Windows Server
	// 2012, Windows 7, Windows Server 2008 R2, Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP:
	// This flag is not supported.
	JobObjectLimitViolationInformation2 Value = 0x00000022
	// JobObjectNetRateControlInformation: The lpJobObjectInfo parameter is a pointer to a
	// JOBOBJECT_NET_RATE_CONTROL_INFORMATION structure. Windows 8.1, Windows Server 2012 R2, Windows 8, Windows Server
	// 2012, Windows 7, Windows Server 2008 R2, Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP:
	// This flag is not supported.
	JobObjectNetRateControlInformation    Value = 0x00000020
	JobObjectNetworkAccountingInformation Value = 0x00000033
	// JobObjectNotificationLimitInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectNotificationLimitInformation Value = 0x0000000C
	// JobObjectNotificationLimitInformation2: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectNotificationLimitInformation2 Value = 0x00000021
	JobObjectReserved10Information         Value = 0x0000001B
	JobObjectReserved11Information         Value = 0x0000001C
	JobObjectReserved12Information         Value = 0x0000001D
	JobObjectReserved13Information         Value = 0x0000001E
	JobObjectReserved14Information         Value = 0x0000001F
	JobObjectReserved15Information         Value = 0x00000025
	JobObjectReserved16Information         Value = 0x00000026
	JobObjectReserved17Information         Value = 0x00000027
	JobObjectReserved18Information         Value = 0x00000028
	JobObjectReserved19Information         Value = 0x00000029
	JobObjectReserved1Information          Value = 0x00000012
	JobObjectReserved20Information         Value = 0x0000002A
	JobObjectReserved21Information         Value = 0x0000002B
	JobObjectReserved22Information         Value = 0x0000002C
	JobObjectReserved23Information         Value = 0x0000002D
	JobObjectReserved24Information         Value = 0x0000002E
	JobObjectReserved25Information         Value = 0x0000002F
	JobObjectReserved26Information         Value = 0x00000030
	JobObjectReserved27Information         Value = 0x00000031
	JobObjectReserved28Information         Value = 0x00000032
	JobObjectReserved2Information          Value = 0x00000013
	JobObjectReserved3Information          Value = 0x00000014
	JobObjectReserved4Information          Value = 0x00000015
	JobObjectReserved5Information          Value = 0x00000016
	JobObjectReserved6Information          Value = 0x00000017
	JobObjectReserved7Information          Value = 0x00000018
	JobObjectReserved8Information          Value = 0x00000019
	JobObjectReserved9Information          Value = 0x0000001A
	// JobObjectSecurityLimitInformation: Documentation varies per use. Refer to each: QueryInformationJobObject ,
	// SetInformationJobObject .
	JobObjectSecurityLimitInformation Value = 0x00000005
	JobObjectSiloBasicInformation     Value = 0x00000024
	MaxJobObjectInfoClass             Value = 0x00000034
	// ToleranceHigh: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	ToleranceHigh Value = 0x00000003
	// ToleranceIntervalLong: The tolerance interval is 10 minutes.
	ToleranceIntervalLong Value = 0x00000003
	// ToleranceIntervalMedium: The tolerance interval is one minute.
	ToleranceIntervalMedium Value = 0x00000002
	// ToleranceIntervalShort: The tolerance interval is 10 seconds.
	ToleranceIntervalShort Value = 0x00000001
	// ToleranceLow: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	ToleranceLow Value = 0x00000001
	// ToleranceMedium: Documentation varies per use. Refer to each: JOBOBJECT_LIMIT_VIOLATION_INFORMATION ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 , JOBOBJECT_LIMIT_VIOLATION_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 , JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 ,
	// JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION_2 .
	ToleranceMedium Value = 0x00000002
)

// Name returns the canonical symbolic name for value.
func Name(value Value) (string, bool) {
	switch value {
	case Value(0x00000000):
		return "JOB_OBJECT_TERMINATE_AT_END_OF_JOB", true
	case Value(0x00000001):
		return "JOBOBJECT_IO_ATTRIBUTION_CONTROL_ENABLE", true
	case Value(0x00000002):
		return "JOBOBJECT_IO_ATTRIBUTION_CONTROL_DISABLE", true
	case Value(0x00000003):
		return "JOBOBJECT_IO_ATTRIBUTION_CONTROL_VALID_FLAGS", true
	case Value(0x00000004):
		return "JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP", true
	case Value(0x00000005):
		return "JobObjectSecurityLimitInformation", true
	case Value(0x00000006):
		return "JobObjectEndOfJobTimeInformation", true
	case Value(0x00000007):
		return "JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS", true
	case Value(0x00000008):
		return "JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY", true
	case Value(0x00000009):
		return "JobObjectExtendedLimitInformation", true
	case Value(0x0000000A):
		return "JobObjectJobSetInformation", true
	case Value(0x0000000B):
		return "JobObjectGroupInformation", true
	case Value(0x0000000C):
		return "JobObjectNotificationLimitInformation", true
	case Value(0x0000000D):
		return "JobObjectLimitViolationInformation", true
	case Value(0x0000000E):
		return "JobObjectGroupInformationEx", true
	case Value(0x0000000F):
		return "JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS", true
	case Value(0x00000010):
		return "JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE", true
	case Value(0x00000011):
		return "JobObjectCompletionCounter", true
	case Value(0x00000012):
		return "JobObjectReserved1Information", true
	case Value(0x00000013):
		return "JobObjectReserved2Information", true
	case Value(0x00000014):
		return "JobObjectReserved3Information", true
	case Value(0x00000015):
		return "JobObjectReserved4Information", true
	case Value(0x00000016):
		return "JobObjectReserved5Information", true
	case Value(0x00000017):
		return "JobObjectReserved6Information", true
	case Value(0x00000018):
		return "JobObjectReserved7Information", true
	case Value(0x00000019):
		return "JobObjectReserved8Information", true
	case Value(0x0000001A):
		return "JobObjectReserved9Information", true
	case Value(0x0000001B):
		return "JobObjectReserved10Information", true
	case Value(0x0000001C):
		return "JobObjectReserved11Information", true
	case Value(0x0000001D):
		return "JobObjectReserved12Information", true
	case Value(0x0000001E):
		return "JobObjectReserved13Information", true
	case Value(0x0000001F):
		return "JobObjectReserved14Information", true
	case Value(0x00000020):
		return "JOB_OBJECT_LIMIT_PRIORITY_CLASS", true
	case Value(0x00000021):
		return "JobObjectNotificationLimitInformation2", true
	case Value(0x00000022):
		return "JobObjectLimitViolationInformation2", true
	case Value(0x00000023):
		return "JobObjectCreateSilo", true
	case Value(0x00000024):
		return "JobObjectSiloBasicInformation", true
	case Value(0x00000025):
		return "JobObjectReserved15Information", true
	case Value(0x00000026):
		return "JobObjectReserved16Information", true
	case Value(0x00000027):
		return "JobObjectReserved17Information", true
	case Value(0x00000028):
		return "JobObjectReserved18Information", true
	case Value(0x00000029):
		return "JobObjectReserved19Information", true
	case Value(0x0000002A):
		return "JobObjectReserved20Information", true
	case Value(0x0000002B):
		return "JobObjectReserved21Information", true
	case Value(0x0000002C):
		return "JobObjectReserved22Information", true
	case Value(0x0000002D):
		return "JobObjectReserved23Information", true
	case Value(0x0000002E):
		return "JobObjectReserved24Information", true
	case Value(0x0000002F):
		return "JobObjectReserved25Information", true
	case Value(0x00000030):
		return "JobObjectReserved26Information", true
	case Value(0x00000031):
		return "JobObjectReserved27Information", true
	case Value(0x00000032):
		return "JobObjectReserved28Information", true
	case Value(0x00000033):
		return "JobObjectNetworkAccountingInformation", true
	case Value(0x00000034):
		return "MaxJobObjectInfoClass", true
	case Value(0x0000003F):
		return "JOB_OBJECT_CPU_RATE_CONTROL_VALID_FLAGS", true
	case Value(0x00000040):
		return "JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME", true
	case Value(0x00000080):
		return "JOB_OBJECT_LIMIT_SCHEDULING_CLASS", true
	case Value(0x000000FF):
		return "JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS", true
	case Value(0x00000100):
		return "JOB_OBJECT_LIMIT_PROCESS_MEMORY", true
	case Value(0x00000200):
		return "JOB_OBJECT_LIMIT_JOB_MEMORY", true
	case Value(0x00000400):
		return "JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION", true
	case Value(0x00000800):
		return "JOB_OBJECT_LIMIT_BREAKAWAY_OK", true
	case Value(0x00001000):
		return "JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK", true
	case Value(0x00002000):
		return "JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE", true
	case Value(0x00004000):
		return "JOB_OBJECT_LIMIT_SUBSET_AFFINITY", true
	case Value(0x00007FFF):
		return "JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS", true
	case Value(0x00008000):
		return "JOB_OBJECT_LIMIT_JOB_MEMORY_LOW", true
	case Value(0x00010000):
		return "JOB_OBJECT_LIMIT_JOB_READ_BYTES", true
	case Value(0x00020000):
		return "JOB_OBJECT_LIMIT_JOB_WRITE_BYTES", true
	case Value(0x00040000):
		return "JOB_OBJECT_LIMIT_CPU_RATE_CONTROL", true
	case Value(0x0007FFFF):
		return "JOB_OBJECT_LIMIT_VALID_FLAGS", true
	case Value(0x00080000):
		return "JOB_OBJECT_LIMIT_IO_RATE_CONTROL", true
	case Value(0x00100000):
		return "JOB_OBJECT_LIMIT_NET_RATE_CONTROL", true
	case Value(0x001F8204):
		return "JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS", true
	default:
		return "", false
	}
}

// Names returns every symbolic alias for value in lexical order.
func Names(value Value) []string {
	switch value {
	case Value(0x00000000):
		return []string{"JOB_OBJECT_TERMINATE_AT_END_OF_JOB", "JOB_OBJECT_UILIMIT_NONE"}
	case Value(0x00000001):
		return []string{"JOBOBJECT_IO_ATTRIBUTION_CONTROL_ENABLE", "JOB_OBJECT_CPU_RATE_CONTROL_ENABLE", "JOB_OBJECT_IO_RATE_CONTROL_ENABLE", "JOB_OBJECT_LIMIT_WORKINGSET", "JOB_OBJECT_NET_RATE_CONTROL_ENABLE", "JOB_OBJECT_POST_AT_END_OF_JOB", "JOB_OBJECT_SECURITY_NO_ADMIN", "JOB_OBJECT_UILIMIT_HANDLES", "JobObjectBasicAccountingInformation", "ToleranceIntervalShort", "ToleranceLow"}
	case Value(0x00000002):
		return []string{"JOBOBJECT_IO_ATTRIBUTION_CONTROL_DISABLE", "JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED", "JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME", "JOB_OBJECT_LIMIT_PROCESS_TIME", "JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH", "JOB_OBJECT_SECURITY_RESTRICTED_TOKEN", "JOB_OBJECT_UILIMIT_READCLIPBOARD", "JobObjectBasicLimitInformation", "ToleranceIntervalMedium", "ToleranceMedium"}
	case Value(0x00000003):
		return []string{"JOBOBJECT_IO_ATTRIBUTION_CONTROL_VALID_FLAGS", "JobObjectBasicProcessIdList", "ToleranceHigh", "ToleranceIntervalLong"}
	case Value(0x00000004):
		return []string{"JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP", "JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ALL", "JOB_OBJECT_LIMIT_JOB_TIME", "JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG", "JOB_OBJECT_SECURITY_ONLY_TOKEN", "JOB_OBJECT_UILIMIT_WRITECLIPBOARD", "JobObjectBasicUIRestrictions"}
	case Value(0x00000005):
		return []string{"JobObjectSecurityLimitInformation"}
	case Value(0x00000006):
		return []string{"JobObjectEndOfJobTimeInformation"}
	case Value(0x00000007):
		return []string{"JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS", "JobObjectAssociateCompletionPortInformation"}
	case Value(0x00000008):
		return []string{"JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY", "JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ON_SOFT_CAP", "JOB_OBJECT_LIMIT_ACTIVE_PROCESS", "JOB_OBJECT_SECURITY_FILTER_TOKENS", "JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS", "JobObjectBasicAndIoAccountingInformation"}
	case Value(0x00000009):
		return []string{"JobObjectExtendedLimitInformation"}
	case Value(0x0000000A):
		return []string{"JobObjectJobSetInformation"}
	case Value(0x0000000B):
		return []string{"JobObjectGroupInformation"}
	case Value(0x0000000C):
		return []string{"JobObjectNotificationLimitInformation"}
	case Value(0x0000000D):
		return []string{"JobObjectLimitViolationInformation"}
	case Value(0x0000000E):
		return []string{"JobObjectGroupInformationEx"}
	case Value(0x0000000F):
		return []string{"JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS", "JOB_OBJECT_SECURITY_VALID_FLAGS", "JobObjectCpuRateControlInformation"}
	case Value(0x00000010):
		return []string{"JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE", "JOB_OBJECT_LIMIT_AFFINITY", "JOB_OBJECT_UILIMIT_DISPLAYSETTINGS", "JobObjectCompletionFilter"}
	case Value(0x00000011):
		return []string{"JobObjectCompletionCounter"}
	case Value(0x00000012):
		return []string{"JobObjectReserved1Information"}
	case Value(0x00000013):
		return []string{"JobObjectReserved2Information"}
	case Value(0x00000014):
		return []string{"JobObjectReserved3Information"}
	case Value(0x00000015):
		return []string{"JobObjectReserved4Information"}
	case Value(0x00000016):
		return []string{"JobObjectReserved5Information"}
	case Value(0x00000017):
		return []string{"JobObjectReserved6Information"}
	case Value(0x00000018):
		return []string{"JobObjectReserved7Information"}
	case Value(0x00000019):
		return []string{"JobObjectReserved8Information"}
	case Value(0x0000001A):
		return []string{"JobObjectReserved9Information"}
	case Value(0x0000001B):
		return []string{"JobObjectReserved10Information"}
	case Value(0x0000001C):
		return []string{"JobObjectReserved11Information"}
	case Value(0x0000001D):
		return []string{"JobObjectReserved12Information"}
	case Value(0x0000001E):
		return []string{"JobObjectReserved13Information"}
	case Value(0x0000001F):
		return []string{"JobObjectReserved14Information"}
	case Value(0x00000020):
		return []string{"JOB_OBJECT_LIMIT_PRIORITY_CLASS", "JOB_OBJECT_UILIMIT_GLOBALATOMS", "JobObjectNetRateControlInformation"}
	case Value(0x00000021):
		return []string{"JobObjectNotificationLimitInformation2"}
	case Value(0x00000022):
		return []string{"JobObjectLimitViolationInformation2"}
	case Value(0x00000023):
		return []string{"JobObjectCreateSilo"}
	case Value(0x00000024):
		return []string{"JobObjectSiloBasicInformation"}
	case Value(0x00000025):
		return []string{"JobObjectReserved15Information"}
	case Value(0x00000026):
		return []string{"JobObjectReserved16Information"}
	case Value(0x00000027):
		return []string{"JobObjectReserved17Information"}
	case Value(0x00000028):
		return []string{"JobObjectReserved18Information"}
	case Value(0x00000029):
		return []string{"JobObjectReserved19Information"}
	case Value(0x0000002A):
		return []string{"JobObjectReserved20Information"}
	case Value(0x0000002B):
		return []string{"JobObjectReserved21Information"}
	case Value(0x0000002C):
		return []string{"JobObjectReserved22Information"}
	case Value(0x0000002D):
		return []string{"JobObjectReserved23Information"}
	case Value(0x0000002E):
		return []string{"JobObjectReserved24Information"}
	case Value(0x0000002F):
		return []string{"JobObjectReserved25Information"}
	case Value(0x00000030):
		return []string{"JobObjectReserved26Information"}
	case Value(0x00000031):
		return []string{"JobObjectReserved27Information"}
	case Value(0x00000032):
		return []string{"JobObjectReserved28Information"}
	case Value(0x00000033):
		return []string{"JobObjectNetworkAccountingInformation"}
	case Value(0x00000034):
		return []string{"MaxJobObjectInfoClass"}
	case Value(0x0000003F):
		return []string{"JOB_OBJECT_CPU_RATE_CONTROL_VALID_FLAGS"}
	case Value(0x00000040):
		return []string{"JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME", "JOB_OBJECT_UILIMIT_DESKTOP"}
	case Value(0x00000080):
		return []string{"JOB_OBJECT_LIMIT_SCHEDULING_CLASS", "JOB_OBJECT_UILIMIT_EXITWINDOWS"}
	case Value(0x000000FF):
		return []string{"JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS"}
	case Value(0x00000100):
		return []string{"JOB_OBJECT_LIMIT_PROCESS_MEMORY"}
	case Value(0x00000200):
		return []string{"JOB_OBJECT_LIMIT_JOB_MEMORY", "JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH"}
	case Value(0x00000400):
		return []string{"JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION"}
	case Value(0x00000800):
		return []string{"JOB_OBJECT_LIMIT_BREAKAWAY_OK"}
	case Value(0x00001000):
		return []string{"JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK"}
	case Value(0x00002000):
		return []string{"JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE"}
	case Value(0x00004000):
		return []string{"JOB_OBJECT_LIMIT_SUBSET_AFFINITY"}
	case Value(0x00007FFF):
		return []string{"JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS"}
	case Value(0x00008000):
		return []string{"JOB_OBJECT_LIMIT_JOB_MEMORY_LOW"}
	case Value(0x00010000):
		return []string{"JOB_OBJECT_LIMIT_JOB_READ_BYTES"}
	case Value(0x00020000):
		return []string{"JOB_OBJECT_LIMIT_JOB_WRITE_BYTES"}
	case Value(0x00040000):
		return []string{"JOB_OBJECT_LIMIT_CPU_RATE_CONTROL", "JOB_OBJECT_LIMIT_RATE_CONTROL"}
	case Value(0x0007FFFF):
		return []string{"JOB_OBJECT_LIMIT_VALID_FLAGS"}
	case Value(0x00080000):
		return []string{"JOB_OBJECT_LIMIT_IO_RATE_CONTROL"}
	case Value(0x00100000):
		return []string{"JOB_OBJECT_LIMIT_NET_RATE_CONTROL"}
	case Value(0x001F8204):
		return []string{"JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS"}
	default:
		return nil
	}
}

// Parse returns the numeric value associated with an exact symbolic name.
func Parse(name string) (Value, bool) {
	switch name {
	case "JOBOBJECT_IO_ATTRIBUTION_CONTROL_DISABLE":
		return JOBOBJECT_IO_ATTRIBUTION_CONTROL_DISABLE, true
	case "JOBOBJECT_IO_ATTRIBUTION_CONTROL_ENABLE":
		return JOBOBJECT_IO_ATTRIBUTION_CONTROL_ENABLE, true
	case "JOBOBJECT_IO_ATTRIBUTION_CONTROL_VALID_FLAGS":
		return JOBOBJECT_IO_ATTRIBUTION_CONTROL_VALID_FLAGS, true
	case "JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS":
		return JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_ENABLE":
		return JOB_OBJECT_CPU_RATE_CONTROL_ENABLE, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP":
		return JOB_OBJECT_CPU_RATE_CONTROL_HARD_CAP, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE":
		return JOB_OBJECT_CPU_RATE_CONTROL_MIN_MAX_RATE, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY":
		return JOB_OBJECT_CPU_RATE_CONTROL_NOTIFY, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_VALID_FLAGS":
		return JOB_OBJECT_CPU_RATE_CONTROL_VALID_FLAGS, true
	case "JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED":
		return JOB_OBJECT_CPU_RATE_CONTROL_WEIGHT_BASED, true
	case "JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS":
		return JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS, true
	case "JOB_OBJECT_IO_RATE_CONTROL_ENABLE":
		return JOB_OBJECT_IO_RATE_CONTROL_ENABLE, true
	case "JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ALL":
		return JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ALL, true
	case "JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ON_SOFT_CAP":
		return JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ON_SOFT_CAP, true
	case "JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME":
		return JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME, true
	case "JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS":
		return JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS, true
	case "JOB_OBJECT_LIMIT_ACTIVE_PROCESS":
		return JOB_OBJECT_LIMIT_ACTIVE_PROCESS, true
	case "JOB_OBJECT_LIMIT_AFFINITY":
		return JOB_OBJECT_LIMIT_AFFINITY, true
	case "JOB_OBJECT_LIMIT_BREAKAWAY_OK":
		return JOB_OBJECT_LIMIT_BREAKAWAY_OK, true
	case "JOB_OBJECT_LIMIT_CPU_RATE_CONTROL":
		return JOB_OBJECT_LIMIT_CPU_RATE_CONTROL, true
	case "JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION":
		return JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION, true
	case "JOB_OBJECT_LIMIT_IO_RATE_CONTROL":
		return JOB_OBJECT_LIMIT_IO_RATE_CONTROL, true
	case "JOB_OBJECT_LIMIT_JOB_MEMORY":
		return JOB_OBJECT_LIMIT_JOB_MEMORY, true
	case "JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH":
		return JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH, true
	case "JOB_OBJECT_LIMIT_JOB_MEMORY_LOW":
		return JOB_OBJECT_LIMIT_JOB_MEMORY_LOW, true
	case "JOB_OBJECT_LIMIT_JOB_READ_BYTES":
		return JOB_OBJECT_LIMIT_JOB_READ_BYTES, true
	case "JOB_OBJECT_LIMIT_JOB_TIME":
		return JOB_OBJECT_LIMIT_JOB_TIME, true
	case "JOB_OBJECT_LIMIT_JOB_WRITE_BYTES":
		return JOB_OBJECT_LIMIT_JOB_WRITE_BYTES, true
	case "JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE":
		return JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, true
	case "JOB_OBJECT_LIMIT_NET_RATE_CONTROL":
		return JOB_OBJECT_LIMIT_NET_RATE_CONTROL, true
	case "JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME":
		return JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME, true
	case "JOB_OBJECT_LIMIT_PRIORITY_CLASS":
		return JOB_OBJECT_LIMIT_PRIORITY_CLASS, true
	case "JOB_OBJECT_LIMIT_PROCESS_MEMORY":
		return JOB_OBJECT_LIMIT_PROCESS_MEMORY, true
	case "JOB_OBJECT_LIMIT_PROCESS_TIME":
		return JOB_OBJECT_LIMIT_PROCESS_TIME, true
	case "JOB_OBJECT_LIMIT_RATE_CONTROL":
		return JOB_OBJECT_LIMIT_RATE_CONTROL, true
	case "JOB_OBJECT_LIMIT_SCHEDULING_CLASS":
		return JOB_OBJECT_LIMIT_SCHEDULING_CLASS, true
	case "JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK":
		return JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, true
	case "JOB_OBJECT_LIMIT_SUBSET_AFFINITY":
		return JOB_OBJECT_LIMIT_SUBSET_AFFINITY, true
	case "JOB_OBJECT_LIMIT_VALID_FLAGS":
		return JOB_OBJECT_LIMIT_VALID_FLAGS, true
	case "JOB_OBJECT_LIMIT_WORKINGSET":
		return JOB_OBJECT_LIMIT_WORKINGSET, true
	case "JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG":
		return JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG, true
	case "JOB_OBJECT_NET_RATE_CONTROL_ENABLE":
		return JOB_OBJECT_NET_RATE_CONTROL_ENABLE, true
	case "JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH":
		return JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH, true
	case "JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS":
		return JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS, true
	case "JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS":
		return JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS, true
	case "JOB_OBJECT_POST_AT_END_OF_JOB":
		return JOB_OBJECT_POST_AT_END_OF_JOB, true
	case "JOB_OBJECT_SECURITY_FILTER_TOKENS":
		return JOB_OBJECT_SECURITY_FILTER_TOKENS, true
	case "JOB_OBJECT_SECURITY_NO_ADMIN":
		return JOB_OBJECT_SECURITY_NO_ADMIN, true
	case "JOB_OBJECT_SECURITY_ONLY_TOKEN":
		return JOB_OBJECT_SECURITY_ONLY_TOKEN, true
	case "JOB_OBJECT_SECURITY_RESTRICTED_TOKEN":
		return JOB_OBJECT_SECURITY_RESTRICTED_TOKEN, true
	case "JOB_OBJECT_SECURITY_VALID_FLAGS":
		return JOB_OBJECT_SECURITY_VALID_FLAGS, true
	case "JOB_OBJECT_TERMINATE_AT_END_OF_JOB":
		return JOB_OBJECT_TERMINATE_AT_END_OF_JOB, true
	case "JOB_OBJECT_UILIMIT_DESKTOP":
		return JOB_OBJECT_UILIMIT_DESKTOP, true
	case "JOB_OBJECT_UILIMIT_DISPLAYSETTINGS":
		return JOB_OBJECT_UILIMIT_DISPLAYSETTINGS, true
	case "JOB_OBJECT_UILIMIT_EXITWINDOWS":
		return JOB_OBJECT_UILIMIT_EXITWINDOWS, true
	case "JOB_OBJECT_UILIMIT_GLOBALATOMS":
		return JOB_OBJECT_UILIMIT_GLOBALATOMS, true
	case "JOB_OBJECT_UILIMIT_HANDLES":
		return JOB_OBJECT_UILIMIT_HANDLES, true
	case "JOB_OBJECT_UILIMIT_NONE":
		return JOB_OBJECT_UILIMIT_NONE, true
	case "JOB_OBJECT_UILIMIT_READCLIPBOARD":
		return JOB_OBJECT_UILIMIT_READCLIPBOARD, true
	case "JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS":
		return JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS, true
	case "JOB_OBJECT_UILIMIT_WRITECLIPBOARD":
		return JOB_OBJECT_UILIMIT_WRITECLIPBOARD, true
	case "JobObjectAssociateCompletionPortInformation":
		return JobObjectAssociateCompletionPortInformation, true
	case "JobObjectBasicAccountingInformation":
		return JobObjectBasicAccountingInformation, true
	case "JobObjectBasicAndIoAccountingInformation":
		return JobObjectBasicAndIoAccountingInformation, true
	case "JobObjectBasicLimitInformation":
		return JobObjectBasicLimitInformation, true
	case "JobObjectBasicProcessIdList":
		return JobObjectBasicProcessIdList, true
	case "JobObjectBasicUIRestrictions":
		return JobObjectBasicUIRestrictions, true
	case "JobObjectCompletionCounter":
		return JobObjectCompletionCounter, true
	case "JobObjectCompletionFilter":
		return JobObjectCompletionFilter, true
	case "JobObjectCpuRateControlInformation":
		return JobObjectCpuRateControlInformation, true
	case "JobObjectCreateSilo":
		return JobObjectCreateSilo, true
	case "JobObjectEndOfJobTimeInformation":
		return JobObjectEndOfJobTimeInformation, true
	case "JobObjectExtendedLimitInformation":
		return JobObjectExtendedLimitInformation, true
	case "JobObjectGroupInformation":
		return JobObjectGroupInformation, true
	case "JobObjectGroupInformationEx":
		return JobObjectGroupInformationEx, true
	case "JobObjectJobSetInformation":
		return JobObjectJobSetInformation, true
	case "JobObjectLimitViolationInformation":
		return JobObjectLimitViolationInformation, true
	case "JobObjectLimitViolationInformation2":
		return JobObjectLimitViolationInformation2, true
	case "JobObjectNetRateControlInformation":
		return JobObjectNetRateControlInformation, true
	case "JobObjectNetworkAccountingInformation":
		return JobObjectNetworkAccountingInformation, true
	case "JobObjectNotificationLimitInformation":
		return JobObjectNotificationLimitInformation, true
	case "JobObjectNotificationLimitInformation2":
		return JobObjectNotificationLimitInformation2, true
	case "JobObjectReserved10Information":
		return JobObjectReserved10Information, true
	case "JobObjectReserved11Information":
		return JobObjectReserved11Information, true
	case "JobObjectReserved12Information":
		return JobObjectReserved12Information, true
	case "JobObjectReserved13Information":
		return JobObjectReserved13Information, true
	case "JobObjectReserved14Information":
		return JobObjectReserved14Information, true
	case "JobObjectReserved15Information":
		return JobObjectReserved15Information, true
	case "JobObjectReserved16Information":
		return JobObjectReserved16Information, true
	case "JobObjectReserved17Information":
		return JobObjectReserved17Information, true
	case "JobObjectReserved18Information":
		return JobObjectReserved18Information, true
	case "JobObjectReserved19Information":
		return JobObjectReserved19Information, true
	case "JobObjectReserved1Information":
		return JobObjectReserved1Information, true
	case "JobObjectReserved20Information":
		return JobObjectReserved20Information, true
	case "JobObjectReserved21Information":
		return JobObjectReserved21Information, true
	case "JobObjectReserved22Information":
		return JobObjectReserved22Information, true
	case "JobObjectReserved23Information":
		return JobObjectReserved23Information, true
	case "JobObjectReserved24Information":
		return JobObjectReserved24Information, true
	case "JobObjectReserved25Information":
		return JobObjectReserved25Information, true
	case "JobObjectReserved26Information":
		return JobObjectReserved26Information, true
	case "JobObjectReserved27Information":
		return JobObjectReserved27Information, true
	case "JobObjectReserved28Information":
		return JobObjectReserved28Information, true
	case "JobObjectReserved2Information":
		return JobObjectReserved2Information, true
	case "JobObjectReserved3Information":
		return JobObjectReserved3Information, true
	case "JobObjectReserved4Information":
		return JobObjectReserved4Information, true
	case "JobObjectReserved5Information":
		return JobObjectReserved5Information, true
	case "JobObjectReserved6Information":
		return JobObjectReserved6Information, true
	case "JobObjectReserved7Information":
		return JobObjectReserved7Information, true
	case "JobObjectReserved8Information":
		return JobObjectReserved8Information, true
	case "JobObjectReserved9Information":
		return JobObjectReserved9Information, true
	case "JobObjectSecurityLimitInformation":
		return JobObjectSecurityLimitInformation, true
	case "JobObjectSiloBasicInformation":
		return JobObjectSiloBasicInformation, true
	case "MaxJobObjectInfoClass":
		return MaxJobObjectInfoClass, true
	case "ToleranceHigh":
		return ToleranceHigh, true
	case "ToleranceIntervalLong":
		return ToleranceIntervalLong, true
	case "ToleranceIntervalMedium":
		return ToleranceIntervalMedium, true
	case "ToleranceIntervalShort":
		return ToleranceIntervalShort, true
	case "ToleranceLow":
		return ToleranceLow, true
	case "ToleranceMedium":
		return ToleranceMedium, true
	default:
		return Value(0), false
	}
}
