// Code generated by win32defs-gen; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata 71.0.26-preview (758efe32666596b8596c58a8c46631da23757a914713b4e88403bbfa5110cb38).

package jobobject

import (
	"unsafe"

	"github.com/depthbomb/win32defs/foundation"
)

// JOBOBJECT_BASIC_PROCESS_ID_LIST projects Windows.Win32.System.JobObjects.JOBOBJECT_BASIC_PROCESS_ID_LIST.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-jobobject_basic_process_id_list.
type JOBOBJECT_BASIC_PROCESS_ID_LIST struct {
	NumberOfAssignedProcesses uint32
	NumberOfProcessIdsInList  uint32
	// Flexible array: this is the metadata-declared initial extent.
	// Additional elements require a larger native allocation.
	ProcessIdList [1]uintptr
}

// JOBOBJECT_BASIC_UI_RESTRICTIONS projects Windows.Win32.System.JobObjects.JOBOBJECT_BASIC_UI_RESTRICTIONS.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-jobobject_basic_ui_restrictions.
type JOBOBJECT_BASIC_UI_RESTRICTIONS struct {
	UIRestrictionsClass JOB_OBJECT_UILIMIT
}

// JOBOBJECT_END_OF_JOB_TIME_INFORMATION projects Windows.Win32.System.JobObjects.JOBOBJECT_END_OF_JOB_TIME_INFORMATION.
// See https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-jobobject_end_of_job_time_information.
type JOBOBJECT_END_OF_JOB_TIME_INFORMATION struct {
	EndOfJobTimeAction JOB_OBJECT_TERMINATE_AT_END_ACTION
}

// JOBOBJECT_JOBSET_INFORMATION projects Windows.Win32.System.JobObjects.JOBOBJECT_JOBSET_INFORMATION.
type JOBOBJECT_JOBSET_INFORMATION struct {
	MemberLevel uint32
}

// JOBOBJECT_RATE_CONTROL_TOLERANCE projects Windows.Win32.System.JobObjects.JOBOBJECT_RATE_CONTROL_TOLERANCE.
type JOBOBJECT_RATE_CONTROL_TOLERANCE int32

// JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL projects Windows.Win32.System.JobObjects.JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL.
type JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL int32

// JOB_OBJECT_CPU_RATE_CONTROL projects Windows.Win32.System.JobObjects.JOB_OBJECT_CPU_RATE_CONTROL.
type JOB_OBJECT_CPU_RATE_CONTROL uint32

// JOB_OBJECT_LIMIT projects Windows.Win32.System.JobObjects.JOB_OBJECT_LIMIT.
type JOB_OBJECT_LIMIT uint32

// JOB_OBJECT_NET_RATE_CONTROL_FLAGS projects Windows.Win32.System.JobObjects.JOB_OBJECT_NET_RATE_CONTROL_FLAGS.
// See https://learn.microsoft.com/windows/win32/api/winnt/ne-winnt-job_object_net_rate_control_flags.
type JOB_OBJECT_NET_RATE_CONTROL_FLAGS int32

// JOB_OBJECT_SECURITY projects Windows.Win32.System.JobObjects.JOB_OBJECT_SECURITY.
type JOB_OBJECT_SECURITY uint32

// JOB_OBJECT_TERMINATE_AT_END_ACTION projects Windows.Win32.System.JobObjects.JOB_OBJECT_TERMINATE_AT_END_ACTION.
type JOB_OBJECT_TERMINATE_AT_END_ACTION uint32

// JOB_OBJECT_UILIMIT projects Windows.Win32.System.JobObjects.JOB_OBJECT_UILIMIT.
type JOB_OBJECT_UILIMIT uint32

// JOB_SET_ARRAY projects Windows.Win32.System.JobObjects.JOB_SET_ARRAY.
type JOB_SET_ARRAY struct {
	JobHandle   foundation.HANDLE
	MemberLevel uint32
	Flags       uint32
}

// Verify metadata-derived Windows ABI sizes, alignments, and field offsets.
var (
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(JOBOBJECT_BASIC_PROCESS_ID_LIST))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(JOBOBJECT_BASIC_PROCESS_ID_LIST))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(JOBOBJECT_BASIC_PROCESS_ID_LIST{}.NumberOfAssignedProcesses)]byte{}
	_ [4]byte                                      = [unsafe.Offsetof(JOBOBJECT_BASIC_PROCESS_ID_LIST{}.NumberOfProcessIdsInList)]byte{}
	_ [8]byte                                      = [unsafe.Offsetof(JOBOBJECT_BASIC_PROCESS_ID_LIST{}.ProcessIdList)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOBOBJECT_BASIC_UI_RESTRICTIONS))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOBOBJECT_BASIC_UI_RESTRICTIONS))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(JOBOBJECT_BASIC_UI_RESTRICTIONS{}.UIRestrictionsClass)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOBOBJECT_END_OF_JOB_TIME_INFORMATION))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOBOBJECT_END_OF_JOB_TIME_INFORMATION))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(JOBOBJECT_END_OF_JOB_TIME_INFORMATION{}.EndOfJobTimeAction)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOBOBJECT_JOBSET_INFORMATION))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOBOBJECT_JOBSET_INFORMATION))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(JOBOBJECT_JOBSET_INFORMATION{}.MemberLevel)]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOBOBJECT_RATE_CONTROL_TOLERANCE))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOBOBJECT_RATE_CONTROL_TOLERANCE))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_CPU_RATE_CONTROL))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_CPU_RATE_CONTROL))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_LIMIT))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_LIMIT))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_NET_RATE_CONTROL_FLAGS))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_NET_RATE_CONTROL_FLAGS))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_SECURITY))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_SECURITY))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_TERMINATE_AT_END_ACTION))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_TERMINATE_AT_END_ACTION))]byte{}
	_ [4]byte                                      = [unsafe.Sizeof(*new(JOB_OBJECT_UILIMIT))]byte{}
	_ [4]byte                                      = [unsafe.Alignof(*new(JOB_OBJECT_UILIMIT))]byte{}
	_ [12 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte = [unsafe.Sizeof(*new(JOB_SET_ARRAY))]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Alignof(*new(JOB_SET_ARRAY))]byte{}
	_ [0]byte                                      = [unsafe.Offsetof(JOB_SET_ARRAY{}.JobHandle)]byte{}
	_ [4 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(JOB_SET_ARRAY{}.MemberLevel)]byte{}
	_ [8 + (unsafe.Sizeof(uintptr(0))-4)/4*4]byte  = [unsafe.Offsetof(JOB_SET_ARRAY{}.Flags)]byte{}
)
